### ISSUE TITLE
Roboto mono italics different width

### ISSUE THREAD

**Issue by quicknir** [google/fonts#142] opened 2015-11-05 23:16 UTC
On my machine (Fedora 20), it looks like Roboto mono changes width based on whether or not it is italicized. Can this be confirmed?

**Comment by davelab6** [comment] 2015-11-06 05:56
I can confirm this as a bug/feature of the current release; this was acknowledged by Christian Robertson, the designer of Roboto, as something that could be changed in a future update, but I don't know when that work might be done by him.

**Comment by quicknir** [comment] 2015-11-06 18:15
Fair enough. FWIW, I'd like to express interest in changing this. Personally, I find it somewhat frustrating that so many fonts advertise themselves as mono, but differ for bold/italics. I'd argue that from a practical programmer's point of view, such a font is not really mono. Syntax highlighting that involves bold/italics is common for many languages, and even the default in many IDEs (e.g. Eclipse for Java or C++).

**Comment by erusev** [comment] 2017-01-03 14:02
Is there any progress on this?

**Comment by octachrome** [comment] 2017-03-10 10:36
+1

I'd like to use Roboto Mono with the [Ace](https://github.com/ajaxorg/ace) editor, but the editor currently calculates the cursor position incorrectly for italic text due to this issue.

**Comment by arm32x** [comment] 2017-06-21 14:13
@octachrome I totally agree. I’m actually using this in a project right now, and it doesn’t work properly because of this.

The project: https://arm32x.github.io/material-mark

**Comment by arm32x** [comment] 2017-12-04 18:14
Any workarounds or quick fixes available for this?

**Comment by thundernixon** [comment] 2019-01-29 22:09
Moving this to issue #1832 in order to group this fixing work with a couple of closely-related bugs and to make it a bit easier for a designer to start fixing in the future.

**Closed by thundernixon** 2019-01-29 22:09 UTC
Labels: Priority 2 - Important but not Urgent, z_Roboto_Mono
