### ISSUE TITLE
Update Nuosu SIL

### ISSUE THREAD

**Issue by devosb** [google/fonts#5243] opened 2022-09-15 00:58 UTC
**Describe the bug**

The Nuosu SIL font on Google Fonts does not have several characters that are in the font from SIL. Specifically I noticed the full width punctuation characters (such as U+FF01 FULLWIDTH EXCLAMATION MARK) are displayed in a fallback from when using the font from Google Fonts. From looking at the list of codepoints in the WOFF2 fonts from Google, it seems like the ranges of circled numbers, starting at

- U+2460 CIRCLED DIGIT ONE
- U+2469 CIRCLED NUMBER TEN
- U+2776 DINGBAT NEGATIVE CIRCLED DIGIT ONE

have also been removed. There are other characters missing, such some extended Latin (U+0041 LATIN CAPITAL LETTER A and U+2013 EN DASH) that I did not list here.

**To Reproduce**
Look at the characters

！＂（），．／：；［］｛｝

with Nuosu SIL from Google Fonts and with the font installed locally. The codepoints of the characters in the sample above is
```
U+FF01 FULLWIDTH EXCLAMATION MARK
U+FF02 FULLWIDTH QUOTATION MARK
U+FF08 FULLWIDTH LEFT PARENTHESIS
U+FF09 FULLWIDTH RIGHT PARENTHESIS
U+FF0C FULLWIDTH COMMA
U+FF0E FULLWIDTH FULL STOP
U+FF0F FULLWIDTH SOLIDUS
U+FF1A FULLWIDTH COLON
U+FF1B FULLWIDTH SEMICOLON
U+FF3B FULLWIDTH LEFT SQUARE BRACKET
U+FF3D FULLWIDTH RIGHT SQUARE BRACKET
U+FF5B FULLWIDTH LEFT CURLY BRACKET
U+FF5D FULLWIDTH RIGHT CURLY BRACKET
```

**Expected behavior**
The Google Fonts version of Nuosu should look like the locally installed version.

**Screenshots**

In the following screenshot LPR = local path-referenced font, GF = Google Font, FLO = our own internal font server. Screenshots are from current Chrome on Ubuntu 22.04.

![nuosu_sil](https://user-images.githubusercontent.com/12450072/190288723-de350184-0fef-4002-bf4c-0b4b8063c857.png)

**Additional context**
Tested with Firefox and Chrome on Ubuntu 22.04, and those browsers, plus Edge, on Windows 10.

**Comment by devosb** [comment] 2022-09-15 01:06
The second character in the list, U+FF02 FULLWIDTH QUOTATION MARK, was mis-encoded in v2.200 of the font (which is the version on Google Fonts right now). So while the display should be the same, for that character, the expected display is incorrect. This has been [fixed in the 2.300](https://github.com/google/fonts/issues/4516#issuecomment-1247451729) version of the font, which was just released.

**Comment by devosb** [comment] 2022-09-15 15:03
At first I thought that the missing characters were due to the `unicode-range:` field in the CSS file. Even after I added the needed ranges to a local copy of the CSS file, the missing characters were still not displayed. I downloaded the WOFF2 files using `curl`, and the WOFF2 file itself does not seem to have the missing characters.

**Comment by emmamarichal** [comment] 2022-10-14 13:32
Hello @devosb,
Thanks for this update. Did you take the opportunity to solve this issue? https://github.com/silnrsi/font-nuosu/issues/1

**Comment by RosaWagner** [comment] 2022-10-14 13:52
@devosb you can see in [the glyphset repo](https://github.com/googlefonts/glyphsets/tree/main/Lib/glyphsets/encodings) if some glyphs are missing from the subset definition, if yes please open an issue to propose a list of unicodes and specify which .nam file would be affected, we'll try to resolve that.

**Comment by devosb** [comment] 2022-10-20 13:59
https://github.com/silnrsi/font-nuosu/issues/1 should be fixed, more details in https://github.com/silnrsi/font-nuosu/issues/1#issuecomment-1285585291

**Comment by devosb** [comment] 2022-10-20 14:29
Even if the [glyphset repo](https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/yi_unique-glyphs.nam) is updated for this script, that will not fix all the problems. To illustrate, U+FF01 is already listed in this file, and this character is in the font that we released. However, there are two problems with this character with this font on Google fonts

1. The character is not listed in the `unicode-range` field of the CSS file from Google Fonts.
2. Even if the `unicode-range` field was correct, the character is not in the WOFF2 font from Google Fonts. More details in a [comment above](https://github.com/google/fonts/issues/5243#issuecomment-1248230692).

**Comment by RosaWagner** [comment] 2022-10-20 14:43
The character is missing/not listed because it may be subsetted from the font following the list of glyphs in the repo I linked above, and the unicode-range field also follow it. Please look at https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/yi_unique-glyphs.nam, if glyphs are missing we can add them and re-push the font so it gets subsetted differently.

Some of the codepoints you listed above have been added to the list few weeks ago, but probably after we merged Nuosu SIL so they were not taken into consideration. Before re-releasing the font, I would like to make sure that no other glyphs from Yi are missing.

**Comment by emmamarichal** [comment] 2022-12-02 10:20
Hi @devosb,
Have you looked to see if there are any other missing glyphs as Rosalie suggested, so we can fix this problem?

**Comment by devosb** [comment] 2022-12-05 15:08
Sorry for the delay. Here are all the characters (grouped by block) that are in the font, but not in the glyphset.

Unicode block | Characters in Nuosu SIL v2.300 but not the Google Fonts glyphset
------------- | ---------------
Basic Latin|U+0021..U+007E
Latin 1 Supplement|U+00A1..U+00FF
Latin Extended A|U+0131, U+0152..U+0153, U+0160..U+0161, U+0178, U+017D..U+017E
Latin Extended B|U+0192
Spacing Modifier Letters|U+02C6..U+02C7, U+02D0, U+02D8..U+02DD
Combining Diacritical Marks|U+034F
Greek And Coptic|U+03C0
General Punctuation|U+2000..U+200D, U+2010..U+2015, U+2018..U+201A, U+201C..U+201E, U+2020..U+2022, U+2026..U+2029, U+202F..U+2030, U+2039..U+203A, U+2044, U+2060
Superscripts And Subscripts|U+2074..U+2077, U+2088, U+2099
Currency Symbols|U+20AC
Letterlike Symbols|U+2122, U+2126
Mathematical Operators|U+2202, U+2206, U+220F, U+2211..U+2212, U+2215, U+2219..U+221A, U+221E, U+222B, U+2248, U+2260, U+2264..U+2265
Control Pictures|U+2423
Enclosed Alphanumerics|U+2460..U+2473
Geometric Shapes|U+25CA, U+25CC
Dingbats|U+2776..U+277F
CJK Symbols And Punctuation|U+3000, U+3003, U+3012..U+3013
Private Use Area|U+F130..U+F131
Alphabetic Presentation Forms|U+FB01..U+FB02
Variation Selectors|U+FE00..U+FE0F
Arabic Presentation Forms B|U+FEFF
Halfwidth And Fullwidth Forms|U+FF02, U+FF08..U+FF09, U+FF0D..U+FF0F, U+FF3B, U+FF3D, U+FF5B..U+FF5E
Specials|U+FFFC..U+FFFD

**Comment by RosaWagner** [comment] 2022-12-09 09:46
Thanks a lot @devosb ! @simoncozens is working on completing the subsets definition, i'll transfer this issue to him ;)

**Comment by simoncozens** [comment] 2023-03-02 17:18
I get quite a few of these glyphset subsetting issues so I just wrote a little script to debug them. Here's its output for nuosusil:

```
The following codepoints supported by the font are not covered by
any subsets defined in the font's metadata file.
U+02C7 CARON: try adding one of: canadian-aboriginal, tifinagh
U+02D8 BREVE: try adding canadian-aboriginal
U+02D9 DOT ABOVE: try adding canadian-aboriginal
U+02DB OGONEK: try adding canadian-aboriginal
U+03C0 GREEK SMALL LETTER PI: try adding greek
U+200C ZERO WIDTH NON-JOINER: try adding one of: arabic, avestan, balinese, batak, bengali, brahmi, buginese, buhid, myanmar, cham, chakma, gujarati, gurmukhi, hanunoo, devanagari, javanese, kaithi, kannada, kayah-li, kharoshthi, khmer, lepcha, limbu, malayalam, mandaic, meetei-mayek, mongolian, new-tai-lue, oriya, phags-pa, rejang, saurashtra, sinhala, sundanese, syloti-nagri, tagalog, tagbanwa, tai-le, tai-tham, tai-viet, tamil, telugu, thaana, thai, tibetan, tifinagh
U+200D ZERO WIDTH JOINER: try adding one of: arabic, avestan, balinese, batak, bengali, brahmi, buginese, buhid, myanmar, cham, chakma, gujarati, gurmukhi, hanunoo, devanagari, javanese, kaithi, kannada, kayah-li, kharoshthi, lepcha, limbu, malayalam, mandaic, meetei-mayek, mongolian, new-tai-lue, oriya, phags-pa, rejang, saurashtra, sinhala, sundanese, syloti-nagri, tagalog, tagbanwa, tai-le, tai-tham, tai-viet, tamil, telugu, thaana, thai, tibetan, tifinagh
U+2010 HYPHEN: try adding one of: arabic, cham, coptic, kaithi, kayah-li, kharoshthi, lisu, sundanese, syloti-nagri
U+2011 NON-BREAKING HYPHEN: try adding one of: arabic, syloti-nagri
U+202F NARROW NO-BREAK SPACE: try adding mongolian
U+2219 BULLET OPERATOR: try adding tai-tham
U+2460 CIRCLED DIGIT ONE: try adding mongolian
U+2461 CIRCLED DIGIT TWO: try adding mongolian
U+2462 CIRCLED DIGIT THREE: try adding mongolian
U+2463 CIRCLED DIGIT FOUR: try adding mongolian
U+2464 CIRCLED DIGIT FIVE: try adding mongolian
U+2465 CIRCLED DIGIT SIX: try adding mongolian
U+2466 CIRCLED DIGIT SEVEN: try adding mongolian
U+2467 CIRCLED DIGIT EIGHT: try adding mongolian
U+2468 CIRCLED DIGIT NINE: try adding mongolian
U+2469 CIRCLED NUMBER TEN: try adding mongolian
U+246A CIRCLED NUMBER ELEVEN: try adding mongolian
U+246B CIRCLED NUMBER TWELVE: try adding mongolian
U+246C CIRCLED NUMBER THIRTEEN: try adding mongolian
U+246D CIRCLED NUMBER FOURTEEN: try adding mongolian
U+246E CIRCLED NUMBER FIFTEEN: try adding mongolian
U+246F CIRCLED NUMBER SIXTEEN: try adding mongolian
U+2470 CIRCLED NUMBER SEVENTEEN: try adding mongolian
U+2471 CIRCLED NUMBER EIGHTEEN: try adding mongolian
U+2472 CIRCLED NUMBER NINETEEN: try adding mongolian
U+2473 CIRCLED NUMBER TWENTY: try adding mongolian
U+25CC DOTTED CIRCLE: try adding one of: balinese, batak, bengali, brahmi, buginese, buhid, myanmar, canadian-aboriginal, cham, chakma, coptic, gujarati, gurmukhi, hanunoo, hebrew, devanagari, javanese, kaithi, kannada, kayah-li, kharoshthi, khmer, lao, lepcha, limbu, malayalam, mandaic, meetei-mayek, mongolian, new-tai-lue, oriya, phags-pa, rejang, saurashtra, sinhala, sundanese, syloti-nagri, tagalog, tagbanwa, tai-le, tai-viet, tamil, telugu, thaana, thai, tibetan, tifinagh
U+3000 IDEOGRAPHIC SPACE: try adding one of: chinese-simplified, chinese-traditional, japanese
U+3003 DITTO MARK: try adding one of: chinese-simplified, chinese-traditional, japanese
U+3012 POSTAL MARK: try adding one of: chinese-simplified, chinese-traditional, japanese
U+3013 GETA MARK: try adding one of: chinese-simplified, japanese
U+FE00 VARIATION SELECTOR-1: try adding phags-pa
U+FF01 FULLWIDTH EXCLAMATION MARK: try adding one of: chinese-simplified, japanese
U+FF02 FULLWIDTH QUOTATION MARK: try adding chinese-simplified
U+FF08 FULLWIDTH LEFT PARENTHESIS: try adding one of: chinese-simplified, japanese
U+FF09 FULLWIDTH RIGHT PARENTHESIS: try adding one of: chinese-simplified, japanese
U+FF0C FULLWIDTH COMMA: try adding one of: chinese-simplified, japanese
U+FF0E FULLWIDTH FULL STOP: try adding one of: chinese-simplified, japanese
U+FF0F FULLWIDTH SOLIDUS: try adding one of: chinese-simplified, japanese
U+FF1A FULLWIDTH COLON: try adding one of: chinese-simplified, japanese
U+FF1B FULLWIDTH SEMICOLON: try adding one of: chinese-simplified, japanese
U+FF3B FULLWIDTH LEFT SQUARE BRACKET: try adding one of: chinese-simplified, japanese
U+FF3D FULLWIDTH RIGHT SQUARE BRACKET: try adding one of: chinese-simplified, japanese
U+FF5B FULLWIDTH LEFT CURLY BRACKET: try adding one of: chinese-simplified, japanese
U+FF5C FULLWIDTH VERTICAL LINE: try adding one of: chinese-simplified, japanese
U+FF5D FULLWIDTH RIGHT CURLY BRACKET: try adding one of: chinese-simplified, japanese
U+FF5E FULLWIDTH TILDE: try adding chinese-simplified

Or you can add these codepoints to one of the subsets supported by the font: latin, latin-ext, menu, yi
```

**Comment by devosb** [comment] 2023-03-03 16:15
Thanks for the analysis. I am not sure how this data will be used. Are you intending to add all the characters mentioned to various subsets?

For this font (unlike the WSTech Arabic fonts) there is no shaping, therefore there should not be any issue with having characters in different subsets. With the Arabic fonts, having characters in different subsets breaks shaping if there is an OpenType rule that involves characters from two subsets.

Adding all the full width characters to a `chinese-simplified` subset should work (for those characters). Using `chinese-simplified` seems to be a good choice, since you could add the full width characters, and U+3000 IDEOGRAPHIC SPACE (for example), in just one extra subset. If U+3000 was in the `japanese` subset, then you would still need the `chinese-simplified` subset for U+FF02 FULLWIDTH QUOTATION MARK (which is not listed for `japanese`).

Having a `mongolian` subset for the circled numbers seems strange for a font for use in southwestern China, but I guess it would work. Adding U+02C7 CARON to either a `canadian-aboriginal` or `tifinagh` subset seems stranger still, but still workable. U+02C7 was added to the font since it is in the MacRoman character set, maybe it could go in the `latin-ext subset`. U+202F NARROW NO-BREAK SPACE is so typesetters have full control over the layout of text, so maybe it can also go into `latin-ext`. U+202F is not for supporting `mongolian` in this font.

**Comment by simoncozens** [comment] 2023-03-03 16:45
We could either add some of these codepoints to different subsets, or we could add some of these subsets to the font's metadata file.

Think about these subsets as "slices of Unicode". The font's metadata declares which slices it supports well, and those are the only slices of the font that get served. The full-width characters *are* in `chinese-simplified`, but since this font doesn't have hanzi, there isn't a high-enough percentage of the `chinese-simplified` slice supported by the font for us to declare it as supported in the metadata, and since these full-width characters are *only* in the `chinese-simplified` subset, and this font "doesn't support `chinese-simplified`" then that slice of the font doesn't get served.

There are various ways we could fix this:

* Add the full-width characters, circled characters, etc. to the `yi` subset; now they're in a supported and declared subset so they get served, job done.
* Manually declare that this font "supports" Mongolian and Chinese in the metadata file, so that those subsets get served and those codepoints are accessible.
* Add a new subset for "generic CJK stuff".
* Lower the percentage required to declare a subset "supported". I do wonder if it should be *any* characters in a subset causes that subset to get served.

**Comment by jvgaultney** [comment] 2023-03-06 16:29
The difficulty with the concept of Unicode 'slices' is that it tends to reinforce a flawed conceptual model: That script A = slice X, script B = slice Y, and that the slices are like that of a pie, where the good stuff ends up in only one slice. That may have not been how the GF subsets were designed but that's the way they seem to have been put together in practice, and may be a contributing factor in how absurdly long it seems to take to get things added to the subsets.

Please just add the missing chars to the Yi subset. We've done the research and confirm that people want to use those chars with Yi text. _It shouldn't matter what Unicode range the characters are from ._  Unicode range is irrelevant. We just want the font to work properly.

GF subsets need to be defined (and though of) as arbitrary collections of USVs that correspond to specific writing systems rather than a list of the Unicode-defined ranges with some additional tweaks.

**Comment by simoncozens** [comment] 2023-03-06 16:51
Huh, it turns out I actually added full width punctuation to the Yi glyphset [six months ago](https://github.com/googlefonts/glyphsets/pull/73). If that still isn't working, this means that the internal engineering team have not synchronised the public glyphsets with their internal copy...

I've created a [new PR](https://github.com/googlefonts/glyphsets/pull/100) for the rest of the codepoints.

**Comment by RosaWagner** [comment] 2023-06-01 13:57
@jvgaultney @devosb can you confirm the issue is fixed ?

**Comment by devosb** [comment] 2023-06-02 20:39
The situation is improved, but since the version of the font that Google has  is v2.200 (both WOFF2 and TTF in a zip file), and [v2.300 is the latest version we have released](https://github.com/silnrsi/font-nuosu/releases/tag/v2.300), I am unable to do a full test. Or did you want me to test what I can before you push the latest version through?

**Comment by RosaWagner** [comment] 2023-06-22 14:07
Ah okay, let's onboard this version first then and see.
cc @emmamarichal

**Closed** 2023-06-28 13:48 UTC
Labels: - Ready for Review, I Font Upgrade
