### ISSUE TITLE
Infinite Scrolling in google fonts

### ISSUE THREAD

**Issue by Adithya-Merugu** [google/fonts#6710] opened 2023-09-14 18:59 UTC
#This issue also works for requesting features. 

**Describe the issue**
Glitch of endless page scrolling

**To Reproduce**
In preview section add any text and then while checking fonts scroll down 

**Expected behavior**
smooth scrolling

**Screenshots**
this is a video of the the incident(https://drive.google.com/file/d/1UgccdDgBLGAcRpfc44blRgQVAytLPjZh/view?usp=sharing)

here is the preview image of it
![font](https://github.com/google/fonts/assets/120652724/0f4aa9bf-c6e1-4871-bffb-9834619c7f7a)
[screen-capture (1).webm](https://github.com/google/fonts/assets/120652724/fbacc404-311d-45aa-910b-af02b78d560f)

https://drive.google.com/file/d/1dxd_W_Xa-57zb8vMeKMMjhjLWBr8XIFN/view?usp=sharing

**Comment by eliheuer** [comment] 2023-09-19 03:10
I can't reproduce this on Chrome 116 and MacOS 13.

I'm going to close this, but if you are certain this is caused by Google Fonts, please provide more information about the browser and operating system you are experiencing this on.

**Closed by eliheuer** 2023-09-19 03:10 UTC
Labels: I Tools / workflow / repo, I API / Website / Platform, I Request
