### ISSUE TITLE
PT Sans displays Russian Ruble (₽) instead of Indian Rupee symbol (₹) and Turkish Lira (₺)

### ISSUE THREAD

**Issue by neochief** [google/fonts#2787] opened 2020-11-03 12:13 UTC
PT Sans has wrong glyphs for a set of currencies, such as ₹ or ₺. They all display a Russian ruble instead of falling back to default.

**Comment by fitojb** [comment] 2020-11-03 13:25
Duplicate of #2406

**Comment by RosaWagner** [comment] 2020-12-08 10:45
I close this since it is a duplicate

**Closed by RosaWagner** 2020-12-08 10:45 UTC
