### ISSUE TITLE
Add Unbounded

### ISSUE THREAD

**Issue by tobestobs** [google/fonts#5205] opened 2022-09-06 10:51 UTC
Font Project Git Repo URL: https://github.com/w3f/unbounded

Super short description of the Font Family:

Unbounded by both name and nature, it is available in six display weights ranging from light to black, as well as a single variable font. The typeface supports both Latin and Cyrillic scripts with over 1300 individual glyphs, including a collection of symbols and a unique figure building system. In addition the sizeable glyph set accommodates for hundreds of languages worldwide.

Unbounded is the product of a joint collaboration between [Studio Koto](https://koto.studio/), [NaN](https://www.nan.xyz/), [Parity Technologies](https://parity.io/) and [Web3 Foundation](https://www.web3.foundation/) for [Polkadot Network](https://polkadot.network/).

[unbounded.polkadot.network](https://unbounded.polkadot.network/)

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

Image: 
<img width="1629" alt="Screen Shot 2022-09-06 at 12 50 45 PM" src="https://user-images.githubusercontent.com/49656407/188616888-2987d65d-df38-43a6-ac31-40d4aa803538.png">

**Comment by davelab6** [comment] 2022-09-06 22:37
Duplicate of #5103

**Closed by davelab6** 2022-09-06 22:37 UTC
Labels: I New Font, II Submission

**Comment by vv-monsalve** [comment] 2022-09-07 15:16
Moved the image there and the url now it's a public repo.
