### ISSUE TITLE
Sora Bold 'l' in MS Win Word is broken

### ISSUE THREAD

**Issue by davelab6** [google/fonts#4898] opened 2022-07-06 20:07 UTC
Sora Bold `l` in MS Win Word is broken

![image001](https://user-images.githubusercontent.com/261579/177616208-0f05ff12-75e5-4f30-91ad-b693b4d0ad90.png)

**Comment by RosaWagner** [comment] 2022-07-27 11:44
upstream repo: https://github.com/sora-xor/sora-font

**Comment by emmamarichal** [comment] 2022-11-03 09:09
Hello! I can't reproduce the bug. I tried with Microsoft Word on Windows 11. Do we have more details about this bug?
Note: I can see on the screenshot that it also concerns the 'T'

<img width="886" alt="Capture d’écran 2022-11-03 à 10 06 12" src="https://user-images.githubusercontent.com/64773544/199682674-4a6fbc95-b672-4aa8-acdc-67c397b8d399.png">

**Comment by RosaWagner** [comment] 2022-12-08 11:33
Closing this since we can't replicate. The last version is released and no problem in the sources. 

It could be that the user in having an old version if Windows and MS Office that doesn't support variable fonts very well. Static files are to be preferred in that case.

**Closed by RosaWagner** 2022-12-08 11:33 UTC
Labels: -- Needs Upstream Resolution, I Font Bug

**Comment by juliekinsella** [comment] 2023-01-25 13:54
This still occurs in word and Powerpoint. When you type the words Its finally here in Sora and then bold it rather than using the semi bold sora font - it still looses the ll. - See below
[Sora font issue.docx](https://github.com/google/fonts/files/10499920/Sora.font.issue.docx)

**Comment by emmamarichal** [comment] 2023-01-25 14:22
hello @juliekinsella,
I push the tests further, I didn't manage to get exactly the bug in the screenshot, but I've got this:

<img width="838" alt="Capture d’écran 2023-01-25 à 15 17 11" src="https://user-images.githubusercontent.com/64773544/214587947-77a92647-7466-4db8-bb2b-3a606348e200.png">

I'll investigate, thanks for the report
