### ISSUE TITLE
Siemreap font for Khmer language does not render correctly on iOS and macOS 

### ISSUE THREAD

**Issue by MakaraSok** [google/fonts#6123] opened 2023-03-28 09:42 UTC
The affected font: https://fonts.google.com/specimen/Siemreap

**Describe the bug**
@sovichet @danhhong 

Siemreap font looks broken when viewing texts on iOS or macOS.

| iOS | macOS | Windows |
| --- | --- | --- |
| <img width=200 src="https://user-images.githubusercontent.com/28331388/228184694-229728f2-2cb0-4d27-9d06-a78ed4a94793.png"> | <img width=200 src="https://user-images.githubusercontent.com/28331388/228184974-dadc2556-b878-4c13-862a-3a4ce29b8a2b.png"> | <img width=200 src="https://user-images.githubusercontent.com/28331388/228185109-1580c1f0-1b75-422e-9cb8-8c0e7d2d2aef.png"> |

A specific example of the issue is when there is a subscript (aka coeng) followed by an above vowel (i.e.  ិ, ី, ឹ, ឺ or ើ). The subscript goes out of place and renders unreadable/incorrect/unexpected words.

មន្ត្រី should be rendered as <img width=50 src="https://user-images.githubusercontent.com/28331388/228186749-98776702-056a-4bcb-898d-328cc3841f55.png">
but instead it is rendered as <img width=50 src="https://user-images.githubusercontent.com/28331388/228187375-0f39c36a-b975-423f-b9b6-081225624fd8.png">

There are several more of these on page. Here is the link to it for you to check and see for yourself. :)
https://library.npic.edu.kh

**To Reproduce**
Go to an iOS or macOS device and load this [page](https://library.npic.edu.kh) on Safari to see the incorrect/unexpected rendering of the text.

You can also see this issue when viewing the font's landing page:
<img width=300 src="https://user-images.githubusercontent.com/28331388/228193380-ca2bf898-cca9-4f29-9219-9e881aca5764.png">

**Expected behavior**
Certain vowels and subscript combination have to be rendered correctly on iOS and macOS.
The same texts rendered on Android and Windows look correct and those are what is expected.

**Screenshots**
See in lines above.

**Additional context**
  - iOS/iPadOS 16.4
    - Safari 16.4
  - macos Ventura 13.3
    - Safari 16.4
  - Windows 11?
    - Chrome ?

**Comment by simoncozens** [comment] 2023-03-28 16:44
I don't think it needs the above vowel. Any double coeng conjunct is wrong: មន្ត្រ

<img width="660" alt="Screenshot 2023-03-28 at 17 43 15" src="https://user-images.githubusercontent.com/106728/228310155-1b0b7f54-4320-46e0-bc00-cf06090b9d85.png">
(left is Safari, right is Chrome)

This makes me suspect the Mac OS shaping engine.

**Comment by simoncozens** [comment] 2023-03-28 17:05
OK, no, I see what's going on, and this is a weird one. It is a problem with Apple's shaping engine *and* the font.

Font files have two ways of specifying how they implement complex layout: OpenType `GPOS`/`GSUB` layout tables, and Apple's own TrueType implementation (`morx` tables). `morx` is very rare as it was only implemented by Apple, and OpenType took over as the "standard" way to do things.

At the same time, there are different implementations of *OpenType* (GPOS shaping: the open source Harfbuzz and Apple's CoreText (there's also Windows DirectWrite but that's not relevant to this issue). Sometimes there are differences between how they handle complex scripts. In particular, there may be some bugs in CoreText's handling of Khmer.

So when a font is being rendered on Apple, `morx` is used when it is present in the font, and `GSUB`/`GPOS` is used when `morx` is not present.

What is happening in this case is that the Siemreap font contains *both* `GSUB`/`GPOS` and `morx` tables. In the "desktop" font, this would mean that `morx` would be used for layout on Apple and `GSUB`/`GPOS` everywhere else. But our web API software removes the `morx` table, leaving the `GSUB`/`GPOS` tables. (I think this is actually a sensible thing to do, for complicated reasons.) This means that when this is used *as a web font*, `GSUB`/`GPOS` is used for layout *everywhere*. But because of bugs in the Apple shaping engine, the `GSUB`/`GPOS` code which worked fine on Harfbuzz (Chrome) does not work properly when rendered using CoreText. The `morx` code knew about CoreText's bugs and could work around them, which is why it worked on desktop (and why the font passed our QA processes); without the `morx` code we are at the mercy of bugs in the Apple shaper.

I'll investigate further and file a bug with Apple.

**Comment by danhhong** [comment] 2023-03-29 00:39
I update already, I will check again my github account. Thank you for your feedback

________________________________
From: Makara ***@***.***>
Sent: Tuesday, March 28, 2023 4:42 PM
To: google/fonts ***@***.***>
Cc: Danh Hong ***@***.***>; Mention ***@***.***>
Subject: [google/fonts] Siemreap font for Khmer language does not render correctly on iOS and macOS (Issue #6123)


The affected font: https://fonts.google.com/specimen/Siemreap

Describe the bug
@sovichet<https://github.com/sovichet> @danhhong<https://github.com/danhhong>

Siemreap font looks broken when viewing texts on iOS or macOS.

iOS     macOS   Windows
[https://user-images.githubusercontent.com/28331388/228184694-229728f2-2cb0-4d27-9d06-a78ed4a94793.png]<https://user-images.githubusercontent.com/28331388/228184694-229728f2-2cb0-4d27-9d06-a78ed4a94793.png>  [https://user-images.githubusercontent.com/28331388/228184974-dadc2556-b878-4c13-862a-3a4ce29b8a2b.png] <https://user-images.githubusercontent.com/28331388/228184974-dadc2556-b878-4c13-862a-3a4ce29b8a2b.png>         [https://user-images.githubusercontent.com/28331388/228185109-1580c1f0-1b75-422e-9cb8-8c0e7d2d2aef.png] <https://user-images.githubusercontent.com/28331388/228185109-1580c1f0-1b75-422e-9cb8-8c0e7d2d2aef.png>

A specific example of the issue is when there is a subscript (aka coeng) followed by an above vowel (i.e. ិ, ី, ឹ, ឺ or ើ). The subscript goes out of place and renders unreadable/incorrect/unexpected words.

មន្ត្រី should be rendered as [https://user-images.githubusercontent.com/28331388/228186749-98776702-056a-4bcb-898d-328cc3841f55.png] <https://user-images.githubusercontent.com/28331388/228186749-98776702-056a-4bcb-898d-328cc3841f55.png>
but instead it is rendered as [https://user-images.githubusercontent.com/28331388/228187375-0f39c36a-b975-423f-b9b6-081225624fd8.png] <https://user-images.githubusercontent.com/28331388/228187375-0f39c36a-b975-423f-b9b6-081225624fd8.png>

There are several more of these on page. Here is the link to it for you to check and see for yourself. :)
https://library.npic.edu.kh

To Reproduce
Go to an iOS or macOS device and load this page<https://library.npic.edu.kh> on Safari to see the incorrect/unexpected rendering of the text.

You can also see this issue when viewing the font's landing page:
[https://user-images.githubusercontent.com/28331388/228193380-ca2bf898-cca9-4f29-9219-9e881aca5764.png]<https://user-images.githubusercontent.com/28331388/228193380-ca2bf898-cca9-4f29-9219-9e881aca5764.png>

Expected behavior
Certain vowels and subscript combination have to be rendered correctly on iOS and macOS.
The same texts rendered on Android and Windows look correct and those are what is expected.

Screenshots
See in lines above.

Additional context

  *   iOS/iPadOS 16.4
     *   Safari 16.4
  *   macos Ventura 13.3
     *   Safari 16.4
  *   Windows 11?
     *   Chrome ?

**Comment by MakaraSok** [comment] 2023-03-29 01:32
Thanks a lot, @simoncozens , for the prompt response and investigation. The font does work else where except on Apple product.

@danhhong Could you shed some light on what is going on here since you've developed the font? Thank you, bong!

**Comment by danhhong** [comment] 2023-03-29 03:43
I have new version, it may be error in my github account. I will check

________________________________

**Comment by MakaraSok** [comment] 2023-03-29 03:54
@danhhong Is it related to the issue here https://github.com/google/fonts/issues/3197?

**Comment by simoncozens** [comment] 2023-03-31 07:55
Yes, looks like the latest version will work in CoreText without a morx table; so this will be fixed when the new version is onboarded. Closing in favour of #3197.

**Closed by simoncozens** 2023-03-31 07:55 UTC
Labels: -- Bad rendering, I Font Bug
