### ISSUE TITLE
Shrikhand missing

### ISSUE THREAD

**Issue by sternenseemann** [google/fonts#723] opened 2017-03-26 19:53 UTC
Shrikhand is already listed on the google fonts web page, but is missing here, is there any specific reason?

**Comment by sinspiral** [comment] 2017-03-28 21:50
Same thing with Heebo.

**Comment by davelab6** [comment] 2017-03-29 01:11
Lots of families are in this state. I hope to resolve this soon

**Comment by fitojb** [comment] 2017-03-29 09:13
Duplicate of #271

**Comment by davelab6** [comment] 2017-04-03 14:53
Closing as duplcate

**Closed by davelab6** 2017-04-03 14:53 UTC
