### ISSUE TITLE
Add Open Sauce Sans?

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2657] opened 2020-08-30 02:19 UTC
https://fontsarena.com/open-sauce-sans-by-creative-sauce/

**Comment by cssobral2013** [comment] 2020-09-03 19:37
@davelab6 - Could you include also Open Sauce One and Two on this issue? This's because Open Sauce Sans, One and Two are actually a superfamily. Check it out at: https://github.com/marcologous/Open-Sauce-Fonts

**Comment by cssobral2013** [comment] 2020-09-03 19:38
@davelab6 - This's actually a duplicate of #2421.

**Closed** 2021-05-24 22:04 UTC
