### ISSUE TITLE
Update Inter

### ISSUE THREAD

**Issue by pkj-l** [google/fonts#7661] opened 2024-05-14 00:54 UTC
**Font Project Git Repo URL:**
https://github.com/rsms/inter

**Current version:**
3.019

**New available version:**
[4.0](https://github.com/rsms/inter/releases/tag/v4.0)

**Super short description of the upgrade:**
- Six additional "Display" designs, assigned to an `opsz` variable-font axis, exposed as a second family "Inter Display" as static fonts.
- Several new OpenType features
- Humanist-style italics
- Many technical changes (UPM changed to 2048, refined metrics, many improved features, etc)

**Comment by applecuckoo** [comment] 2024-05-14 19:17
Duplicate of #3429.

**Closed** 2024-05-15 09:09 UTC
Labels: I Font Upgrade
