### ISSUE TITLE
Roboto Flex on Safari renders very thin w/ a weight of 400

### ISSUE THREAD

**Issue by marcusbuffett** [google/fonts#5466] opened 2022-10-25 01:37 UTC
**Describe the bug**
Check out these three screenshots, of the roboto flex font at weights of 400, 300, and 100. You'll notice that 100 and 400 look identical, whereas 300 is thicker than both. 401 and 399 are fine, it's only exactly at 400 where the font appears very thin.

<img width="1484" alt="CleanShot 2022-10-24 at 19 34 29@2x" src="https://user-images.githubusercontent.com/1834328/197661428-8723718d-0412-4cd0-9698-db1e35a16488.png">
<img width="1495" alt="CleanShot 2022-10-24 at 19 34 23@2x" src="https://user-images.githubusercontent.com/1834328/197661436-3cd7ead9-89d5-42fc-82d2-608c0bb20d91.png">
<img width="1515" alt="CleanShot 2022-10-24 at 19 34 14@2x" src="https://user-images.githubusercontent.com/1834328/197661438-01e77182-b5c6-4ab2-bf85-391f3a0eeaa1.png">

**To Reproduce**
Just visit the roboto flex style editor on Safari

**Expected behavior**
The text should be thicker at 400 than 300.

**Additional context**
OS X Ventura, Safari 16.1. Also happens on iOS.

Happens on my site too, which uses Roboto Flex. Safari on iOS and OS X renders the 400 weight text extremely thin.

**Comment by RosaWagner** [comment] 2022-10-26 08:20
The fact that it works fine on Monterey with Safari 15.6.1 makes me think that this is a bug brought by the update, and so it is a Mac bug, not a Google Fonts bug. We are going to investigate further to see if the font has an issue, but it could worth to report it to Apple too. 

cc @m4rc1e

**Comment by m4rc1e** [comment] 2023-10-03 14:51
Can confirm I'm getting the same issue on Safari 16.2, Ventura 13.1

<img width="973" alt="Screenshot 2023-10-03 at 15 49 59" src="https://github.com/google/fonts/assets/7525512/bf9bd05c-28cc-4b39-a13a-cf2f3e5ff154">

I'll dig deeper. I'm not able to replicate this issue in FT or Chrome so I'll get in touch with Apple if I cannot find the cause.

**Comment by chrissimpkins** [comment] 2023-11-29 21:23
@m4rc1e status?

**Comment by m4rc1e** [comment] 2023-11-29 21:29
@chrissimpkins Yep, I can replicate it

<img width="948" alt="Screenshot 2023-11-29 at 21 28 32" src="https://github.com/google/fonts/assets/7525512/4ad2faad-deb7-4a94-83dc-2523e5aa8f5a">

@dberlow any ideas what could be causing it?

**Comment by kenmcd** [comment] 2023-11-30 03:17
This appears to be fixed on macOS 14.1 Sonoma.
There was another Safari variable font issue that was reportedly fixed with v14.4.
So I installed 14.1 in a VM and was going to upgrade to 14.4 and then test.
But I tried this first and it appears to be working in 14.1.

![macOS 14 1 Sonoma](https://github.com/google/fonts/assets/844920/6a5d7620-0b8c-4ce8-bf1b-868191359a9c)

**Comment by chrissimpkins** [comment] 2023-12-14 21:03
Thanks for verifying!  Let's close this as it does not appear that we are dealing with a bug in the fonts.  This seems to be a platform/browser-specific issue.  Please feel free to reopen if we need to revisit it in the font development.

**Closed by chrissimpkins** 2023-12-14 21:03 UTC
Labels: I Font Bug
