### ISSUE TITLE
Poppins Bold stopped working in MS Powerpoint

### ISSUE THREAD

**Issue by cannedconcept** [google/fonts#8467] opened 2024-11-06 15:41 UTC
We've used the same PPT template for years, using Poppins font defined in the template theme Bold (Headings) and Light (Body). Since a few days, on multiple machines within our office Powerpoint stopped rendering the Headings as bold.

**Describe the bug**

- The text areas that have Poppins Bold set as their font render the font as Poppins Regular. 
- Also in the font selector the preview of Poppins Bold looks like Poppins regular.
- When Poppins Bold is uninstalled from the system, Powerpoint falls back to Poppins Italic, if that is uninstalled it falls back to Poppins Bold
- Also, eventho Poppins Bold is installed (c:/windows/fonts)  Powerpoint won't save the file and says it's missing the Poppins Bold font

- When a text area for which the selected font is Poppins Bold but is rendered as Poppins regular is activated and the faux bold button is pressed [B] it actually renders the text area correctly as Poppins Bold.

- In MS Word Poppins Bold (or Italic) isn't selectable as a seperate font, to 'reach' those fonts one must select Poppins and press the [B] for bold and [I] for Italic.

**To Reproduce**

It's hard to reproduce. The bug is intermittent.

**Expected behavior**

The expectation is that MS Office will render the selected font as designed without use of any faux bold/italic options.

**Screenshots**

![Image](https://github.com/user-attachments/assets/d2ba4961-4909-4def-98cf-87572b9c6f81)
![Image](https://github.com/user-attachments/assets/4668ac2d-0414-419c-a428-1bcc842dc0ce)
![Image](https://github.com/user-attachments/assets/40de5f0e-5306-4faa-baba-90ed0219b692)
![Image](https://github.com/user-attachments/assets/20ed9a98-b736-43a9-b104-dbe8427c5dbd)
![Image](https://github.com/user-attachments/assets/78300933-f8af-45b5-80d3-75a6b8b4efe5)

**Additional context**

This issue seems related to #1380

**Comment by kenmcd** [comment] 2024-11-06 17:20
Sounds like you have both the static fonts and variable fonts installed at the same time.
If that is the case, un-install the variable fonts.

Otherwise...
What version of Office?
What version of Windows?
What version of Poppins?

**Comment by cannedconcept** [comment] 2024-11-06 18:03
Thank you for your reply. I've installed the fonts as is as downloaded from Google fonts. Believe these are all static? Am I wrong?

Latest version of Poppins (uninstalled and installed from new download today to see if that fixed it. Happens on both win10 and win11 machines. Will have to check the ppt version tomorrow. Am out of office currently.

Can it be that, because the implate is configured to include the font, that the system somehow sees it as a variable variant?

**Comment by cannedconcept** [comment] 2024-11-06 20:46
Update!

Couldn't let this go. I find out that MS Office recently got updated (https://learn.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date). So I rolled back to the previous version and the first 5 attempts of opening the file (and closing the file and program) so far haven't shown the issue it seems.

Will continue to try and figure this out. I'll update later.

**Comment by vv-monsalve** [comment] 2024-11-09 00:24
Thanks, @kenmcd, for all the provided information. I use Windows 10 to test the fonts in that OS since it's still one of the more popular. So, I couldn't reproduce the issue.

@cannedconcept I'm closing this issue here. Please feel free to reopen it if you need to.

**Closed by vv-monsalve** 2024-11-09 00:24 UTC
Labels: I Font Bug
