### ISSUE TITLE
Update Cormorant

### ISSUE THREAD

**Issue by davelab6** [google/fonts#344] opened 2016-08-03 14:46 UTC
A new release of Cormorant is out, fixing a Glyphs export issue.

**Comment by alexeiva** [comment] 2017-01-09 23:28
Updated Cormorant v3.3 by @CatharsisFonts has been released on git:
https://github.com/CatharsisFonts/Cormorant/releases/tag/v3.3


> Significant overhaul and expansion of the Cyrillic inventory based on reviews by Alexei Vanyashin. See the Google Fonts forum threads on Cormorant for details.
> 
> Also replaced a few more characters in the Garamond style, especially /A and /R, whose tiny counters looked out of place there.
> 
> 
>

**Comment by CatharsisFonts** [comment] 2017-01-21 16:06
The update of Cormorant that has just been released on GF was broken. The interpolated instances of the spin-off fonts (like Cormorant Garamond) contained lots of misaligned composed characters. This problem was introduced during remastering by Google using a version of Glyphs that suffered from a bug. The problem is described in this thread:
https://groups.google.com/d/msg/googlefonts-discuss/wmHBh2k_eu0/F3iPOm0tCQAJ

**Meanwhile, the problem is fixed. I am anxious to see the broken version on GF replaced by the new version (live on https://github.com/CatharsisFonts/Cormorant) as soon as possible.**

**Comment by m4rc1e** [comment] 2017-01-23 10:25
I'll get this done asap. This was a problem with Glyphs < Version 2.4.1 (965), probably 964.

In the future @CatharsisFonts, if a release goes public and you then file a fix/update, increase the version number. In this case we are now on 3.302. This helps us if people report bugs :-). I'll do this now and file a pr back to you.

Cheers,
Marc

**Comment by m4rc1e** [comment] 2017-06-15 10:54
Closing, #579 was pushed out.

**Closed by m4rc1e** 2017-06-15 10:54 UTC
Labels: z_Cormorant

**Comment by CatharsisFonts** [comment] 2017-06-18 13:57
Did you use the current version, 3.500?
