### ISSUE TITLE
Add Carlito and Caladea

### ISSUE THREAD

**Issue by cssobral2013** [google/fonts#1441] opened 2018-02-01 19:31 UTC
https://github.com/huertatipografica/Caladea

Carlito has no github, to date

**Comment by davelab6** [comment] 2018-02-05 18:42
There are a few more families that were part of this set.

**Comment by laerm0** [comment] 2018-07-09 18:19
Were there? Arimo, Tinos, and Cousine are already on GF.

**Comment by m4rc1e** [comment] 2020-03-06 09:37
Caladea is now on Google Fonts, https://fonts.google.com/specimen/Caladea?query=caladea

Carlito coming soon.

**Comment by mfwitten** [comment] 2020-06-29 21:59
What is the reason for *Carlito*'s delay, especially given the importance of its metric-compatibility with the ubiquitous *Calibri*?

I don't intend to poke anybody; I'm just genuinely curious.

From what I can tell:

* **2013-12-05:** *Carlito* basically came into existence via ChromeOS [Issue 280557](https://code.google.com/p/chromium/issues/detail?id=280557).

* **2017-08-20:** @Ganton noted in issue #1142 that *Carlito* was no longer available from *Google Fonts*; it was decided that it had never been available *officially*, and so the issue was closed.

* **2018-02-01:** @cssobral2013 opened this issue #1441 to request the inclusion of *Carlito* into *Google Fonts*.

* **2020-03-06:** @m4rc1e gave the feared &ldquo;*SOON*&rdquo; response, which usually means &ldquo;*NOT&nbsp;SOON*&rdquo; or possibly even &ldquo;*NEVER*&rdquo;.

**Comment by m4rc1e** [comment] 2020-06-30 09:48
@vv-monsalve Did we work on Carlito at any pooint? I can't remember.

**Comment by vv-monsalve** [comment] 2020-06-30 13:47
> @vv-monsalve Did we work on Carlito at any pooint? I can't remember.

No, we only worked on Caladea last year, I didn't know about Carlito.

**Comment by mfwitten** [comment] 2020-07-09 21:26
The [*ChromiumOS* source says](https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/master/media-fonts/crosextrafonts-carlito/crosextrafonts-carlito-20130920.ebuild):

* The *Carlito* font was designed by Łukasz Dziedzic (@typoland).

* The license is **OFL 1.1**

* The distribution files are gotten from [here](http://commondatastorage.googleapis.com/chromeos-localmirror/distfiles/crosextrafonts-carlito-20130920.tar.gz), and have not changed since 2013-09-20.

* Sources for the font files don't appear to be anywhere readily accessible, as far as I can tell; and, nobody seems to care.

Perhaps @typoland would be willing to help move this issue along.

**Comment by mfwitten** [comment] 2020-07-21 16:22
The file [`CONTRIBUTING.md`](https://github.com/google/fonts/blob/master/CONTRIBUTING.md) lists some high-level criteria for including a font family in the *Google Fonts* project; here are the high-level criteria that need to be investigated for the inclusion of *Carlito*:

Criterion | Satisfied | Comment
--------- | :-------: | -------
[Google&nbsp;CLA](https://cla.developers.google.com/about) | ? | The *Carlito* font is attributed to Łukasz Dziedzic (@typoland), whose [Lato](https://fonts.google.com/specimen/Lato) font is already included in the *Google Fonts* project. Also, *Google* already includes *Carlito* [in&nbsp;Chom\*OS](https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/master/media-fonts/crosextrafonts-carlito/crosextrafonts-carlito-20130920.ebuild). This should be straightforward to resolve.
Font&nbsp;Name<br>is not a<br>registered<br>trademark | ? | According to the USPTO&rsquo;s [TESS](http://tmsearch.uspto.gov/bin/gate.exe?f=searchss&state=4803:hrvvj5.1.1) service, there is only one &ldquo;live&rdquo; registered trademark with &ldquo;carlito&rdquo; as the word mark: US Registration Number [3082671](http://tsdr.uspto.gov/#caseNumber=3082671&caseType=US_REGISTRATION_NO&searchType=statusSearch) (US Serial Number 78622082).<br><br>**However**, the registered rendition of the word &ldquo;carlito&rdquo; does *not* use the *Carlito* font that is being discussed in this GitHub issue.
Hinting | ? | *Carlito* is supposedly based on [Lato](https://fonts.google.com/specimen/Lato), and has long been included in *ChromeOS* and FLOSS OSes where [Freetype](https://www.freetype.org/) is common; this suggests it has hinting, and probably benefited from [ttfautohint](https://www.freetype.org/ttfautohint/doc/ttfautohint.html).
Supports<br>[Google Fonts<br>2016 Plus](https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/GF%20Glyph%20Sets/README.md)<br>glyph set | ? | The *Carlito* font has been [included](https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/master/media-fonts/crosextrafonts-carlito/crosextrafonts-carlito-20130920.ebuild) with *ChromeOS* since 2013, and has not been changed since that time. The *Carlito* font is supposedly based on [Lato](https://fonts.google.com/specimen/Lato), and thus very likely meets this requirement.
Active<br>development | ✗ | The font has not changed since its [debut](https://code.google.com/p/chromium/issues/detail?id=280557) in *ChromeOS*; the supposed author is unresponsive about the matter.
On Github<br>or similar | ? | The font [*binaries*](http://commondatastorage.googleapis.com/chromeos-localmirror/distfiles/crosextrafonts-carlito-20130920.tar.gz) are included in the *Chromium* project.
Corresponding<br>sources | ✗ | Apparently, there are no readily available human-readable sources that correspond to the [binaries](http://commondatastorage.googleapis.com/chromeos-localmirror/distfiles/crosextrafonts-carlito-20130920.tar.gz). Perhaps *Google* or the supposed author (*Łukasz Dziedzic*) would be willing to make those available; or, perhaps the binaries can simply be &ldquo;decompiled&rdquo; and added to the appropriate repository somewhere.
[Font Bakery](https://github.com/googlefonts/fontbakery)<br>checks | ✗ | There are no corresponding sources.
Scripted build<br>process | ✗ | There are no corresponding sources.
`README.md` | ✗ | There are no corresponding sources.
`profile.txt` | ✗ | There are no corresponding sources.
`your-name.jpg` | ✗ | There are no corresponding sources.
`DESCRIPTION`<br>`.en_us.html` | ✗ | There are no corresponding sources.
Uses [fontmake](https://github.com/googlefonts/fontmake) | ✗ | There are no corresponding sources.

All High-Level Criteria
=======================

Criterion | Satisfied | Comment
--------- | :-------: | -------
Original | ✓ | The *Carlito* font is a variation of [Lato](https://fonts.google.com/specimen/Lato).
Good&nbsp;quality | ✓ | *Google* has included the *Carlito* font [in *ChromeOS*](https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/master/media-fonts/crosextrafonts-carlito/crosextrafonts-carlito-20130920.ebuild) since 2013.
OFL&nbsp;1.1 | ✓ | That&rsquo;s what *Google* [claims](https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/master/media-fonts/crosextrafonts-carlito/crosextrafonts-carlito-20130920.ebuild).
No reserved<br>names | ✓ | No reservation appears to be made.
[Google&nbsp;CLA](https://cla.developers.google.com/about) | ? | The *Carlito* font is attributed to Łukasz Dziedzic (@typoland), whose [Lato](https://fonts.google.com/specimen/Lato) font is already included in the *Google Fonts* project. Also, *Google* already includes *Carlito* [in&nbsp;Chom\*OS](https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/master/media-fonts/crosextrafonts-carlito/crosextrafonts-carlito-20130920.ebuild). This should be straightforward to resolve.
TTF format | ✓ |
All font files<br>have the same<br>Unicode<br>character<br>set | ✓ | The *Carlito* font is supposedly based on [Lato](https://fonts.google.com/specimen/Lato), and thus very likely meets this requirement.
Font&nbsp;Name<br>is not a<br>full formal<br>noun | ✓ | &ldquo;Carlito&rdquo; is not even a name of the supposed copyright holder, *Łukasz Dziedzic*.
Font&nbsp;Name<br>is not a<br>registered<br>trademark | ? | According to the USPTO&rsquo;s [TESS](http://tmsearch.uspto.gov/bin/gate.exe?f=searchss&state=4803:hrvvj5.1.1) service, there is only one &ldquo;live&rdquo; registered trademark with &ldquo;carlito&rdquo; as the word mark: US Registration Number [3082671](http://tsdr.uspto.gov/#caseNumber=3082671&caseType=US_REGISTRATION_NO&searchType=statusSearch) (US Serial Number 78622082).<br><br>**However**, the registered rendition of the word &ldquo;carlito&rdquo; does *not* use the *Carlito* font that is being discussed in this GitHub issue.
Font&nbsp;Name<br>has no<br>initials or<br>abbreviations | ✓ |
Font&nbsp;Name<br>makes no<br>reference<br>to a<br>language<br>or writing<br>system | ✓
Font&nbsp;Name<br>is simple<br>and<br>unique| ✓ | The name &ldquo;carlito&rdquo; is [unknown to fontdata.com](https://namecheck.fontdata.com/?q=carlito).
Hinting | ? | *Carlito* is supposedly based on [Lato](https://fonts.google.com/specimen/Lato), and has long been included in *ChromeOS* and FLOSS OSes where [Freetype](https://www.freetype.org/) is common; this suggests it has hinting, and probably benefited from [ttfautohint](https://www.freetype.org/ttfautohint/doc/ttfautohint.html).
Supports<br>[Google Fonts<br>2016 Plus](https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/GF%20Glyph%20Sets/README.md)<br>glyph set | ? | The *Carlito* font has been [included](https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/master/media-fonts/crosextrafonts-carlito/crosextrafonts-carlito-20130920.ebuild) with *ChromeOS* since 2013, and has not been changed since that time. The *Carlito* font is supposedly based on [Lato](https://fonts.google.com/specimen/Lato), and thus very likely meets this requirement.
Active<br>development | ✗ | The font has not changed since its [debut](https://code.google.com/p/chromium/issues/detail?id=280557) in *ChromeOS*; the supposed author is unresponsive about the matter.
On Github<br>or similar | ? | The font [*binaries*](http://commondatastorage.googleapis.com/chromeos-localmirror/distfiles/crosextrafonts-carlito-20130920.tar.gz) are included in the *Chromium* project.
Corresponding<br>sources | ✗ | Apparently, there are no readily available human-readable sources that correspond to the [binaries](http://commondatastorage.googleapis.com/chromeos-localmirror/distfiles/crosextrafonts-carlito-20130920.tar.gz). Perhaps *Google* or the supposed author (*Łukasz Dziedzic*) would be willing to make those available; or, perhaps the binaries can simply be &ldquo;decompiled&rdquo; and added to the appropriate repository somewhere.
[Font Bakery](https://github.com/googlefonts/fontbakery)<br>checks | ✗ | There are no corresponding sources.
Scripted build<br>process | ✗ | There are no corresponding sources.
`README.md` | ✗ | There are no corresponding sources.
`profile.txt` | ✗ | There are no corresponding sources.
`your-name.jpg` | ✗ | There are no corresponding sources.
`DESCRIPTION`<br>`.en_us.html` | ✗ | There are no corresponding sources.
Uses [fontmake](https://github.com/googlefonts/fontmake) | ✗ | There are no corresponding sources.

**Comment by raffaem** [comment] 2020-12-23 08:40
Tried to contact them about Carlito, hope they will answer ... if it's not open source there will be resistance in including it in certain distributions

**Comment by twardoch** [comment] 2020-12-23 09:45
The Carlito fonts were derived from Lato in a semi-automated semi-manual fashion, with some work done in FontLab Studio 5, some work done on the binary level, using proprietary software that is not publicly available. 

The goal was to match the metrics and kerning of an existing font, so there were some tests, iterations and hackery involved. The production process was “one-off“.

Basically, there never were any “sources” from which the fonts could be re-built. I wrote some ad-hoc scripts for the process but they were never organized and never intended for release. They would not have benefitted the public anyway because they used now-defunct proprietary libraries which are no longer maintained by the authors. 

The current TTFs are the best-available sources. I mean, were I to do any work on those fonts, I’d use the TTFs, as they're the only ones that fulfil the goal of having the metrics compatibility that the fonts were created for.

**Comment by twardoch** [comment] 2020-12-23 10:00
BTW, the original author of Calibri, Luc(as) de Groot, has publicly raised objections over whether Carlito is “original”. Whether the spacing and kerning of a font is subject to copyright has been the subject of some debate, and I think the concern is valid. 

The Carlito fonts are “original” in terms of copyright law, I think, but are certainly not something that one might call “original design”.

I don't think Carlito is worthy of inclusion in Google Fonts. It’s a font in which the letters of the original design (Lato) have been algorithmically adjusted to fit the widths of another design. There was no quality design involved in the process. So the result is just an ugly Frankenstein monster — it's neither Lato nor Calibri. 

Carlito may have fit its purpose for which it was created, but users should not be encouraged to use it beyond that.

**Comment by twardoch** [comment] 2020-12-23 10:19
Ps. As you're aware, quite a few acquisitions happened in the font industry in the past years (Monotype, Bistream, FontShop, URW). These companies had some old proprietary tools that could work on the TTF level, for example Incubator Pro: https://vimeo.com/193433222

I have used some of such tools in the production process. Because these tools are a “black box”, any previous, intermediate steps in the build process of Carlito aren't really “sources”. I have also deleted many of those steps because I was not developing a “replayable” build process but a very specific set of deliverables. 

I didn’t even document the build process for myself — because of the very specific brief. As a result, the TTFs are the best “sources”, because they best reflect the main point why Carlito was created — metric compatibility with another font. 

If you want “higher-level” sources, https://github.com/latofonts/lato-source are such sources.

**Comment by Ganton** [comment] 2020-12-23 10:20
> Carlito may have fit its purpose for which it was created

It fits it. Every day. A metric-compatible font that prevents documents from breaking. A useful resource for free software people. Thanks everyone involved!

**Comment by twardoch** [comment] 2020-12-23 10:56
I agree :) Microsoft created the Office Open XML formats (.docx etc.) in response to Open Document Format, and submitted the formats to ISO. 

.docx, .xslx and .pptx became international standard ISO/IEC 29500:2008 after a tough process. The formats are documented — but Microsoft made Calibri and Cambria the default fonts of Office 2007, and so the vast majority of documents created in Microsoft Office use these fonts.

So a user may have full copyright over the document’s content, and the document can be available in an international standard (which .docx is), yet that user has no chance of faithfully reproducing that document in another system if they used the default fonts. Bringing these documents to another system results in massive reflows.

I agree that this situation goes against the spirit of ISO standardization, and I think this was a valid reason to create Carlito and Caladea. 

These fonts were not created because somebody loved the metrics and kerning of the reference fonts. They were only created to allow for the international standard ISO/IEC 29500 to _actually_ work properly. 

So I’m not denouncing these fonts — I’m just letting you know that Carlito was created in a highly non-standard process which was a bit “heroic”, using a mixed bag of tools and scripts that spanned several operating systems including, yes, emulated Mac OS 9. 😀

**Comment by raffaem** [comment] 2020-12-25 07:00
> So a user may have full copyright over the document’s content, and the document can be available in an international standard (which .docx is), yet that user has no chance of faithfully reproducing that document in another system if they used the default fonts. Bringing these documents to another system results in massive reflows.

Dear  Adam,

that is exactly the problem. When I open a co-worker document in LibreOffice, LibreOffice is able to read the file format, but it substitutes "Calibri" with the font "Noto", which I guess is an improper substitution and breaks the layout of the document, making it unreadable. I have posted a question on AskUbuntu [here](https://askubuntu.com/questions/1300334/missing-fonts-cause-libreoffice-impress-to-mess-up-the-layout-of-the-slides/1301497#1301497) and a bug report [here](https://bugs.documentfoundation.org/show_bug.cgi?id=138923) about that. 

Moreover, but that is a problem of LibreOffice I guess, LibreOffice does not even tell you that a missing font may cause problem in opening the document. It just opens the document and breaks its layout. An inexperienced user may believe that LibreOffice just doesn't work and turn back to Microsoft Office. It took me some time, and some perseverance, and a bit of luck, in finding out that the problem was a missing font. I say "a bit of luck" because by pure chance I noticed that the problem went away when I install "wine", and so I investigated more on the reasons.

Your Carlito font solve the problem and restores the correct layout of it.

By making "Calibri" the default font, and by the fact that the vast majority of desktops still use Windows and Microsoft Office, Microsoft has established a *de facto* standard on the font spacing and kerning, I think. Any other spacing and kerning rather than the de facto standard ones will break the layout.

So I would like to thank you for your font which allows us to open documents of friends and co-workers in our open-source systems 

> BTW, the original author of Calibri, Luc(as) de Groot, has publicly raised objections over whether Carlito is “original”. Whether the spacing and kerning of a font is subject to copyright has been the subject of some debate, and I think the concern is valid.
> 
> The Carlito fonts are “original” in terms of copyright law, I think, but are certainly not something that one might call “original design”.

You are clearly much more knowledgeable than me on fonts, copyright law and industry dynamics. 

But, as far as I know:
1. You need a "substantial" amount of copying to even think of breaking copyright law. For example, if I write the word "call", that doesn't break Melville's copyright (assuming it was still valid) just because his book starts with the word "call". Different would be if I copy an entire paragraph of phrase from Moby Dick. I think you are using just the font spacing and kerning, which is not enough to break copyright
2. There is a fair use doctrine in copyright law, where you can use copyrighted material in some circumstances, and I think portability is one of them
3. Most importantly, copyright law is not the only law of the land. There is also antitrust law, for example, which in the US would be the Sherman Act. For instance, the European Commission compelled Microsoft to release the specification of the communication protocol between computers, so that Sun could implement such protocol in their system and have Sun's computers talk with Microsoft's one. Since the Commission compelled them to release the protocol (and Microsoft lost every appeal and the fine was upheld by the courts), it is clear that, if this communication protocol implies that a TCP packet should be sent with a certain information and structure (for instance, a JSON dictionary in which the keys must be such and such and the values such and such), Microsoft could not claim a copyright violation over that structure and information content (otherwise the decision of the commission and court would be moot .... you have to release the specification to allow Sun to use it, but Sun could not use it anyway without breaking copyright ... that would not make sense). I think we have well a case here where not only there is no copyright violation, but we would be able to demand Microsoft to officially release the specification of the font spacing and kerning.

Moreover, as I understood, Google, and at least Canonical (Debian and Ubuntu) and Red Hat (Fedora, RHS) provide Carlito for free in their systems. So I think that copyright infringement may have well been already resolved by their lawyers in your favor.

> I don't think Carlito is worthy of inclusion in Google Fonts. It’s a font in which the letters of the original design (Lato) have been algorithmically adjusted to fit the widths of another design. There was no quality design involved in the process. So the result is just an ugly Frankenstein monster — it's neither Lato nor Calibri.
> 
> Carlito may have fit its purpose for which it was created, but users should not be encouraged to use it beyond that.

I understand that you may not deem Carlito your best creative work of all time. I absolutely respect that. Just know that it is being used for compatibility with other software.

I may also open my co-workers documents and change the font to Lato and embed it with the document, so we will change the standard :)

I respect your decision to not have this font on Google Fonts. I hope Linux distribution would provide the font without putting it in some odd non-free / drm / universal repository (which often you have to turn on explicitly in your system, are disliked by some users, and some "completely free" distribution would not provide such repositories at all).

Anyway, what is the story of Carlito? Did you have the idea on your own or Google commissioned it? Did you provide it on your site originally?

**Comment by thlinard** [comment] 2020-12-26 10:55
> So I’m not denouncing these fonts — I’m just letting you know that Carlito was created in a highly non-standard process which was a bit “heroic”, using a mixed bag of tools and scripts that spanned several operating systems including, yes, emulated Mac OS 9. 😀

Also, doesn't Lato itself have a bit "heroic" build process that is becoming more standard, but not quite?

**Comment by raffaem** [comment] 2020-12-29 13:16
Yes, as Adam said people are using the .tff as source code for the font

[See here](https://github.com/yomli/latte-fonts/issues/1#issuecomment-752041310)

**Comment by twardoch** [comment] 2020-12-29 18:31
> > So I’m not denouncing these fonts — I’m just letting you know that Carlito was created in a highly non-standard process which was a bit “heroic”, using a mixed bag of tools and scripts that spanned several operating systems including, yes, emulated Mac OS 9. 😀
> 
> Also, doesn't Lato itself have a bit "heroic" build process that is becoming more standard, but not quite?

Yes, though with Lato the problems were different. It was complicated due to buggy apps — for example no single “remove overlap” algorithm was, and still is, correct in all cases, so a special build process was required that uses different tools. 

But that process is getting cleaned up. 

With Carlito, the “design adaptation” and build process was very specific because of the metrics compatibility aspect.

**Comment by thlinard** [comment] 2020-12-29 19:37
> But that Lato process is getting cleaned up.

I think it'll be reassuring for type designers using FontLab to see a version of FontLab that is fully capable of building Lato without external tools (although using an external tool is not a bad thing, some type designers are really not comfortable with everything technical).

But I digress from the original subject. 😀

**Comment by davelab6** [comment] 2020-12-30 16:23
We will add it. We will make an "upstream" repo in the googlefonts org for
it.

**Comment by raffaem** [comment] 2021-01-03 18:54
> We will add it. We will make an "upstream" repo in the googlefonts org for it.

This would be great. It would even more legitimize this font I think.

But I thought @twardoch did not agree?

> I don't think Carlito is worthy of inclusion in Google Fonts. It’s a font in which the letters of the original design (Lato) have been algorithmically adjusted to fit the widths of another design. There was no quality design involved in the process. So the result is just an ugly Frankenstein monster — it's neither Lato nor Calibri.

Maybe we can try to struck a deal with him? :)

**Comment by fabiangreffrath** [comment] 2021-01-03 19:44
> We will add it. We will make an "upstream" repo in the googlefonts org for it.

Hiw about Caladea?

**Comment by twardoch** [comment] 2021-01-03 22:00
There is nothing for me to agree or disagree about :) The fonts are published under OFL so anyone can redistribute them. The fonts in the Chrome repo are “best known files” to my knowledge.

**Comment by raffaem** [comment] 2021-01-04 14:53
> > We will add it. We will make an "upstream" repo in the googlefonts org for it.
> 
> Hiw about Caladea?

Caladea is [already on Google Fonts](https://fonts.google.com/specimen/Caladea?query=caladea)

**Comment by davelab6** [comment] 2021-01-04 16:15
https://github.com/googlefonts/carlito is ready for a PR

**Comment by raffaem** [comment] 2021-01-04 16:17
> https://github.com/googlefonts/carlito is ready for a PR

It says 404

**Comment by davelab6** [comment] 2021-01-04 18:42
Fixed

**Comment by mfwitten** [comment] 2021-08-19 16:34
Please address @ronaldtse's Pull Request.

It's time to finish this.

**Comment by ronaldtse** [comment] 2021-08-20 02:07
Thanks @mfwitten , pinging @davelab6 @RosaWagner for attention that the googlefonts/carlito repository requires a first commit before a PR can be submitted. The PR is ready once the repository is. Appreciate your help!

**Closed** 2022-02-24 05:23 UTC
Labels: - Ready for Review, I New Font, II Submission

**Comment by davelab6** [comment] 2022-02-24 05:25
Thanks @ronaldtse I have finally merged this PR. @twardoch PTAL

**Comment by ronaldtse** [comment] 2022-02-24 05:32
Thank you very much @davelab6 ! Very glad to be able to use the font from its rightful location 😉
