### ISSUE TITLE
Wrong characters displayed in woff2 fonts on macOS Sierra

### ISSUE THREAD

**Issue by mrudolf** [google/fonts#574] opened 2017-01-13 10:00 UTC
Recently I noticed that macOS Sierra started to display wrong characters for latin-ext subset of Google Fonts even though latin-ext parameter is specified in URL. The problem occurs both in Safari and in Firefox, but not in Vivaldi. 

Working hypothesis is that it is related to woff2 format used by Safari and Firefox. Vivaldi uses TTF and it renders it correctly.

I was able to reproduce it with many pages and many fonts, e.g. Titillium, Lato etc.

Screenshot for Titillium:
![polskieradio](https://cloud.githubusercontent.com/assets/2480257/21925698/def3b686-d97e-11e6-9e60-8073e5e0dbcd.png)
[Source](http://www.polskieradio.pl/130/2793/Artykul/1713042,Rafal-Rostkowski-o-szkoleniach-i-wyzwaniach-dla-sedziow-pilkarskich)

**Comment by davelab6** [comment] 2017-01-13 17:10
Thanks for reporting this. Could you provide a isolated test page on jsbin.com that reproduces the issue for you, as I couldnt reproduce this on the source link provided on Android.

**Comment by mrudolf** [comment] 2017-01-13 18:05
This can be reproduced only on macOS Sierra, so I am not sure I got the remark about Android.

I made a sample case at [jsbin.com](http://jsbin.com/zohenezohu/edit?html,css,js,output).
This is how it looks on Safari:
![lato.png](https://cloud.githubusercontent.com/assets/2480257/21940132/1f9fb13c-d9c3-11e6-8a99-eb73643af45a.png)

I noticed that the problem goes away for larger font sizes, although the sizes depends on the font. The problem obviously does not occur if given font is installed in the system.

**Comment by davelab6** [comment] 2017-01-17 07:44
@mrudolf Hmm, I upgraded my laptop to Sierra and using Safari Version 10.0 (12602.1.50.0.10) I don't see this. 

![screen shot 2017-01-16 at 23 43 45](https://cloud.githubusercontent.com/assets/261579/22011806/b57af016-dc45-11e6-9058-15c17c99dc54.png)

**Comment by garretrieger** [comment] 2017-01-17 23:00
I was able to reproduce on Chrome (56.0.2924.51 beta) and Firefox on Linux. Additionally I narrowed down a possible cause to unicode range. On http://output.jsbin.com/zuhaviduni/1/quiet I only see the problem when unicode range is being used. Hints on/off had no effect.
![unicoderange-rendering-issue](https://cloud.githubusercontent.com/assets/10966419/22043671/8a0f4230-dcc5-11e6-814c-d476663a6ad1.png)

**Comment by khaledhosny** [comment] 2017-06-13 01:34
It might be an autohinting issue, when the font is split into ranges the autohinter might not be able to correctly calculate alignment zones for the ranges missing the base characters.

**Comment by khaledhosny** [comment] 2017-06-13 01:35
(If true, one more reason `unicode-range` should be avoided except for CJK fonts).

**Comment by davelab6** [comment] 2017-09-22 02:01
Closing as duplicate of https://github.com/google/fonts/issues/282

**Closed by davelab6** 2017-09-22 02:01 UTC
Labels: Needs Confirmation, Priority 0 - Urgent and Important

**Comment by JanuaryLimes** [comment] 2019-02-09 16:20
I have the same issue on Opera 58.0.3135.53 on Arch linux (KDE)

![opera](https://user-images.githubusercontent.com/15075229/52523180-d7434900-2c8e-11e9-8f07-f71bdd0b1db2.png)
