### ISSUE TITLE
Update RDTurcios

### ISSUE THREAD

**Issue by RDTurcios** [google/fonts#4641] opened 2022-05-11 23:05 UTC
**Font Project Git Repo URL: https://github.com/RDTurcios/Fonts-and-Stuff**

**New available version includes more glyphs and a few corrections.**

**Super short description of the upgrade: Expanded glyphset to match the _GF Latin Core_ glyph set.**

**Bugs reported in this repo which this upgrade would fix: Glyphset issue.**

[RDTurcios.zip](https://github.com/google/fonts/files/8673854/RDTurcios.zip)

**Comment by RosaWagner** [comment] 2022-05-12 08:44
duplicate of #4481

**Closed by RosaWagner** 2022-05-12 08:44 UTC
Labels: I Font Upgrade
