### ISSUE TITLE
Fira Sans is not working 

### ISSUE THREAD

**Issue by enoch85** [google/fonts#206] opened 2016-01-31 00:06 UTC
### Expected behaviour

![image](https://cloud.githubusercontent.com/assets/4511254/12699245/b9518eda-c7b4-11e5-92c9-496f899f5987.png)

### Actual behaviour

![image](https://cloud.githubusercontent.com/assets/4511254/12699275/de53d53e-c7b5-11e5-8df8-0bb40f3cd1fe.png)

There are several other users with the same error. https://code.google.com/archive/p/googlefontdirectory/issues/368

### OS
[Deepin 15](http://www.deepin.org/?language=en), Debian Linux.

### Browser
Chrome version 48.0.2564.97 (64-bit)

### How to reproduce

Remove Fira Sans from the code, and the text appears:

**With Fira Sans**
![image](https://cloud.githubusercontent.com/assets/4511254/12699294/9d62e30c-c7b6-11e5-8c49-a8e33a2dee1c.png)

**Without Fira Sans**
![image](https://cloud.githubusercontent.com/assets/4511254/12699289/6005b7b4-c7b6-11e5-9d85-70375551b593.png)

**Comment by davelab6** [comment] 2016-01-31 00:42
Thanks for reporting this! Its a duplicate of #10 so closing, but I will look into this today.

**Closed by davelab6** 2016-01-31 00:42 UTC

**Comment by enoch85** [comment] 2016-02-01 08:31
Thanks!
