### ISSUE TITLE
Roboto Serif Missing?

### ISSUE THREAD

**Issue by elnath78** [google/fonts#4315] opened 2022-02-17 12:16 UTC
Cannot find this font in the archive, probably it is under a different name? Also why name it Roboto Serif when it is a Sans Serif font?

**Comment by m4rc1e** [comment] 2022-02-17 12:24
See #4303. Hasn't been merged yet.

**Comment by elnath78** [comment] 2022-02-17 13:02
@m4rc1e why call it Serif while the font is under Sans Serif category in Google Fonts?

**Comment by RosaWagner** [comment] 2022-02-24 09:15
Closing this since we merged Roboto and corrected the categorisation issue.

@elnath78 Roboto Serif is a serif font (as you can see by design, it has serif). But your issue demonstrated that we categorised the font wrongly under sans serif, so thank you. The fix will be reflected on the webpage within 2 weeks.

**Closed by RosaWagner** 2022-02-24 09:15 UTC
Labels: -- Needs Meta/Desc/License changes, I Font Bug
