### ISSUE TITLE
Montserrat - bug with capital "A" when self hosted ?

### ISSUE THREAD

**Issue by Anticosti** [google/fonts#4584] opened 2022-05-04 03:07 UTC
**Describe the bug**
I am just wondering if this is a known bug with the capital "A" when using Monserrat ?
It looks like horizontal bar joining with the obliques has a problem... Curiously, **only on desktop**... using MacOs Catalina 10.15.7; Firefox (latest); Google Chrome (latest); Safari (latest), hmmmm... On iPhone 7, all is fine and beautiful.
![Screen Shot 2022-05-03 at 13 53 44](https://user-images.githubusercontent.com/5446224/166617946-d1f62111-81b1-4093-b253-53fe716b9db8.png)

If i swap Monserrat for Raleway all is fine:
![Screen Shot 2022-05-03 at 14 57 17](https://user-images.githubusercontent.com/5446224/166617960-f7bc5cc3-c78c-49d4-8a3d-65c31a3c0cce.png)

**To Reproduce**
Download woff and woff2 files from:
https://google-webfonts-helper.herokuapp.com/fonts/montserrat?subsets=latin

**Expected behavior**
Should be rendered as clean as calling the font from Google Fonts

**Comment by eliheuer** [comment] 2022-05-04 05:11
This is a known issue caused by the way some outlines are drawn in some variable fonts.

The source files are [here](https://github.com/JulietaUla/Montserrat), and if you download them and open the source file in a font editor you will see the overlapping forms that are causing this issue. 
<img width="1519" alt="montse" src="https://user-images.githubusercontent.com/5162664/166625715-c6a5a985-7f67-4b14-9636-73d03642a244.png">

There are various ways to remove the overlap and rebuild the font files, and you are free to do that thanks to the [OFL license](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL). 

I can try to walk you through re-exporting the font if you need any help, do you know how to use the command line?

**Comment by thlinard** [comment] 2022-05-04 19:46
Hi @eliheuer 

Look at https://github.com/majodev/google-webfonts-helper/blob/master/server/logic/conf.js

> ```
> 
> USER_AGENTS: {
> […]
>     woff: 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0',
> […]
>     woff2: 'Mozilla/5.0 (Windows NT 6.3; rv:39.0) Gecko/20100101 Firefox/39.0',
> ```

google-webfonts-helper identifies itself as Firefox 39 for a WOFF2 and Firefox 27 for a WOFF. So, the downloaded files are the versions that the Google API reserves for these older versions of Firefox.

**Comment by eliheuer** [comment] 2022-05-05 15:49
Thanks @thlinard! I'm going to close this, but if you need any more help @Anticosti, I'm happy to try to walk you through the steps to fix your problem.

**Closed by eliheuer** 2022-05-05 15:49 UTC
Labels: I Font Bug
