### ISSUE TITLE
Josefin Sans regular appears to be italic

### ISSUE THREAD

**Issue by baferret** [google/fonts#28] opened 2015-05-15 19:42 UTC
Not sure if I'm doing anything wrong, but I installed Josefin Sans Regular on Windows 7, and both GIMP and Paint show it as italic, not regular.
Nice font BTW!

**Comment by jomoos** [comment] 2015-05-21 05:51
Can confirm, appears to be italic on Inkscape in Fedora 20.

**Comment by digitalmoksha** [comment] 2015-06-24 08:01
From what I can tell, it seems that inside the ttf container, the font's type is set incorrectly - it's set to another type in the family, which is causing a duplicate (and overwrites the previous font when installed).  The actual typography inside the container is correct (based on it's preview), but it's name conflicts with others in the same family.

I'm seeing this on a Mac using Font Book.  I see it with two fonts:

* JosephineSans-Italic tries to install as Regular
* JosephineSans-SemiBoldItalic tries to installs as SemiBold

**Comment by taip** [comment] 2015-07-03 23:10
Confirmed on Mac. Regular Italic, SemiBold Italic, and Thin Italic have name conflicts; Light Italic and Bold Italic are fine.

**Comment by davelab6** [comment] 2015-07-03 23:12
Thanks for investigating :)

**Comment by Behold666** [comment] 2015-07-07 17:06
Any way to fix this? I need the regular weight for a project.

**Comment by davelab6** [comment] 2015-08-25 18:13
I have an update from the designer, which will solve this

**Comment by Behold666** [comment] 2015-08-26 01:40
I found that downloading the font from Font Squirrel gave me uncorrupted files. Does the archive that Google Fonts hosts now work?

**Comment by 4ll4n** [comment] 2015-08-27 13:18
Any updates on this? Tried Font Squirrel but got the same problem.

**Comment by insanelyus** [comment] 2015-09-05 17:48
Had the same problem. http://1001freefonts.com version works fine.

**Comment by omurphy27** [comment] 2015-10-12 22:23
Having the same problem on Mac OS. 

Switched to Font Squirrel which works fine for me.

**Comment by untangledjake** [comment] 2015-10-13 13:46
Just wanted to report that I'm also experiencing this problem on a Windows machine in latest versions of Chrome and Firefox. This is on a site that's been up for awhile but the problem seems to have begun in the last week or so.

**Comment by digitalmoksha** [comment] 2015-10-13 16:29
@davelab6 , you mentioned you had an update from the designer - is there any way that those updates can get checked in?  Would be great to just get this closed out...

**Comment by just-trey** [comment] 2015-11-02 21:12
I would like to see this corrected as well seems to be an issue on all devices and browsers

**Comment by squarecandy** [comment] 2016-04-08 20:53
+1

**Comment by squarecandy** [comment] 2016-04-08 21:11
Be sure to select X-height Matching: none and Vertical Metrics: no adjust if you're swapping out font squirrel for google fonts and want your sizes and spacing to look the same.

**Comment by admench** [comment] 2016-05-17 11:13
+! this is a current issue still!

**Comment by just-trey** [comment] 2016-05-17 12:36
Do you have you a copy installed on your computer? If so try to remove it and start over. this corrected it for me.

**Comment by galenking** [comment] 2016-07-06 13:23
@davelab6, this is still an issue for me; even when installing through SkyFonts.

Regular and Regular Italic are both named Regular—which causes a conflict. Same with SemiBold and Thin.

Any tips on how to resolve it?

**Comment by DrewRobertson** [comment] 2016-07-06 17:54
This has been an issue for over a year, how has this not been resolved yet? Especially with such a popular font.

I've tried every trick I know and I've been unable to edit it myself.

**Comment by rohapa** [comment] 2016-07-08 03:47
Why not fixed?

**Comment by dinko** [comment] 2016-07-18 07:58
I'm having the same issue, whether using SkyFonts or manual install.

**Comment by Flynn1972** [comment] 2016-09-05 13:10
Uninstall the font and delete the file AdobeFnt.lst from the computer. Only install the "regular" fonts you need and the problem is dissolved (until you need an Italic).

**Comment by digitalmoksha** [comment] 2016-09-05 18:19
@davelab6, can we get the update that you mentioned on Aug 25, 2015

> I have an update from the designer, which will solve this

Then we can get this issue closed once and for all.  If it's not fixed, can you contact the designer to get a fix?  Seems like it's in Google's interest to have their fonts in good working order. And it seems like this should be an easy fix...

**Comment by fionnayao** [comment] 2016-09-12 04:20
+1 for this problem. Have tried uninstalling the italic variant too but all of my Sketch App exports are still coming up in italics...

**Comment by LindsayElia** [comment] 2016-09-21 23:46
+1 I'm also seeing this problem when trying to use this font from the Google Fonts CDN.

**Comment by m4rc1e** [comment] 2016-09-22 08:38
Update will be rolled out soon folks,

Hang tight.

**Comment by rockstarwebdesign** [comment] 2016-10-26 16:17
Raleway font-weight:500 has the same issue. it appears italic and can't be overridden, so this must be that the font uploaded to the CDN is corrupted or mistakenly uploaded as italic.

**Comment by Varin6** [comment] 2016-11-15 17:24
Hmm, this is still an issue.. Any news on the update?

**Comment by Uranbold** [comment] 2016-11-20 14:49
Ooh I got this problem again. Can Google Fonts CDN will quickly resolve this? Only the 600 is Italic, 700 is fine but we want to display our text with 600.

**Comment by DarkDracoon** [comment] 2016-12-09 00:33
Whenever it gets fixed, let us be informed.
Thank you ^^

**Comment by davelab6** [comment] 2016-12-09 17:30
@thomasjockin worked on the roman styles earlier this year, and is now working on the italic styles.

**Comment by ChristopherNeetz** [comment] 2017-01-25 18:07
Just happened to me.  Adobe Illustrator + Skyfonts on PC

**Comment by avoision** [comment] 2017-02-07 02:05
Seeing the same issue: http://codepen.io/avoision/pen/PWBOvO

**Comment by javaheri2016** [comment] 2017-02-28 13:53
I have this problem too (Photoshop CC 2017).

**Comment by rizqinizamil** [comment] 2017-03-20 01:37
Got same issue on Mac + Sketch

**Comment by max-pub** [comment] 2017-03-24 22:17
wow, in discussion for almost two years and still no resolve?

**Comment by docet85** [comment] 2017-04-18 13:36
The issue stands in the "ttf Names" embedded in the fonts styles, where some values of the variants are the same of the Regular/NonItalic versions.

I edited them myself to use J.Sans in my text processors, here you can get the four main variants waiting for the original author or GoogleFonts to fix'em.

Cheers

[Basic_JosefinSans.zip](https://github.com/google/fonts/files/929809/Basic_JosefinSans.zip)

**Comment by Webstylerin** [comment] 2017-05-10 13:19
Still the same problem with the Google Fonts version. The first post is nearly 2 years old so I guess there will be no fix in the next days. :(

**Comment by m4rc1e** [comment] 2017-06-14 13:35
The v2.000 update, #1045 I pr'd yesterday, will solve this. The nametable was recreated

**Comment by joshua-chavanne** [comment] 2017-07-20 07:22
still getting this issue on Josefin 400 from Google Fonts.

**Comment by davelab6** [comment] 2017-07-21 14:41
https://twitter.com/xavierfoucrier/status/880807225161261059 also mentions this

**Comment by xavierfoucrier** [comment] 2017-07-21 19:26
Didn't know this issue was open. Glad to help 😉✌

**Comment by m0nzderr** [comment] 2017-07-31 20:39
+1 still experience the problem (downloading from google fonts and installing ttfs on Windows).

**Comment by davelab6** [comment] 2017-07-31 23:33
Fix will be out soon

**Comment by davelab6** [comment] 2017-08-08 00:21
Here is the pending update visually:

![josefin](https://user-images.githubusercontent.com/261579/29051057-f5e62564-7bad-11e7-820e-d0deffc3bd22.gif)

**Comment by m4rc1e** [comment] 2017-08-08 08:28
@davelab6 thanks for this!

**Comment by flashinnl** [comment] 2017-08-11 11:25
Thank you for the fix :-) 

I am curious, when will this be released to production?

**Comment by RhysMartindale** [comment] 2017-08-30 05:24
@davelab6 Hi, the font weight and letter spacing have changed with the update. Was that intentional? It looks like it's been stretched horizontally.

**Comment by m4rc1e** [comment] 2017-08-30 08:28
Yes, the weight change and redesign was intentional, #1045

**Comment by RhysMartindale** [comment] 2017-08-30 11:16
@m4rc1e Cool. Thank you :)

**Comment by davelab6** [comment] 2017-08-30 13:03
You can use negative letter-spacing to mitigate the change in spacing,
which changed to improve readability

**Comment by RhysMartindale** [comment] 2017-08-30 23:43
@davelab6 Thanks, Dave. I adjusted the weight and letter-spacing to compensate before asking. I just wanted to confirm that they were permanent adjustments before removing the old values.

**Comment by davelab6** [comment] 2017-08-31 00:16
Yes, I don't expect to roll this update back; while a few users may have change aversion, I think this upgrade to the family makes it a much better family.

**Closed** 2017-08-31 00:19 UTC
Labels: z_Josefin_Sans

**Comment by ZCweb** [comment] 2017-09-02 14:37
I like how Josefin Sans was. It was more elegant. Make sure to add
```
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
```
because it is weightier now too

**Comment by icrtf** [comment] 2023-11-23 04:07
Hi, I am experiencing this issue as well - Josefin Sans weight 200 and 300 display as Josefin Sans italic 300, and Josefin Sans 500 displays as Josefin Sans 400 when I am embedding the fonts for email signature. I have tried both the LINK and IMPORT methods and still in both cases the font renders incorrectly even within Google's Gmail.
<img width="448" alt="image" src="https://github.com/google/fonts/assets/139601616/18f49f74-f1f7-49b7-93c1-82a321263632">
