### ISSUE TITLE
Update Overpass Following Significant bugfix

### ISSUE THREAD

**Issue by michaelfaith** [google/fonts#3490] opened 2021-06-10 01:02 UTC
After a two year old, significant issue was originally identified, they've finally merged the fix in: https://github.com/RedHatOfficial/Overpass/pull/84  

This issue has been a significant one for our organization.  Just requesting that google fonts are updated with the new versions of these files.

**Comment by fitojb** [comment] 2021-06-12 16:28
Duplicate of #2665. @davelab6, please close

**Comment by michaelfaith** [comment] 2021-06-12 16:33
Hmm, interesting. That was opened before they actually merged the rebuilt files in. So i don't think updating at that point wouldn't have incorporated the fix. But nonetheless, how does timing work on this? Looks like that was posted 9 months ago and was since buried.

**Comment by davelab6** [comment] 2021-06-12 23:22
When @RosaWagner is back in 3 weeks I hope she can take a look at the q3 queue and place this a bit higher up.

**Comment by davelab6** [comment] 2021-06-12 23:23
Closing as duplicate tho, since 3.0.4 is still not pushed afaik

**Closed by davelab6** 2021-06-12 23:23 UTC

**Comment by michaelfaith** [comment] 2021-06-13 02:19
> When @RosaWagner is back in 3 weeks I hope she can take a look at the q3 queue and place this a bit higher up.

Thanks @davelab6
