### ISSUE TITLE
Rubik replacing "if" with "fi" in Safari 10

### ISSUE THREAD

**Issue by timvasil** [google/fonts#401] opened 2016-10-09 20:07 UTC
Related to #184, something is off with ligatures.  Specifically in Safari 10, instances of "if" seem to be replaced with "fi".  The letters appear in the correct order in Safari 9.1 as well as other browsers.

![ligatures](https://cloud.githubusercontent.com/assets/406652/19223313/bf5f78a8-8e21-11e6-833a-309d585ae478.png)

In this example, the CSS for the heading was set at font weight 500, however the link to the font file specified only "400,300,600,400italic".

**Comment by davelab6** [comment] 2016-10-10 16:23
@timvasil thanks for reporting this!

**Comment by davelab6** [comment] 2016-10-10 16:26
@timvasil I can't reproduce this - http://jsbin.com/zebumijuza/edit?html,output - perhaps you have an older version of the fonts installed, that you can uninstall to fix this? 

![screen shot 2016-10-10 at 09 26 26](https://cloud.githubusercontent.com/assets/261579/19243236/a2ac58ca-8ecb-11e6-87eb-94bde2461efc.png)

**Comment by driesdeclercq** [comment] 2016-10-18 13:41
I'm having the same issue ( http://www.crig.ugent.be/en/research )

- I tested with Safari 9.1 and 10.0 on OS X 10.11.6 without issues.
- The issues did appear on an iPhone 6 with latest iOS 10. (Screenshot [here](https://goo.gl/photos/rb29DWxEreVCLg9w9))

I am using the latest version of the font, as it is loaded via Google https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900

Any suggestions?

**Comment by KokkieH** [comment] 2016-10-25 14:49
We are also seeing the problem on WordPress.com sites using this font. Confirmed on Safari 10.0.1 on OS X 10.12.1

<img width="793" alt="shift_to_the_left" src="https://cloud.githubusercontent.com/assets/11873759/19691012/f1037d60-9ad2-11e6-8554-a77fd6128d81.png">

**Comment by dadra** [comment] 2016-10-26 16:44
Found this thread after seeing the issue on iPhone 6 in mobile safari with latest iOS 10 installed.  Hoping to not have to change to a different font.

**Comment by dadra** [comment] 2016-10-26 16:55
@driesdeclercq just saw your suggestion for disabling web ligatures.  Great.  That works for now.  This also works for this issue: `font-variant-ligatures: no-common-ligatures`

**Comment by timvasil** [comment] 2016-10-26 18:13
@davelab6:  here's a repro:  http://jsbin.com/kukaragumi/1/edit?html,output

The issue appears to happen only when a font weight that isn't explicitly loaded is used (in this case, 500).

**Comment by dadra** [comment] 2016-10-26 19:08
@timvasil I see the problem in mobile safari on iphone even when the font is explicitly loaded.   `<link href="https://fonts.googleapis.com/css?family=Rubik:300,300i,400,400i,500,700" rel="stylesheet">`

**Comment by ibrambe** [comment] 2016-11-16 22:58
I have the same problem with lowercase LF switching to FL.

**Comment by jigsawpieces** [comment] 2016-11-18 13:50
Can confirm adding `font-variant-ligatures: no-common-ligatures;` fixed this issue on Safari and Chrome on iOS for me.

**Comment by SiobhyB** [comment] 2016-11-21 11:26
We've had a couple more reports from WordPress.com site owners who use [Rebalance](https://rebalancedemo.wordpress.com/), a theme that uses Rubik:

* https://en.forums.wordpress.com/topic/lettering-being-mixed-up
* https://en.forums.wordpress.com/topic/if-now-spelled-wrong

I was able to reproduce in Safari on my laptop and iPad only after updating to the latest versions of macOS and iOS (I couldn't reproduce prior to updating).

**Comment by yakinbozek** [comment] 2016-12-06 16:08
The same problem happens when using some templates of the Brine family in Squarespace. Brine for instance comes with the Rubik font as default. And this bug appears not only on mobile devices as it was referenced before but even on Safari running in a MacBook pro. Hope this issue is fixed ASAP so we can keep using the Rubik font. Thanks!

**Comment by alexeiva** [comment] 2017-01-09 23:24
This has been fixed in the update. 
https://fonts.google.com/specimen/Rubik
<img width="518" alt="screen shot 2017-01-10 at 12 23 17 am" src="https://cloud.githubusercontent.com/assets/16634089/21787709/04cdc330-d6cb-11e6-89d5-f7c62eba94ff.png">

**Closed by alexeiva** 2017-01-09 23:24 UTC
Labels: z_Rubik

**Comment by elron** [comment] 2020-08-13 07:50
@alexeiva Would you mind explaining what you did to fix that in the font?

**Comment by graphicore** [comment] 2020-08-13 12:06
@elron this is done with Open Type Features, which are usually written in the [Open Type Feature File (`.fea`)](http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html) syntax. Here's an introduction, the first example is of course the fi ligature: https://ilovetypography.com/OpenType/opentype-features.html

The problem was most likely a line like this: `sub i f by f_i;`

**Comment by graphicore** [comment] 2020-08-13 12:15
@elron: Another good resource: http://opentypecookbook.com/
