### ISSUE TITLE
Upgrade Signika with GRAD axis

### ISSUE THREAD

**Issue by aaronbell** [google/fonts#3784] opened 2021-09-01 18:11 UTC
This new custom axis is included in [Signika](https://github.com/googlefonts/Signika) to adjust the font weight for white-on-black versus black-on-white text rendering. 

~~~
#SHARP based on https://github.com/googlefonts/Signika
tag: "NEGA"
display_name: "Negative"
min_value: 0.0
max_value: 1.0
default_value: 0.0
precision: -1
fallback {
  name: "Normal"
  value: 0.0
}
description: "Detailing and terminal treatment."
  "Adjusts the weight of the font to optimize text for white-on-black or black-on-white text rendering."
~~~

(Sorry this is my first time submitting such a thing, so please feel free to modify as necessary!)

**Comment by RosaWagner** [comment] 2021-09-01 18:17
GRAD axis couldn't be used for that same purpose? If yes, it is already registered, could be practical. Or is this one really different?

**Comment by aaronbell** [comment] 2021-09-01 18:19
Ha! I was actually just writing that. After looking through the axisregistry, yes, I suspect that GRAD could be used for the same purpose. I'll inquire with Anna.

**Comment by aaronbell** [comment] 2021-09-01 18:22
Actually, re-reading through the GRAD registry, that axis requires that character widths are maintained, whereas `NEGA` does not. In the case of Signika, the widths are not preserved as swapping between normal and negative variants.

**Comment by kenmcd** [comment] 2021-09-01 19:21
Another example: Darkmode VF font by Dalton Maag
They call this axis Darkmode (DRKM).
Works exactly the same as Signika NEGA.

**Comment by davelab6** [comment] 2021-09-03 14:53
Thanks for the axis registry definition data, that's helpful. I expect to get to registering a lot of custom axes in Q4, might be Q1.

**Comment by RosaWagner** [comment] 2022-09-28 10:31
> Actually, re-reading through the GRAD registry, that axis requires that character widths are maintained, whereas `NEGA` does not. In the case of Signika, the widths are not preserved as swapping between normal and negative variants.

IMO this is an error from Signika. Text composition shouldn't be subject to change when turning to Dark mode. If the weight changes regardless of the width, it is not so different from a normal weight axis. Since [GRAD](https://fonts.google.com/knowledge/glossary/grade) is thought for that purpose, it doesn't seem necessary to register a NEGA axis.

Closing this issue, please feel free to continue the discussion in the [axis registry repository](https://github.com/googlefonts/axisregistry).

**Comment by aaronbell** [comment] 2022-09-28 12:24
@Ancymonic 

I don’t think one can so easily say “this font is in error here as there is good reason one might want the widths to change. But as I am not the designer, I think it best that Anna drive the conversation if she thinks her design is correct.

If Google thinks this is an error, an issue should be filed in the repro(s) as well. And keep in mind that resolving it will force reflow as metrics change.

**Comment by RosaWagner** [comment] 2022-09-28 12:49
Please feel free to discuss this in the dedicated repository linked above.

**Comment by Ancymonic** [comment] 2022-09-29 07:18
Signika was designed long time before the "Dark mode", with print settings in mind. The negative variants were ment for text settings where text on dark backgroung is set next to text on white background, to make them look even. Not fot switching between dark and light background. That option came later. And, as @aaronbell said, adapting the typeafce to the new purpouse would cause reflow and metrics change...

**Comment by RosaWagner** [comment] 2022-09-29 08:30
Adding a GRAD axis to Signika wouldn't cause reflow on GF since it is published only with a Weight axis so far. Signika Negative can stay as it is for legacy statics.

**Comment by Ancymonic** [comment] 2022-09-29 09:23
That is true, indeed... the latest version was not yet published. That does give some space for rethinking that issue. I do recall discussing it with @kontur when we were producing the latest files. I think we were worried that it might be confusing for people if the negative/grade version of Signika would behave differently than Signika Negative.

**Comment by kontur** [comment] 2022-09-29 11:09
Yes, but I understand the static files no longer matter for GF deployments as they are instantiated from the VFs. Correct me if this assumption is wrong.

Even though intended as such the negative Signika does not fit the `GRAD` definition as relates to the "maintain width" requirement. In Signika, the negative is technically a `wght` remapping with different semantics. For the typesetting scenario @Ancymonic describes this works and guides the user to select visually even pairs of same style name or VF `wght` location. So either it lives on as `NEGA`, or the design needs to address the "maintain width" requirement.

@Ancymonic Don't bite my head off, but I was wondering this: Could the `NEGA` styles use the glyph metrics of the positive. So, since the negative glyphs are a few units "bolder", remove the difference to the positive by "chopping it off" from the sidebearings left and right equally. Since the `wght` mapped to `NEGA` is in the %, this may be acceptable, non? Et voilá, we'd have a `GRAD` compliant version and could use that axis. You could test this easily with negative tracking in InDesign for the negative version, next to the normal, adjusted to match widths. If it does feel too crammed then it's a bad idea. If it's visually acceptable this could be automated in the build process. I have only skimmed the new code by @aaronbell , but basically a pre-processing on all negative UFOs adjusting the sidebearings.

**Comment by Ancymonic** [comment] 2022-09-29 12:28
@kontur yes, if we would decide to go for the `GRAD` axis, that would probably be the best way to do it. The new lighter `GRAD` (aka Negative) versions would become a bit more spaced up, but the difference is not that big, so it should look fine. The only thing that we might not be able to make work automatically would be the ligatures, since they would need more space inside (in-between the letters). We would also need to copy the kerning from the positive grades.

**Comment by chrissimpkins** [comment] 2022-09-29 15:47
Thanks for the discussion!  We'd be happy to consider the update with the GRAD axis, or if you feel that there is something distinct about a NEGA axix relative to the current definition of GRAD, please open a new issue on our [googlefonts/axisregistry](https://github.com/googlefonts/axisregistry) repository and explain your ideas.

**Comment by davelab6** [comment] 2023-05-31 23:02
@RosaWagner had said,

> Adding a GRAD axis to Signika wouldn't cause reflow on GF since it is published only with a Weight axis so far. Signika Negative can stay as it is for legacy statics.

And @Ancymonic said in email, after investigating, 

> The difference in metrics is very small, between 0,2-0.7% or so. So I do hope reflow will not be a problem. In case it will, we can do it as Rosalie suggested in the git comment – add the GRAD axis to Signika only. Signika Negative would stay as it is for legacy statics.

This is an excellent way forwards! For me, Signika Negative could stay as it is with legacy statics, or could be output with a `wght` axis only which gets the "to Compress" benefit of VFs without any changes to existing documents that use it.

**Comment by Ancymonic** [comment] 2023-06-01 10:06
Perfect.

**Comment by davelab6** [comment] 2023-06-01 20:26
Great! So, I'm reassigning this from me to @RosaWagner, as Rosalie hasn't got many assignments at the moment :)

**Comment by RosaWagner** [comment] 2023-06-14 14:23
@Ancymonic you can let me know in this thread when the sources with the GRAD axis are available in your repo :)

**Comment by Ancymonic** [comment] 2023-06-20 11:10
@RosaWagner new sources are more or less ready. We just need to run some tests, to check if all works well. You can expect them in the repo soonish.

**Comment by Ancymonic** [comment] 2023-06-26 20:21
@RosaWagner we have the new files ready, but there seems to be a problem with creating a pull request. It states that CLA from @kmilaa is missing... I do not know who that is, and why they are listed as contributors... Can you solve that somehow on your end?

**Comment by RosaWagner** [comment] 2023-06-27 09:49
Uh yeah it's a bit of a mess ^^ 

- It looks like the PR was opened by that person and they didn't sign the Contributor License Agreement (https://cla.developers.google.com/clas) which is required when contributing to Google repository. But she probably wanted to open an issue and opened a PR instead asking for merging your fork into the Googlefonts master branch.
- It looks also like the repositories are also in conflict:
<img width="901" alt="Screenshot 2023-06-27 at 11 32 01" src="https://github.com/google/fonts/assets/12222436/056e466f-fd66-4cea-8d35-653b857a7032">

At this stage I would close that PR to remove her from contributors, so you can re-open a PR.
Let me try something to resolve the conflict before making a new PR.

**Comment by RosaWagner** [comment] 2023-06-27 10:37
I synced the 2 repo and made a new PR 👍 I gonna review them before merging

**Comment by Ancymonic** [comment] 2023-06-27 19:16
Ok, sounds good. Let me know when I can pull it back.

**Comment by RosaWagner** [comment] 2023-06-29 10:44
@kontur fixed one fail about the width of some brakets, I re-built the fonts and now we can onboard it Signika with a GRAD axis :)

**Closed** 2023-06-30 11:01 UTC
Labels: III Expand styles, I Font Upgrade, II Commissioned, III Custom axes

**Comment by Ancymonic** [comment] 2023-07-03 07:16
Thank you @RosaWagner for your assistance. Can you tell me when, more or less, it will go live?

**Comment by RosaWagner** [comment] 2023-07-03 12:10
It should be in about 1-2 weeks, but we enter the holiday period so might take longer.
