### ISSUE TITLE
What’s the reason for including U+02C9 ‘firsttonechinese’ in Latin Plus?

### ISSUE THREAD

**Issue by rbmntjs** [google/fonts#561] opened 2017-01-03 12:19 UTC
All I can surmise about this character is that it works like the combining macron (U+0304), but it’s the only Chinese tone included in the set. I’d like to know if the glyph is required in your tests or if it’s perhaps in the wrong glyph set.

**Comment by davelab6** [comment] 2017-01-05 17:53
I'm not sure - @kalapi and @alexeiva do you have any thoughts on this? :)

**Comment by rbmntjs** [comment] 2017-01-06 11:28
> On 5 Jan 2017, at 21:58, Alexei Vanyashin <notifications@github.com> wrote:
> 
> I think it's used in IPA.

That's U+02C8, primary stress marker. But why would that be the only IPA mark in the Latin Plus set anyway?

**Comment by rbmntjs** [comment] 2017-01-06 11:49
Considering the similarities between GF Latin Plus and Underware’s Latin Plus resource, my guess is this character is [just another honeypot](http://www.underware.nl/latin_plus/languages/oneipot).

**Comment by davelab6** [comment] 2017-09-22 03:04
Closing as duplicate of https://github.com/google/fonts/issues/1088 (will remove - thanks Rob'in!)

**Closed by davelab6** 2017-09-22 03:04 UTC
Labels: Priority 0 - Urgent and Important

**Comment by davelab6** [comment] 2017-09-26 12:14
Fixed
