### ISSUE TITLE
Roboto Mono regular and italic do not display as the same width

### ISSUE THREAD

**Issue by Uglyface200** [google/fonts#249] opened 2016-05-15 20:00 UTC
I am running Xubuntu 14.04 and Roboto Mono version 2.000985.

In LibreOffice Writer 5.1.2.2 and Inkscape 0.48, Roboto Mono's regular and italic styles do not display as the same width. The italic style is slightly thinner.

![screenshot - 16-05-15 - 12 51 40 pm](https://cloud.githubusercontent.com/assets/2916723/15276411/3c502a1e-1a9c-11e6-8c27-5f4a28db0c92.png)
![screenshot - 16-05-15 - 12 51 32 pm](https://cloud.githubusercontent.com/assets/2916723/15276412/3c543564-1a9c-11e6-870f-389264a5f2c0.png)

This is not the fault of the application, because the "~" character is unmodified between the styles, and (though not shown in the screenshots) it remains upright in the italic style. Additionally, even if the application were substituting its own italics, in my experience this does not affect the spacing of monospaced fonts.

Curiously, Gedit is not affected:

![screenshot - 16-05-15 - 12 52 44 pm](https://cloud.githubusercontent.com/assets/2916723/15276433/c85c673e-1a9c-11e6-993f-1ef4342dd469.png)

I went into FontForge and confirmed that the same glyphs do not have the same spacing between the styles. Note the number in the top right corner indicating the width.

![screenshot - 16-05-15 - 12 57 44 pm](https://cloud.githubusercontent.com/assets/2916723/15276440/eac8ddfc-1a9c-11e6-88de-9a97df523eab.png)

Such improper spacing is unacceptable for monospaced fonts.

**Comment by fitojb** [comment] 2016-05-16 05:12
This is a duplicate of #142 and #160. Please search for existing open reports to avoid filing duplicates. Thanks.

**Comment by davelab6** [comment] 2016-05-23 23:25
Thanks for reporting @Uglyface200 :) I'm closing as duplicate of https://github.com/google/fonts/issues/142; this has been acknowledged by the designer.

**Closed by davelab6** 2016-05-23 23:25 UTC
