### ISSUE TITLE
Miriam Libre doesn't render right on Windows

### ISSUE THREAD

**Issue by MarvinGI** [google/fonts#1300] opened 2017-11-03 15:56 UTC
When viewing a website with the Miriam Libre font on a Windows 10 computer the font doesn't render correctly. This occurs in all major browsers (Edge, FireFox, Chrome). The rendering problem arises when the font has a font size below 20px, and the problem is more pronounced when the font weight is bold. 

![screenshot from 2017-11-03 16-52-01](https://user-images.githubusercontent.com/22152296/32383129-683a6014-c0b7-11e7-91ee-ec7ab91ca67c.png)

**Comment by jodygarnett** [comment] 2017-11-14 18:06
Is this related to https://github.com/google/fonts/issues/1092

**Comment by davelab6** [comment] 2017-11-14 20:40
@jodygarnett yep! @MarvinGI thanks for reporting but closing as a duplicate of https://github.com/google/fonts/issues/1092

**Closed by davelab6** 2017-11-14 20:40 UTC

**Comment by jodygarnett** [comment] 2017-12-31 22:11
Different issue; in this case the font is not displaying at all (rather than displaying the font poorly).
