### ISSUE TITLE
Add italics and weights to Adamina

### ISSUE THREAD

**Issue by steveherrmann** [google/fonts#1030] opened 2017-06-05 10:56 UTC
Adamina is a beautiful typeface. The high x-height makes it so legible that it nearly reads itself. The only problem with it is that it is an orphan. It has no family members! Can you believe it?!! Such a beautiful typeface as this http://www.1001fonts.com/adamina-font.html and it doesn't have any siblings? No italic. No bold. It lacks the full range of diphthongs. Really an aching pity - isn't it?!! Adamina is so sweet that it deserves more. We need it to have more!!

Who can finance Alexei Vanyashin to work on this?

**Comment by davelab6** [comment] 2017-06-12 22:21
@steveherrmann https://fonts.google.com/specimen/Sura has a bold, at least :)

**Comment by davelab6** [comment] 2017-09-22 02:41
Closing as duplicate of #506

**Closed by davelab6** 2017-09-22 02:41 UTC
Labels: Priority 3 - Not Urgent or Important
