### ISSUE TITLE
the new fonts is not in the repository

### ISSUE THREAD

**Issue by chezsick** [google/fonts#371] opened 2016-09-10 06:02 UTC
just an question
why the new fonts are not in the repository ?

the new font : Yatra One, Cairo ... for example after the new interface of google fonts.

**Comment by fitojb** [comment] 2016-09-10 08:11
This issue is an exact duplicate of #271.

Before creating issues, please perform a search to see if your questions or bug reports have been posted already.

**Closed** 2016-09-27 01:40 UTC
