### ISSUE TITLE
Add Metropolis

### ISSUE THREAD

**Issue by podrivo** [google/fonts#1322] opened 2017-11-13 12:33 UTC
I believe this would be a great addition to Google Fonts: https://github.com/chrismsimpson/Metropolis

**Comment by thlinard** [comment] 2017-11-13 14:34
Duplicate of #676

**Closed** 2018-07-09 18:42 UTC

**Comment by wayward-turnip** [comment] 2021-07-20 10:23
> Duplicate of #676

It appears #1322 and #676 were closed to each other.
Issue #3414 exists to adopt the ''Clarity City'' derivative of this font.
