### ISSUE TITLE
Montserrat missing weight

### ISSUE THREAD

**Issue by ZeGregg** [google/fonts#130] opened 2015-09-30 13:45 UTC
Hi

All Montserrat font weight are not available on Google Web Font. There are more here https://github.com/google/fonts/tree/master/ofl/montserrat than https://www.google.com/fonts#UsePlace:use/Collection:Montserrat

Regards

**Comment by davelab6** [comment] 2015-09-30 14:56
Thanks for reporting this! Closing as duplicate of #2

**Closed by davelab6** 2015-09-30 14:56 UTC
