### ISSUE TITLE
This would probably be better:

### ISSUE THREAD

**Issue by Anucha7736zxc** [google/fonts#4526] opened 2022-04-18 12:27 UTC
This would probably be better:

**Font Project Git Repo URL:**
https://github.com/itfoundry/halant

**Current version:**
v1.101

**New available version:**
v2.000

**Super short description of the upgrade:**
Many improvements.

**Bugs reported in this repo which this upgrade would fix:**
#1068
#105 (partially)

_Originally posted by @thlinard in https://github.com/google/fonts/issues/4301#issuecomment-1040751186_

**Comment by RosaWagner** [comment] 2022-04-20 07:43
Duplicate of #4301

**Closed by RosaWagner** 2022-04-20 07:43 UTC
