### ISSUE TITLE
EB Garamond static files name tables are broken

### ISSUE THREAD

**Issue by davelab6** [google/fonts#3679] opened 2021-08-09 13:25 UTC
A user wrote in,

> I am writing to you because I have observed a problem with your EB Garamond font. 
>
> Italics do not apply when pressing the "italics" key in Word. 
>
> ![i-button](https://user-images.githubusercontent.com/261579/128712933-9128cf4e-4050-40ac-a05d-a2c50bc77bc9.jpg)
>
> You have to do it manually, like this
> 
> ![menu](https://user-images.githubusercontent.com/261579/128712939-2cb30588-1a7c-48ee-a891-69cfaf3aa1e9.jpg)
> 
> I am a regular user of your fonts and this is the first time that I have encountered this type of problem. Applying italics manually results in unnecessary waste of time, in addition to cutting down on writing. Can you remedy this situation? Thank you!
> 
> I got this font directly from the Google Fonts site and installed it manually on my computer.
>
> ![statics](https://user-images.githubusercontent.com/261579/128713175-94ad60f3-06c3-432e-81d4-c1ef419a1828.jpg)

This may be an instance of the STAT issues in #3267 and #2391, but since the user said they installed the statics, I guess it might be an issue with the GF API instantiation code?

Since @m4rc1e is neck deep in redoing our name table fontbakery checks, I'm assigning this to him :)

**Comment by thlinard** [comment] 2021-08-09 13:31
Hi @davelab6

Could be related to issue #2616.

Btw, nobody is assigned to this issue.

**Comment by tiroj** [comment] 2021-08-09 16:14
I am also seeing issues with bold weight mapping in Word (Mac, v16.51). Top line shows fake emboldened effect of clicking [B] button or using Command+B keyboard shortcut; lower line shows actual EB Garamond Bold font selected from font menu.
![image](https://user-images.githubusercontent.com/5614500/128738314-510e2b73-f50e-4206-bfd9-66a3b1525365.png)
Clicking the [I] button or using Command+I then produces fake italic (mechanically slanted):
![image](https://user-images.githubusercontent.com/5614500/128738594-a237469c-d055-43f3-a1a4-09a839ed7b06.png)

I checked the name tables of the EB Garamond family and also the OS/2 table fsSelection and other fields. I didn’t see any obvious errors that would produce this result, so suspect the STAT table may be to blame.

**Comment by thlinard** [comment] 2021-08-09 16:34
> I checked the name tables of the EB Garamond family and also the OS/2 table fsSelection and other fields. I didn’t see any obvious errors that would produce this result, so suspect the STAT table may be to blame.

The STAT table is certainly to blame, but `fsSelection` bit 6 (Regular) is enabled for Bold, which is obviously wrong (the issues I describe for Inter in https://github.com/google/fonts/issues/2616#issuecomment-785843977 are more or less valid for EB Garamond too).

This is also a more fundamental problem, because if #3633 corrects the STAT table for VFs and removes it for statics, the `fsSelection` and `panose.bWeight` issues persist (`panose.bWeight` is certainly less important, but `fsSelection` matters!). So the cause is to be found in the tools used  for generation.

**Comment by aaronbell** [comment] 2021-08-09 19:22
For what it's worth, I've been encountering a number of issues with Mac Word with bold and italic weights across a variety of fonts, both variable and static. In my examinations of the files, I have not been able to identify any problem in the fonts themselves. 

It isn't clear to me if the issue is with the fonts (given that some fonts work fine), or if it has something to do with Mac Word's behavior. :/

**Comment by thlinard** [comment] 2021-08-10 16:52
> For what it's worth, I've been encountering a number of issues with Mac Word with bold and italic weights across a variety of fonts, both variable and static. In my examinations of the files, I have not been able to identify any problem in the fonts themselves.
> 
> It isn't clear to me if the issue is with the fonts (given that some fonts work fine), or if it has something to do with Mac Word's behavior. :/

I tested the EB Garadond fonts with the `panose` values completely corrected, it didn't change anything. I'm inclined to think Word guilty.

**Comment by tiroj** [comment] 2021-08-10 17:00
I have encountered issues with Adobe apps not applying style linking correctly that seems to be related to OS/2 codepage or Unicode range settings. Not sure whether similar might be at play in Word?

**Comment by thlinard** [comment] 2021-08-10 18:26
> I have encountered issues with Adobe apps not applying style linking correctly that seems to be related to OS/2 codepage or Unicode range settings. Not sure whether similar might be at play in Word?

I tried a few other tricks… at the point where I am, I'm ready to try the voodoo incantations, so why not the codepages!

**Comment by RosaWagner** [comment] 2021-09-24 12:28
Naming scheme fixed with #3633, italic style linking is working for what I see. 

> It isn't clear to me if the issue is with the fonts (given that some fonts work fine), or if it has something to do with Mac Word's behavior. :/

Indeed, I have spent a lot of time this week and couldn't find what is wrong with some of the fonts. For bold italic I suspect a bug from Mac office, which are now reported there: https://github.com/MicrosoftDocs/typography-issues/issues/829 and also there: https://techcommunity.microsoft.com/t5/office-for-mac/bold-italics-not-working-on-word/m-p/2773111/highlight/true#M297

**Closed** 2021-09-24 12:28 UTC
Labels: II Small Fix
