### ISSUE TITLE
Varela Round not Found

### ISSUE THREAD

**Issue by ShintaroNippon** [google/fonts#600] opened 2017-01-24 18:48 UTC
HI there i'm loading in web font like this

```
<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
<script type="text/javascript">
WebFont.load({
  google: {
    families: ["", "Open Sans", "Varela Round", "Varela Round"]
  }
});
</script>
```

But i'm getting an error:

`webfont.js:16 GET https://fonts.googleapis.com/css?family=%7COpen+Sans%7CVarela+Round%7CVarela+Round
`

How to solve ?
Thanks in advance
Carlos Vieira

**Comment by m4rc1e** [comment] 2017-01-24 19:43
https://fonts.googleapis.com/css?family=Varela+Round

Works fine for me.

**Comment by garretrieger** [comment] 2017-01-24 21:56
The problem is the empty family name (families: ["", ...]). It's causing the loader to create a url with an invalid family parameter, family=|Open+Sans|Varela+Round|Varela+Round, which should instead be family=Open+Sans|Varela+Round|Varela+Round

**Comment by m4rc1e** [comment] 2017-01-25 09:32
Thanks @garretrieger.

@ShintaroNippon please confirm and I'll close this.

**Comment by ShintaroNippon** [comment] 2017-01-25 10:17
Hi. thanks, you are right, can't be empty.

Thanks
Carlos Vieira

**Closed** 2017-01-25 10:18 UTC
