### ISSUE TITLE
Noto Sans Symbols 2 type tester and glyphs overview are outdated on fonts.google.com

### ISSUE THREAD

**Issue by LaPingvino** [google/fonts#7238] opened 2024-01-30 23:16 UTC
#This issue also works for requesting features. 

**Describe the issue**
On the fonts.google.com website, Noto Sans Symbols 2 seems up to date for the download part, e.g. 🟙 is properly included, but it and e.g. Kaktovik numerals don't show in the glyph list or appear properly when using the type tester.

**To Reproduce**
Try looking for the nine pointed star in the glyph list (should appear after the go symbols) or try typing/copy-pasting 🟙 (U+1f7d9).

**Expected behavior**
The new characters should appear in the glyph list and work properly in the type tester.

**Additional context**
New characters since Unicode 15 and possibly 15.1

**Comment by emmamarichal** [comment] 2024-01-31 10:23
@simoncozens, is it a subset issue?

**Comment by simoncozens** [comment] 2024-01-31 10:44
In general: If a glyph is in the font we serve but it's not coming out of the web API, then yes, it's likely a subset issue.

In this case: Yes, NINE POINTED STAR is not in the latest symbols nam file, and it should be added, and the same goes for the Kaktovik Numerals block. There are probably other codepoints in Noto Sans Symbols 2 that are not being served. I'll do a test and make a PR.

**Comment by simoncozens** [comment] 2024-01-31 12:45
Actually we probably need to re-push the font once this is done; I *did* add NINE POINTED STAR two weeks ago and apparently Garret merged it.

**Comment by LaPingvino** [comment] 2024-01-31 16:49
@simoncozens so now re-push?

**Comment by LaPingvino** [comment] 2024-02-02 14:24
How long do these thinngs take normally? when should I check in again? @simoncozens

**Comment by simoncozens** [comment] 2024-02-02 16:24
Probably a couple of weeks?

**Comment by LaPingvino** [comment] 2024-03-04 22:55
https://issuetracker.google.com/issues/289759016 also references an internal bug... any updates on either?

**Comment by simoncozens** [comment] 2024-03-05 13:33
Looks OK to me:

<img width="429" alt="Screenshot 2024-03-05 at 13 33 39" src="https://github.com/google/fonts/assets/106728/d476ba6f-55b4-4c16-8834-14caecd8f8b3">

**Comment by simoncozens** [comment] 2024-03-05 13:57
Yeah, looks like some stuff on the front end has not been updated to Unicode 15.0. We've had the limits of my knowledge here, and this becomes a question for the frontend team.

**Comment by LaPingvino** [comment] 2024-03-24 21:32
no changes yet... do you know anyone of the right team to ping?

**Comment by simoncozens** [comment] 2024-03-25 07:27
@garretrieger?

**Comment by garretrieger** [comment] 2024-03-25 15:47
@nathan-williams for the FE team

**Comment by LaPingvino** [comment] 2024-04-25 14:40
One month later... is this properly checked, scheduled etc? Just checked with the same checklist and the result is the same, it shows in search but not in the type tester and glyph overview.

**Comment by LaPingvino** [comment] 2024-05-28 00:32
Just did a little testing and found the following:
- When using the search page, it fully works
- When using the specimen page, it works at first and then fails when using a link to get to the page, maybe because of a cache overwrite, see next item why
- When using the font tester, it always fails and when testing the woff2 file used on that page (added here) I see that the new characters are still missing here
Possibly rebuilding the fonts from the last version might be enough? Looks like some kind of cache invalidation issue for the proper font page...
[Archive.zip](https://github.com/google/fonts/files/15462551/Archive.zip)

@simoncozens @garretrieger @nathan-williams

**Comment by simoncozens** [comment] 2024-05-28 07:56
No point tagging me, I just provide the fonts and they're working. :-) It's a subsetting issue on the back end. It's not to do with caching but the way that subsets are delivered using CSS.

**Comment by vv-monsalve** [comment] 2024-05-28 19:23
I can reproduce the following:

Copy pasting 🟙 in the field for "Type something" + querying for `Noto Sans Symbols` works to display the `NINE POINTED STAR` symbol (for Noto Sans Symbols 2)

<img width="500" alt="Screen Shot 2024-05-28 at 14 15 42" src="https://github.com/google/fonts/assets/48698976/71fab7c6-6d75-4dbc-bd55-a32c47489f7e">

<br>
<br>

However, when copy pasting that same glyph in the TypeTester, it shows a tofu

<img width="500" alt="Screen Shot 2024-05-28 at 14 16 06" src="https://github.com/google/fonts/assets/48698976/97c79e9b-75e4-47a7-a427-47f030db9237">

<br>
<br>

@nathan-williams could you please take a look at this?

**Comment by LaPingvino** [comment] 2024-09-22 02:50
@vv-monsalve @nathan-williams ping 🙈

**Comment by vv-monsalve** [comment] 2024-09-25 00:32
@nathan-williams I reran the test (as in my previous comment), but the issue persists. Could you help us understand the root cause and what could be the solution?

**Comment by nathan-williams** [comment] 2024-09-25 21:56
@LaPingvino apologies for not noticing the earlier messages that I was tagged in. I realize it's been several months and this turned out to be a pretty simple issue.

The fix should roll out in the next week or two.

**Comment by LaPingvino** [comment] 2024-09-25 22:01
thanks a million @nathan-williams ! I already was considering to apply just to get this done 🤭

**Comment by LaPingvino** [comment] 2024-09-26 00:25
I suspect it's not your field, but any idea if that has an effect on this? https://issuetracker.google.com/issues/289759016 (updating fallback fonts on Android, ChromeOS and Google Docs)

For ChromeOS it seems to rely on a Gentoo ebuild I'm not certain about if it's  still working correctly. For Android and Google Docs I know even less relevant pointers... I hope it's just normal update delay, but my gut feeling says there might be something broken.

**Comment by LaPingvino** [comment] 2024-10-02 01:31
Verified fixed, can close @nathan-williams (but will be very pleased if you can give the issuetracker bug a look)

**Closed** 2024-10-02 08:08 UTC
Labels: I Tools / workflow / repo, I API / Website / Platform, I Request, -- Needs Eng team opinion
