### ISSUE TITLE
Teko SemiBold Colon interpolation issue

### ISSUE THREAD

**Issue by davelab6** [google/fonts#610] opened 2017-01-26 23:42 UTC
> I would like to use the font Teko for my design. But,the semicolon runs together in the semibold script. Can you change this? :)

https://twitter.com/LenaSchurr/status/821645395931648000

**Comment by m4rc1e** [comment] 2017-06-15 11:12
Confirmed.

It was the colon, not the semi colon :-)

![screen shot 2017-06-15 at 12 12 29](https://user-images.githubusercontent.com/7525512/27178878-ec314062-51c3-11e7-97d7-33b0ba965f1c.png)


http://jsbin.com/tezanukixa/edit?html,output

**Comment by laerm0** [comment] 2017-10-03 17:48
There's a [v2 in ITF's github](https://github.com/itfoundry/teko) but it still has the issues with the colon. Still, probably worth checking into to see if it's got other noteworthy improvements.

**Comment by davelab6** [comment] 2020-04-13 14:33
@Gue3bara was this fixed in your update?

**Comment by Gue3bara** [comment] 2020-04-14 11:01
> @Gue3bara was this fixed in your update?

Yes

**Comment by MasterKelli** [comment] 2020-04-20 20:37
> > @Gue3bara was this fixed in your update?
> 
> @davelab6
> Yes

Where is the fixed font available? Google Fonts and https://github.com/Gue3bara/fonts still have the bugged colon Teko Medium.

**Comment by ndo360** [comment] 2020-06-28 13:01
Hate to bump this... but where is the fixed font?

**Comment by BrandonKramerWebwhales** [comment] 2020-10-06 08:53
Any update? :)

**Comment by melissabeth** [comment] 2023-03-22 16:13
Am looking for this fix as well. Appear to affect Medium and Semibold weights.

**Comment by davelab6** [comment] 2023-06-01 22:11
Since @yanone is away for the summer and this bug is quite severe, I would like to see it fixed sooner, so assigning to @m4rc1e

**Comment by IvanTrendafilov** [comment] 2023-06-01 22:51
Well, it's only been 6 years. No rush guys.

**Comment by emmamarichal** [comment] 2023-10-04 14:08
Seems to be fixed here: https://github.com/google/fonts/pull/6560
<img width="1387" alt="Capture d’écran 2023-10-04 à 16 07 42" src="https://github.com/google/fonts/assets/64773544/f63752f9-2afb-4ee2-9704-7877e084de3c">

I close this issue then :)

**Closed by emmamarichal** 2023-10-04 14:08 UTC
Labels: I Font Bug
