### ISSUE TITLE
[Noto Sans Syriac] Include Syriac Supplement characters

### ISSUE THREAD

**Issue by ramesh-k** [google/fonts#7397] opened 2024-03-18 02:56 UTC
Include [Syriac Supplement](https://unicode.org/charts/nameslist/n_0860.html) characters to the font, which are used for writing Suriyani Malayalam, also known as Garshuni (Karshoni) and Syriac Malayalam.

Fonts for reference : 
https://bethmardutho.org/malayalamgarshuni/

**Comment by simoncozens** [comment] 2024-03-27 11:55
Duplicate of #7398.

**Closed by simoncozens** 2024-03-27 11:55 UTC
Labels: I Font Bug
