### ISSUE TITLE
Fix stacked diacritics of Vina Sans

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#6226] opened 2023-04-26 13:27 UTC
**Describe the bug**
Missing anchors

**Screenshots**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)
<img width="736" alt="Capture d’écran 2023-04-26 à 15 25 12" src="https://user-images.githubusercontent.com/12222436/234589700-048ba15f-f1c9-4189-9838-38b77b73aef3.png">
<img width="347" alt="Capture d’écran 2023-04-26 à 15 25 40" src="https://user-images.githubusercontent.com/12222436/234589703-b680a106-bcbe-41a1-b935-221975d3952f.png">

**Comment by m4rc1e** [comment] 2023-04-26 13:28
Perhaps it's the same as https://github.com/google/fonts/pull/5878#issuecomment-1523420230. Download the fonts and check with hb-view.

**Comment by emmamarichal** [comment] 2023-04-26 13:36
@emmamarichal Yep, same issue!
![vina](https://user-images.githubusercontent.com/64773544/234592683-423b155c-108d-48ef-b100-ec63013b63ae.png)

**Comment by RosaWagner** [comment] 2023-04-26 15:13
In any case there is a problem with the mark feature and the source is missing all anchors, it shouldn't have passed QA.

**Comment by garretrieger** [comment] 2023-04-26 21:42
So the root cause is the same as here: https://github.com/google/fonts/pull/5878#issuecomment-1523844317. There's nothing wrong with the font our the subsets, but we need to make a fix to the "unicode-range" we are emitting in the generated CSS for the family.

**Comment by garretrieger** [comment] 2023-04-27 19:27
This is now fixed on sandbox (you may need to clear cache to get updated CSS)

**Closed** 2023-05-24 13:19 UTC
Labels: I Font Bug
