### ISSUE TITLE
Font Lalezar is missing in github repo

### ISSUE THREAD

**Issue by udondan** [google/fonts#314] opened 2016-07-07 13:26 UTC
According to https://www.google.com/fonts/specimen/Lalezar the font Lalezar is licensed under OFL, but it can not be found in https://github.com/google/fonts/tree/master/ofl

**Comment by davelab6** [comment] 2016-07-07 13:31
Its upstream is on github, and ill add it here soon

**Comment by davelab6** [comment] 2016-07-25 16:33
Closing as duplicate of https://github.com/google/fonts/issues/271

**Closed by davelab6** 2016-07-25 16:33 UTC
