### ISSUE TITLE
Css font-display support

### ISSUE THREAD

**Issue by retyui** [google/fonts#1547] opened 2018-04-30 11:14 UTC
Why google fonts does not support this css property?
```css
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  /* ??? font-display: auto, block, swap, fallback, optional; */
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu72xKOzY.woff2) format('woff2');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}
```

**Comment by retyui** [comment] 2018-05-04 08:49
@sladen 
@shyndman 
@khaledhosny 
@cdibona 
@felipesanches 
Up!

**Comment by khaledhosny** [comment] 2018-05-04 13:47
Down!

**Comment by rsheeter** [comment] 2018-05-09 17:25
Duplicate of #358

**Closed by rsheeter** 2018-05-09 17:25 UTC
