### ISSUE TITLE
Nunito Character Sizes Inconsistent with Certain "font-size" Values

### ISSUE THREAD

**Issue by thomas-j-moffett** [google/fonts#632] opened 2017-02-03 19:13 UTC
This is happening for me on Windows 10 on latest Chrome, Firefox and IE 11 (but doesn't seem to be on Microsoft Edge).

I tested the problematic `font-size` that I was having on the Google fonts page and it produced the same results:
![image](https://cloud.githubusercontent.com/assets/22506345/22604418/5d89efce-ea00-11e6-8531-615e3879997d.png)
_(click image for larger size)_

The way I tried that was to go to this specimen page, https://fonts.google.com/specimen/Nunito, and select the element (shown in the picture above) and add a `font-size: 0.8571rem;` property to the styles (using Chrome).  This resulted in a computed `font-size: 11.994px`, which is exactly the `font-size` I was seeing on my site that was having the issue.  I noticed that the issue seems to go away _(haven't done extensive testing though)_ when the computed font size is somewhere between 12.5px and 13px and higher.

I guess this is mostly an issue with the capital letters, however, I am using all uppercase letters for some buttons and other things on the site I am working on, and it is causing very noticeable differences for letters within the same word.

I wanted to add that I tried this same thing on the Muli font (since I was looking at that as a possibility instead of Nunito), and Muli does not have this issue.

****UPDATE:** I investigated this issue a little more and I guess it might not be caused by a fractional computed `font-size` value.  I tried `font-size` of 11px and 12px directly and it seemed to be an issue for those cases and just happened that my fractional value fell in that range, but 10px seemed normal and 13px and above as well (didn't try less than 10px).

**Comment by davelab6** [comment] 2017-02-10 18:42
@tmoffett-centrify thanks for reporting this! 

It looks like ttfautohint (maintained by @lemzwerg) is doing this, and it might be possible to tweak its args to prevent this. 

Meanwhile @m4rc1e and @felipesanches are planning to re-ttfautohint the whole GF collection, so it  would be good to get to the bottom of this :)

**Comment by lemzwerg** [comment] 2017-02-11 18:51
This is a bug in FreeType's auto-hinter (and thus in ttfautohint also).  Will fix it soon.

**Comment by lemzwerg** [comment] 2017-02-13 08:37
Fix now in git.

**Comment by davelab6** [comment] 2017-02-13 15:37
Thank you!!

**Comment by tmoffett-centrify** [comment] 2017-02-15 23:35
Cool!  Glad to see this addressed so quickly!  Thanks!

**Comment by davelab6** [comment] 2017-02-16 07:27
Haha its still a ways off from a fix; @m4rc1e has to rebuild the fonts, and
make a PR to this repo, and then I have to work with the GF eng team to get
the update pushed all the way... it can take a while.

**Comment by lemzwerg** [comment] 2017-02-16 08:28
Well, with a git version of FreeType you get immediately better results if auto-hinting is activated ('slight hinting') on a GNU/Linux box...

**Comment by tmoffett-centrify** [comment] 2017-02-16 18:02
@davelab6 Well, I've seen some projects where issues go on for years not addressed at all, so I was glad to see that you guys jumped on this one quickly and have a resolution. Thanks!

**Comment by nolde** [comment] 2017-11-16 05:48
Just adding further info:

I have been noticing the same issue with Nunito on our website, with uppercase glyphs in small font sizes in Windows only.

On the image below, you can see that the `N` looks larger than the other letters:

![nunito_00](https://user-images.githubusercontent.com/12801563/32875714-88afb6ce-caed-11e7-9cf0-3aa38138600d.png)

On the next one, `DO` looks smaller than `WN`:

![nunito_01](https://user-images.githubusercontent.com/12801563/32875720-8e940888-caed-11e7-9af9-5acde227fc4a.png)

The results are consistent between different browsers in Windows. Folks using mac over here don't experience the issue.

**Comment by davelab6** [comment] 2017-11-23 01:43
This is definitely a ttfautohint issue, but according to @lemzwerg above the latest version of ttfautohint should fix this. 

@alexeiva please confirm if this is fixed when you prepare the next release of Nunito :)

**Comment by alexeiva** [comment] 2017-11-23 16:53
By default Glyphs generates CFF based webfonts. To avoid this @schriftgestalt recommends adding a `Save as TrueType` custom parameter. https://forum.glyphsapp.com/t/ttfautohint-different-from-project/3186/5

Can this be the issue?

**Comment by davelab6** [comment] 2017-11-24 00:52
No, because GF on boards TTFs not web font formats

**Comment by ben4d85** [comment] 2018-02-03 18:18
I am experiencing the exact same issue when using text-transform: uppercase; font-size: 12px; with Nunito on Windows, Chrome.

Any update on when an actual fixed Nunito font will be available for download on Google Fonts?

**Comment by rwsansom** [comment] 2018-02-08 21:32
Sadly, the designer of Nunito, Vernon Adams, passed away in 2016 - so unless Google Fonts can fix the font on his behalf, it's unlikely this issue will be resolved. 

You can read more about Vernon at SansOxygen.com/Donate. He was a talented designer.

**Comment by alexeiva** [comment] 2018-02-27 19:58
Re-generating from GlyphsApp with `ttfautohint on` did not fix issue.
Tested on Windows 10, and 7, Chrome 63

@ 11-12px the x-height jump is evident

<img width="846" alt="screen shot 2018-02-27 at 11 03 01 pm" src="https://user-images.githubusercontent.com/16634089/36749188-74eda3f4-1c13-11e8-9f06-398af15f40ac.png">

<img width="859" alt="screen shot 2018-02-27 at 11 06 55 pm" src="https://user-images.githubusercontent.com/16634089/36749189-75244422-1c13-11e8-9070-77e35f69b4a4.png">

Below is a test with no hinting. The issues is fixed at the expense of poor rendering of other sizes.
<img width="845" alt="screen shot 2018-02-27 at 11 53 31 pm" src="https://user-images.githubusercontent.com/16634089/36751425-97d91adc-1c19-11e8-9011-94fe014d3bf2.png">

I need to experiment with custom options like `increase-x-height=1` and others.

**Comment by alexeiva** [comment] 2018-02-27 20:37
Exported from Glyphs with no hinting, used ttfa options `ttfautohint -v -a nnn`. This fixed the issue:

<img width="1530" alt="screen shot 2018-02-28 at 12 32 41 am" src="https://user-images.githubusercontent.com/16634089/36753229-000eb9a4-1c1f-11e8-8f76-58321298df04.png">

I made a testing html here: http://www.cyreal.org/test4/index.html

**Comment by nolde** [comment] 2018-02-28 01:29
Accessing http://www.cyreal.org/test4/index.html in Windows 10, Chrome 63.0.3239.132 64-bit, I see not artefacts on the font. Looks good!

**Comment by alexeiva** [comment] 2018-02-28 14:42
@nolde thank you for the confirmation. 

Here is a pre-release with the fixed fonts: https://github.com/alexeiva/NunitoFont/releases/tag/v3.502

**Comment by alexeiva** [comment] 2018-02-28 14:47
@davelab6 fixed now

**Comment by ben4d85** [comment] 2018-04-25 23:32
@alexeiva Will this fix be applied to the version of Nunito on Google Fonts?

    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

**Comment by alexeiva** [comment] 2018-04-27 08:58
@m4rc1e is responsible for pushing this out

**Comment by m4rc1e** [comment] 2018-04-29 16:15
@alexeiva I'll inspect what you've done. If its fine, we'll make a pr to the official googlefonts Nunito repo.

**Comment by m4rc1e** [comment] 2018-04-29 17:11
@alexeiva @ben4d85 I haven't been able to replicate this issue on any of the browsers listed. I wonder if the users raising this issue are using custom rasterization settings?

Anyways, if people want to test this themselves, I've uploaded Alexeiva's version against the current hosted GF version. 

http://www.gf-regression.com/compare/9c0b77a8-eeef-4af1-9700-ecfcf13b9a0d

Toggle the before and after button and let me know what you think.

**Comment by nolde** [comment] 2018-04-29 23:57
Using the [gf-regression](http://www.gf-regression.com/compare/9c0b77a8-eeef-4af1-9700-ecfcf13b9a0d) link left by @m4rc1e , I can see the following results:

## FONT BEFORE:
![image](https://user-images.githubusercontent.com/12801563/39412207-10d5de94-4c5c-11e8-836c-8fc7fc360535.png)
notice `H`, `I` and `N` sizes

## FONT AFTER:
![image](https://user-images.githubusercontent.com/12801563/39412219-59c69abc-4c5c-11e8-988a-8da080583fd1.png)
all good!

__The issue seems to be fixed__, no size differences between glyphs.

And about the reproducibility, @m4rc1e , it seems to be related to very small font-sizes and Windows, not browsers. It is also affected by the system's DPI settings.

**Comment by m4rc1e** [comment] 2018-04-30 09:28
@nolde Interesting thank you very much for checking!

This release also has significant improvements over the version currently served. I'll get it pr'd into the upstream then push it here.

**Comment by davelab6** [comment] 2018-04-30 10:15
<3 it

**Comment by nolde** [comment] 2018-04-30 23:26
Thanks a lot for the [pull request](https://github.com/googlefonts/nunito/pull/12), @m4rc1e !

Quick question: how long after the merge does it become available through https://fonts.googleapis.com ?

**Comment by m4rc1e** [comment] 2018-05-01 09:06
'It depends'. The family usually goes through another round of checks and is then pushed. Could be a week, could be longer.

**Comment by ben4d85** [comment] 2018-05-02 16:05
To confirm, using the gf-regression link left by @m4rc1e , the problem of size difference between glyphs does appear for Fonts Before, but does *not* appear for Fonts After. So it seems to be fixed!

Please update this thread once the new version is available through https://fonts.googleapis.com/

Thanks for your help! Can't wait to use this!

**Comment by davelab6** [comment] 2018-06-29 13:39
Bottlenecks on me; with vacations I don't expect this to ship until August

**Comment by brandynmorelli** [comment] 2018-08-30 16:45
@davelab6 - Any hope of this getting shipped soon? :)

**Comment by rtud** [comment] 2018-09-10 16:07
@davelab6: Any update on when this will be live? Looking forward to using Nunito in an active project. Thanks!

**Comment by thomas-darling** [comment] 2018-10-08 09:51
@davelab6 This problem was reported more than a year ago, and now _another_ month has passed without any update or fix. I understand we're all busy here, but if the issue is fixed and it just need to be released, it really shouldn't take this long.

Issues like this affect our customers perception of the quality of our products, and it forces us to make less than ideal design choices, in an attempt to avoid those font sizes. That's not a sustainable situation, and if this is the level of support we can expect from Google fonts, then we're better off giving up on it.

**Comment by lynn** [comment] 2018-10-24 14:44
@davelab6 @m4rc1e  A project I'm on could really use this fixed :) Any updates?

**Comment by Zeroto** [comment] 2019-06-18 15:25
@m4rc1e Any updates on this? google fonts still seems to supply the version with the problem.

**Comment by m4rc1e** [comment] 2019-06-19 09:16
@Zeroto finalising #1549 now.

**Comment by nolde** [comment] 2019-07-29 04:37
What's the current status?

**Comment by fatcatx** [comment] 2019-07-29 22:23
Nunito Sans is the fixed version

https://fonts.google.com/specimen/Nunito+Sans

**Comment by nolde** [comment] 2019-07-30 02:12
Yep, it seems to be for the fonts dashboard.
I got the wrong one yesterday, but it must have been caching on my side. I'll recheck and report back.

**Comment by ketonik** [comment] 2020-01-05 17:26
Same issue with `Titillium Web`

https://fonts.google.com/specimen/Titillium+Web?selection.family=Titillium+Web

On macOS 10.6 to 10.14..x  it look perfect at defined pt/px font size or any zoomed size.

Windows and Linux, the digits are very much noticeably a different height

Digits 1, 4, 5, 7  
much lower than (1 pixel less)
Digits 2, 3, 6, 8, 9, 0  

0 next to 4, the 4 is tiny
Put a 1, 4, 5, 7  next to a capital letter A, H M etc, again, digits look tiny and very wrong.

On Linux change the zoom in browser and the difference in digit height is less noticeable, I don't have Windows now to look bit probably is similar observation.

**Comment by nolde** [comment] 2020-01-05 23:21
Hello!

Just confirming that, after the [merge in 21 Nov 2019](https://github.com/matrix-org/matrix-react-sdk/pull/3639), I cannot reproduce the issue using the [fonts dashboard](https://fonts.google.com/specimen/Nunito). 

Seems finally fixed.
Thanks!

**Closed** 2020-06-16 16:52 UTC
Labels: Priority 2 - Important but not Urgent, z_Nunito
