### ISSUE TITLE
All Khmer fonts are missing Latin

### ISSUE THREAD

**Issue by shahabsiavash** [google/fonts#345] opened 2016-08-03 17:02 UTC
I didn't install the fonts, but in preview all of them shows nothing for Latin texts.

[https://fonts.google.com/?sort=popularity&subset=khmer](https://fonts.google.com/?sort=popularity&subset=khmer)

![2016-08-02-14-47-25](https://cloud.githubusercontent.com/assets/20119395/17374399/a6cd91ec-59c1-11e6-847e-848d69e8525f.png)

**Comment by davelab6** [comment] 2016-08-08 15:02
Thanks! This is a duplicate of #66 so closing :)

**Closed by davelab6** 2016-08-08 15:02 UTC
