### ISSUE TITLE
Nunito Sans missing characters 

### ISSUE THREAD

**Issue by bank360design** [google/fonts#1866] opened 2019-03-05 10:19 UTC
We would like to use Nunito Sans font in Hungary, and 2 characters: Ő and Ű is missing. Would it be possible to add them to all versions of the font set, like Regulal, Black, etc.? Or we can draw them if it is possible. In this case please send us the requirements.
Thanks!
Levi

**Comment by fitojb** [comment] 2019-03-07 01:44
The font does include characters for all Hungarian vowels (technically, they are not missing). The problem is, there is an interpolation error in Regular and Bold (the other weights are fine), so instead of “Ő Ű” you see “Ó Ú”.

**Comment by fitojb** [comment] 2019-03-07 01:45
This is a duplicate of #1297.

**Comment by bank360design** [comment] 2019-03-07 07:49
Thanks for the answer!

**Comment by laerm0** [comment] 2020-02-14 19:24
[closed as duplicate of #1297]

**Closed by laerm0** 2020-02-14 19:24 UTC
