### ISSUE TITLE
Bugs with fonts name / font family name and variants, between Linux and Windows machines

### ISSUE THREAD

**Issue by joserprieto** [google/fonts#1435] opened 2018-02-01 10:19 UTC
I have a lot of problems with different fonts families, that have one names on Windows, and another, on Linux.
Affected Font Families, that I had see, are Roboto, Open Sans, Montserrat, Yanone; but is easy that there will be much more fonts will be affected.

Is it a issue?

Are any workaround for fix it?

Regards.

Screenshots (from LibreOffice):

Linux (Linux Mint 18.3):

![seleccion_999 1251](https://user-images.githubusercontent.com/1142233/35673284-651fe55e-0741-11e8-97c0-b2124c50b341.png)
![seleccion_999 1252](https://user-images.githubusercontent.com/1142233/35673285-65466602-0741-11e8-9196-d27afe2c0dd1.png)
![seleccion_999 1253](https://user-images.githubusercontent.com/1142233/35673287-656b1736-0741-11e8-8d67-bd90c6910673.png)

Windows(Windows 10 Pro):

![2018-02-01 11_13_42-document odt - libreoffice writer](https://user-images.githubusercontent.com/1142233/35673301-741ee0d2-0741-11e8-9cb9-f212050cad65.png)
![2018-02-01 11_14_35-document odt - libreoffice writer](https://user-images.githubusercontent.com/1142233/35673303-744d2ffa-0741-11e8-9633-dd5cb731466b.png)
![2018-02-01 11_14_56-document odt - libreoffice writer](https://user-images.githubusercontent.com/1142233/35673304-7473352e-0741-11e8-9a24-790ddf98b740.png)
![2018-02-01 11_15_38-document odt - libreoffice writer](https://user-images.githubusercontent.com/1142233/35673305-749930bc-0741-11e8-9c3b-f3488cf2f62e.png)

**Comment by thlinard** [comment] 2018-02-01 10:30
LibreOffice bugs.

- [Bug 72944 - Enhance handling of font families (weight, style, stretches) on Windows](https://bugs.documentfoundation.org/show_bug.cgi?id=72944)
- [Bug 98596 - Correct handling of font families (weight, style, stretches) on Linux](https://bugs.documentfoundation.org/show_bug.cgi?id=98596)

Meta-bug:

- [Bug 35538 - Handling of fonts with more that 4 styles (R/B/I/BI) is suboptimal](https://bugs.documentfoundation.org/show_bug.cgi?id=35538)

**Comment by joserprieto** [comment] 2018-02-01 11:46
Not is a LibreOffice bug.

The same behaviour is in InkScape, The Gimp, and other programs.

I can take screenshots, if you need.

**Comment by thlinard** [comment] 2018-02-01 12:12
I believe Inkscape ported FreeType on Windows to do styles handling. Still, there are many bugs:
https://bugs.launchpad.net/inkscape/+bug/165521 (as you can see, far beyond Google Fonts).

To understand this poor behavior, you could read this tutorial witch will give you background information:
https://glyphsapp.com/tutorials/naming

**Comment by joserprieto** [comment] 2018-02-01 12:23
Test on InkScape; more or less, same behaviour on Windows / Linux:

Roboto:
Windows:
![roboto family](https://user-images.githubusercontent.com/1142233/35678134-767fa44a-0752-11e8-85a9-c31a581fe4e1.png)
Linux:
![roboto family](https://user-images.githubusercontent.com/1142233/35678145-857a1d86-0752-11e8-950e-89f1e2145c2c.png)

Montserrat:
Windows:
![montserrat family](https://user-images.githubusercontent.com/1142233/35678132-762db810-0752-11e8-9fa6-60d507b99f44.png)
Linux:
![montserrat family](https://user-images.githubusercontent.com/1142233/35678142-8529b0c6-0752-11e8-8a29-df33d8ee7ef6.png)

Open Sans:
Windows:
![open sans family](https://user-images.githubusercontent.com/1142233/35678133-76584008-0752-11e8-8b9e-5222a04a7831.png)
Linux:
![open sans family](https://user-images.githubusercontent.com/1142233/35678144-85505136-0752-11e8-9297-1c04387c4b90.png)

Yanone Kaffeesatz:
Windows:
![yanone kaffeesatz family](https://user-images.githubusercontent.com/1142233/35678135-76a4925a-0752-11e8-8c28-f1190c746a99.png)
Linux:
![yanone family](https://user-images.githubusercontent.com/1142233/35678146-85a34f1c-0752-11e8-978c-3856da15c161.png)

**Comment by joserprieto** [comment] 2018-02-01 12:25
So, exists any workaround to fix this?

I make a templates on LibreOffice, and it is embarrasing doing one for Linux, and one for Windows...

**Comment by thlinard** [comment] 2018-02-01 12:52
For the time being, if you want cross-platform LibreOffice templates, restrain yourself to R-B-I-BI styles.

In the meantime, you can comment on relevant LibreOffice bugs to make clear that this issue requires attention and resource allocation.

**Comment by thlinard** [comment] 2018-02-01 12:58
And for Inkscape and GIMP bugs, there are duplicate of #633.

**Comment by joserprieto** [comment] 2018-02-02 13:25
OMG, restrict to R-B-I-BI... 

:/

Again with two templates..

:(

**Comment by davelab6** [comment] 2018-02-05 18:44
I'm closing this issue because it is a problem with libre software being basic, not with the fonts :)

**Closed by davelab6** 2018-02-05 18:44 UTC

**Comment by joserprieto** [comment] 2018-02-06 10:09
I think that is a problem with OS specs.. And software that is not well implemented :/
