### ISSUE TITLE
NO variable version for IBM Plex Sans, despite it existing upstream?

### ISSUE THREAD

**Issue by cssobral2013** [google/fonts#3954] opened 2021-10-21 21:31 UTC

**Comment by applecuckoo** [comment] 2022-09-24 23:18
This seems to be a duplicate of #2407.

**Comment by yanone** [comment] 2022-11-09 09:16
Closing this because duplicate of https://github.com/google/fonts/issues/2407 indeed.

**Closed by yanone** 2022-11-09 09:16 UTC
