### ISSUE TITLE
Roboto Normal Style error with sequence "P:"

### ISSUE THREAD

**Issue by Aabcomp** [google/fonts#109] opened 2015-08-30 01:24 UTC
Roboto font (TTF Windows Version test) error with sequence "P:", (Upper case "P" and Colon punctuation mark)

The top dot in colon is superposed to "P", only the inferior dot is visible. Se annotated screen capture attached... 

![roboto-font_error](https://cloud.githubusercontent.com/assets/14035633/9565286/b581aa08-4e8b-11e5-9dbe-7f0249fdfbfe.png)

**Comment by davelab6** [comment] 2015-08-30 01:54
I think you have an old copy installed; please uninstall the fonts and refresh the page. 

Here is a Win 8 Firefox:

<img width="1680" alt="screen shot 2015-08-29 at 21 52 42" src="https://cloud.githubusercontent.com/assets/261579/9565360/6b69f6ac-4e98-11e5-9d12-5182345aa464.png">

**Comment by davelab6** [comment] 2016-06-30 20:48
@Aabcomp I'm closing this as I can't reproduce it; feel free to re-open if you still have issues.

**Closed by davelab6** 2016-06-30 20:48 UTC
Labels: question

**Comment by oNdsen** [comment] 2017-07-09 21:08
I have the same Issue with Embedded Font.
Roboto, weight 400:
[https://fonts.googleapis.com/css?family=Roboto:300,400](https://fonts.googleapis.com/css?family=Roboto:300,400)

Text: IP:Port
![https://picload.org/image/rpcrgawr/2017-07-0923_04_48.png](https://picload.org/image/rpcrgawr/2017-07-0923_04_48.png)

No Point Overlay with Font weight 300.

**Comment by fitojb** [comment] 2017-07-10 08:36
@oNdsen Same as above: please make sure you don’t have any old version of Roboto locally installed.

**Comment by oNdsen** [comment] 2017-07-12 09:54
@fitojb im using the Release from here:
[https://fonts.google.com/specimen/Roboto?selection.family=Roboto](https://fonts.google.com/specimen/Roboto?selection.family=Roboto)

Still the same Problem on weight 400

**Comment by davelab6** [comment] 2017-07-12 13:35
@oNdsen do you have an old version installed locally (perhaps via typekit)?
