### ISSUE TITLE
Subsetting doesn't work

### ISSUE THREAD

**Issue by LoranRendel** [google/fonts#1399] opened 2017-12-19 09:27 UTC
https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900&subset=cyrillic
When open this url I got all subsettings. A a part of page contents is below.

```
/* greek */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 300;
  src: local('Roboto Light'), local('Roboto-Light'), url(https://fonts.gstatic.com/s/roboto/v18/I3S1wsgSg9YCurV6PUkTORJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
  unicode-range: U+0370-03FF;
}
/* vietnamese */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 300;
  src: local('Roboto Light'), local('Roboto-Light'), url(https://fonts.gstatic.com/s/roboto/v18/NYDWBdD4gIq26G5XYbHsFBJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
  unicode-range: U+0102-0103, U+0110-0111, U+1EA0-1EF9, U+20AB;
}
```

**Comment by davelab6** [comment] 2018-01-04 20:49
Because your browser supports www.caniuse.com/#search=unicode%20range

Duplicate of https://github.com/google/fonts/issues/68#issuecomment-118155706

**Closed by davelab6** 2018-01-04 20:49 UTC
