### ISSUE TITLE
Cairo Play glyphmapping issue

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#5913] opened 2023-02-20 16:15 UTC
Weirdest glyphmapping in Cairo Play: for example `A` -> `AEacute`, `é` -> `ebreve`. Happens in VF from upstream repo + VF in GF zip.
Although when typing in GF specimen page, the font behaves correctly.
The issue cannot be reproduced with Cairo although the fonts are built from the same source. 

cc @yanone @m4rc1e

**Comment by m4rc1e** [comment] 2023-02-21 13:05
I don't understand the issue. Are you saying that  the "A" glyph are mapped to "Aacute" unicode? If I check the font, that isn't the case.

Are you checking the fonts in applications which support COLR tables?

**Comment by RosaWagner** [comment] 2023-02-21 13:18
Yeah by glyphmapping I meant, I type a letter and another one is displayed. To be more precise, it sometimes displays the next glyph ID of the one typed. This is the basic alphabet:

<img width="787" alt="Capture d’écran 2023-02-21 à 14 15 11" src="https://user-images.githubusercontent.com/12222436/220354971-ed9fec1d-ede8-4ae0-aea5-a97a0a9a59f6.png">


I checked it in different apps in Mac; textEdit, Indesign, Word. I know some don't support the COLR table, but they are supposed to display the proper glyphs with or without color. Nabla doesn't have this issue, that is why I think something is happening with Cairo Play.

**Comment by yanone** [comment] 2023-02-21 14:08
I made these on my old computer which is at home. I can check soon when I'm back. Though I didn't check for macOS compatibility explicitly, I have a feeling I should have seen that while working on it, which would suggest a macOS issue. I'll let you know.

**Comment by yanone** [comment] 2023-02-21 14:16
FLTR: Brave on latest macOS, Safari on latest macOS, latest Edge on Windows. Only Safari shows the anomaly (and all other native macOS apps).
<img width="2815" alt="Bildschirm­foto 2023-02-21 um 15 14 34" src="https://user-images.githubusercontent.com/175386/220369533-cc919b6e-e0e2-4eed-a762-a18dec6b1db6.png">

**Comment by yanone** [comment] 2023-02-21 14:32
> Although when typing in GF specimen page, the font behaves correctly.

Not in Safari. This is a legitimate bus crash: 
<img width="1479" alt="Bildschirm­foto 2023-02-21 um 15 32 07" src="https://user-images.githubusercontent.com/175386/220373386-f8ed0b6f-e80a-4935-bd36-9e07035e626d.png">

**Comment by yanone** [comment] 2023-02-21 14:35
Although the behaviour above is actually different from Rosalie's report where COLR glyphs were showing the wrong GID. In the Safari screenshot, the glyphs are actually identical but rendered wrong.

**Comment by RosaWagner** [comment] 2023-02-21 14:59
I am no expert in color font, but I wouldn't be surprised if one reads the COLR table and the other one the SVG table. The SVG table was added using maximum_color script; can it be that there is something wrong with that particular process creating inconsistencies?

**Comment by anthrotype** [comment] 2023-02-21 15:25
it might be the SVG table (generated by nanoemoji's maximum_color) that is at fault. Try to see if by removing 'SVG ' table, the font works.
Cairo Play looks like a COLR version 0 (only flat colors) font, so in theory I would _not_ expect it to also have an SVG table, because COLRv0 should work mostly everywhere as SVG also works, and is more compact, variable-friendly, just better for flat-only colors.

I thought we added a fontbakery check that only COLRv1 fonts should go through maximum_color, no?

**Comment by anthrotype** [comment] 2023-02-21 15:28
Ouch, yes. it's the SVG table...

BTW, to quickly strip a table using `ttx` do:

```sh
$ ttx -x 'SVG ' -o CairoPlay-Regular_nosvg.ttx CairoPlay-Regular.ttf
$ ttx -o CairoPlay-Regular_nosvg.ttf CairoPlay-Regular_nosvg.ttx
```

**Comment by yanone** [comment] 2023-02-21 15:31
> I thought we added a fontbakery check that only COLRv1 fonts should go through maximum_color, no?

Yes, but those checks and the Arabic color fonts were produced around the same time, so it's not certain that the checks were already in place for Cairo. Also, some of the fonts were messed with by Rod in my absence during last summer and uploaded bypassing our review process. Not impossible that Cairo was one of them.

@RosaWagner @m4rc1e I'll attempt an update asap as I'm already familiar with the project.

**Comment by anthrotype** [comment] 2023-02-21 15:31
To fix this issue, I'd recommend that you rebuild the fonts from source and this time not use maximum_color at all, because we do not want COLRv0 fonts like these to also have an SVG table, even more so when they are variable (for SVG is not)

**Comment by m4rc1e** [comment] 2023-02-21 15:41
gftools builder should only add svg tables to fonts with colr v1 tables, https://github.com/googlefonts/gftools/blob/main/Lib/gftools/fix.py#L694-L709

You may need to update Cairo Play's dependencies if this isn't happening.

**Comment by anthrotype** [comment] 2023-02-21 15:41
I just cloned the Cairo repository and it looks like the variable font in this directory of pre-built fonts does have an SVG table, which Yanone committed so this time it doesn't look like the fonts were post-processed by us:
https://github.com/Gue3bara/Cairo/tree/master/fonts/CairoPlay/variable

by the way, I couldn't find a CairoPlay.glyphs source file in that repo... How do I build it?

**Comment by m4rc1e** [comment] 2023-02-21 15:43
> by the way, I couldn't find a CairoPlay.glyphs source file in that repo... How do I build it?

If I remember correctly you run this script https://github.com/Gue3bara/Cairo/blob/master/scripts/makeplay.py

**Comment by anthrotype** [comment] 2023-02-21 15:44
ah, thanks. I suggest you put that in the Readme :)

**Comment by yanone** [comment] 2023-02-21 15:45
Will do. This whole repo is a mess anyway

**Comment by RosaWagner** [comment] 2023-02-21 15:51
But Indesign wouldn't display the color without the SVG table, no?

**Comment by yanone** [comment] 2023-02-21 15:52
I'll check and let you know. I'm on it right now.

**Comment by anthrotype** [comment] 2023-02-21 15:54
I think it will, COLRv0 is about as old as SVG table, I would expect that by now it would work at least everywhere SVG does, but I may be badly wrong..

**Comment by anthrotype** [comment] 2023-02-21 16:01
ah ok thank you. I am always scared when running a makefile I didn't write myself LOL

I just rebuilt CairoPlay-VF.ttf from latest sources using latest fontmake and nanoemoji, and at least now it does have a working SVG table and the glyph order is not messed up as in the original bug report above. Maybe the current one was built using an older nanoemoji, I'm not sure. 

This is the font I built, in case you want to check/compare with yours.
I run the makeplay.py script to generate CairoPlay.glyphs then used fontmake -g CairoPlay.glyphs -o variable and finally run maximum_color on it.

[CairoPlay-VF.ttf.zip](https://github.com/google/fonts/files/10795281/CairoPlay-VF.ttf.zip)

I still hope we don't need to make SVG tables for this, because SVG is inherently not variable and this font is.

**Comment by yanone** [comment] 2023-02-21 16:38
Cosimo's font with SVG table shows the same behaviour in Indesign as the live fonts show in native macOS: No VF support, as Cosimo already said. Therefore I must conclude that we correctly decided for COLRv0 VFs fonts not to have an SVG table and ignore that Adobe apps won't support COLRv0 for the time being, and both `gftools` as well as `fontbakery` follow that conduct today.

This is from Indesign with Cosimo's build:
<img width="253" alt="Bildschirm­foto 2023-02-21 um 17 15 07" src="https://user-images.githubusercontent.com/175386/220400192-d6ab6e6f-36af-4dfd-abf8-5ce6fad6908e.png">

And this is from macOS natively:
<img width="1068" alt="Bildschirm­foto 2023-02-21 um 17 21 20" src="https://user-images.githubusercontent.com/175386/220401397-e0818886-c9ae-41d0-8ce9-1378ec912b2a.png">

What really bothers me here is that it shows left-slanted as default, and this is in line with the two Safari screenshots I posted above of the live font. There is no extrema on the `slnt` axis in STAT, nor are any slanted `fvar` instances defined, so I really don't know where it gets that from. Anyone ever seen this?

And this is also in line with the [specimen page](https://fonts.google.com/specimen/Cairo+Play?query=cairo) for Cairo Play on Safari (identical for [Cairo](https://fonts.google.com/specimen/Cairo) btw), while [Type Tester](https://fonts.google.com/specimen/Cairo+Play/tester?query=cairo) page shows upright (`slnt=0` explicitly in CSS), but IT DOESN'T HAVE THE VARIABLE SLIDERS IN SAFARI AAAAH _pulls hair out_

**Comment by anthrotype** [comment] 2023-02-21 16:40
can you please try to strip the SVG table from CairoPlay and then load in Indesign?

**Comment by anthrotype** [comment] 2023-02-21 16:41
Either strip SVG from the font I sent, I simply rebuild from source and not run maximum_color (perhaps better this way), and see if COLRv0 only works in Indesign

**Comment by yanone** [comment] 2023-02-21 16:42
I did already but didn't mention it: It shows variable okay, but only b/w normal outlines, no color

**Comment by yanone** [comment] 2023-02-21 16:44
In conclusion: COLRv0 works in Indesign for statics. In theory we could allow that in `gftools` and `fontbakery`. The current conduct in both tools doesn't differentiate between VFs and statics.

**Comment by yanone** [comment] 2023-02-21 16:51
Two of Khaled's Arabic fonts are static COLRv0 without an SVG table. That's actually sad. We should rethink that.

**Comment by anthrotype** [comment] 2023-02-21 16:58
> It shows variable okay, but only b/w normal outlines, no color

so a font with COLRv0 (without any SVG table) does not work in indesign, shows fallback glyf... I should have known that.

> SVG works in Indesign for statics

yeah, that would be expected. Ideally one would make static instances from the COLR VF and _then_ run `maximum_color` on each one, to get properly interpolated outlines at each instance location, even for the SVG table.
If you simply run maximum_color on the variable COLR font, the SVG table you get is going to reflect only the default outlines (but the font as a whole is still variable, except for the SVG glyphs, e.g. you may get weird glyph metrics not matching the respective outlines)

**Comment by yanone** [comment] 2023-02-21 17:23
Actually, the wrong glyph order might have been my mistake and not related to the SVG table at all: One of the requirements for a COLRv0 font is that it has an empty glyph (e.g. `space`) on GID 1 because of a Microsoft rendering bug. I always used to do that in `ttx` manually for Cairo and might have done it wrong (at least wrong for macOS to read it correctly, while others didn't have a problem with it). I'll figure out a Python script for that and then plead to have it added to `gftools builder` as a post-processor for COLRv0. I've done that manually too many times now.

**Comment by anthrotype** [comment] 2023-02-21 17:25
i think that's better done at the source level

**Comment by yanone** [comment] 2023-02-21 17:44
I wish I could report that that worked, but it didn't. At least the `glyphOrder` custom parameter is ignored. That's a `glyphsLib` I think. The UFOs show no reaction to changing the `glyphOrder` custom parameter. I'll look into it on Thursday. Tomorrow I'm off.

**Comment by anthrotype** [comment] 2023-02-21 17:46
well, that's totally unexpected and if confirmed, a bug.
The ufo lib.plist key is called `public.glyphOrder`, but you already know that. Enjoy your day off!

**Comment by yanone** [comment] 2023-02-23 09:10
Lib `public.glyphOrder` key is ordered as I defined in Glyphs, but ignored. The order in the font is identical to `glyphs/contents.plist`. Why are there two glyph order places in UFO?

I feel like `glyphsLib` should influence `contents.plist` instead. Otherwise, respecting `public.glyphOrder` is probably `ufo2ft`'s responsibility.

**Comment by RosaWagner** [comment] 2023-02-23 09:33
@yanone I tested the glyph order parameter on my machine with only .notdef and space in it, generated with fontmake directly and it worked. I am using the main branch of glyphsLib.

**Comment by yanone** [comment] 2023-02-23 09:35
But really, it's not the responsibility of a designer or any maintainer of a font source to know how to reorder glyphs only to react to a Windows rendering bug that might disappear in the future. This stuff needs to work automatically. Currently writing a gftools issue.

**Comment by anthrotype** [comment] 2023-02-23 10:14
setting glyphOrder custom parameter in glyphsLib should produce a public.glyphOrder lib key in the UFO masters, and the latter should be used by ufo2ft to order the glyphs in the font. If that is not working (which would be strange since we do have tests covering this core functionality) can you please file an issue?

> it's not the responsibility of a designer

Perhaps, but at least there is a way to accomplish this with the current tools, without recurring to hacking the font post-build.

If you'd like this to be done automatically, maybe glyphsLib can make up a glyphOrder (if one wasn't provided already) whenever the UFO that it's generating contains any COLRv0 color glyphs (which Glyphs.app confusingly calls "color palette layers"). Feel free to file a feature request for that in glyphsLib (or even a PR), thanks!

**Comment by yanone** [comment] 2023-02-23 10:16
Turns out Marc had already implemented a fixer, and is investigating why it isn't being applied: https://github.com/googlefonts/gftools/issues/658

**Closed** 2023-03-08 10:39 UTC
Labels: III Improve rendering / layout, I Font Bug
