### ISSUE TITLE
Single-letter Kashida

### ISSUE THREAD

**Issue by avidseeker** [google/fonts#8339] opened 2024-10-16 18:05 UTC
Currently, applying Kashida is by adding "ـ" U+0640 ARABIC TATWEEL _between_ letters. However, a more elegant way is by stretching a specific letter within the word. This method is popular with old scriptures, calligraphy, and handwritten messages.

Examples: (Taken from [KFGQPC print](https://books.islamway.net/1/01_Mushaf_AlMadinah_L_549.pdf) of Quran). 

![kaaf-alif-maqsura-kashida](https://github.com/user-attachments/assets/93d1e949-da55-4b1a-9701-eb18a53c50d5)

Single-letter Kashida applied to initial form "كـ" and final "ـى"

![kaaf-baa-kashida](https://github.com/user-attachments/assets/9a8f36c3-7555-4b35-a5a4-9f9da6baf525)

Applied to "ـكـ" and "ـب" in  "الكتب"

![kaaf-faa-kashida](https://github.com/user-attachments/assets/ac1b8e45-0091-4aaa-ab30-0fc7183e57d6)

Applied to "كـ" and "ـف" in "كيف"

![kaf-kashida](https://github.com/user-attachments/assets/97360c51-15a6-403f-974d-0c6ba51e7876)

Applied to "ـكـ"

![regular-kashida](https://github.com/user-attachments/assets/d2831103-02b3-4734-9562-84614c425daa)

Applied to last two connected letters in "الناس" (notice that س and ا are not connected) and last two connected letters in "عظيم".

**Comment by emmamarichal** [comment] 2024-10-23 12:33
Hello @avidseeker,

Of which font are you talking?

Since no update is already existing, and it's a design choice question, not a bug, I will close this issue for now.
If any designer of arabic font wants to add this modification, he can open a new issue for an update. 
Thanks!

**Closed by emmamarichal** 2024-10-23 12:33 UTC
Labels: I Font Bug
