### ISSUE TITLE
Pompiere does not work with MS Office

### ISSUE THREAD

**Issue by roe85** [google/fonts#1646] opened 2018-08-20 08:53 UTC
I installed Pompiere on two Windows machines (7 and 10) and tried to use it in Word 2007 an 2016 aswell as the Publisher and it did no work. 
In Word it would just take some other font when selected and Publisher would say it is not installed even though I installed it beforehand.

Although I found a workaround: I can use it in Windows own WordPad and copy'n'paste it to Publisher and then use it.

**Comment by laerm0** [comment] 2019-01-29 19:47
Hi @roe85 , do you still have this issue?

**Comment by liesbethmaes** [comment] 2019-02-20 10:23
Dear
I just had the same issue with font Pompiere used in Office 2016 under Windows 10. 
Also copy paste from wordpad works fine. After closing and reopening the document, the font dissappeared.

**Comment by roe85** [comment] 2019-02-27 15:27
Is there a new Version of the font? I still have the same issue.

**Comment by laerm0** [comment] 2020-02-21 20:55
Hi, this font was updated last July which I believe would fix the problem (I can't reproduce it now). I'll tentatively close the issue and please report back if the problem still exists and I'll re-open it.

**Closed by laerm0** 2020-02-21 20:55 UTC
Labels: Needs Confirmation

**Comment by liesbethmaes** [comment] 2020-03-02 09:09
Thanks for the update, this resolved the problem!

**Comment by laerm0** [comment] 2020-03-02 18:46
Thanks for the update. 👍🏻
