### ISSUE TITLE
Roboto locally installed issue

### ISSUE THREAD

**Issue by davelab6** [google/fonts#102] opened 2015-08-25 18:58 UTC
I confirmed https://code.google.com/p/googlefontdirectory/issues/detail?id=416 is still valid:
1. On windows 7 with latest chrome (Version 44.0.2403.157) visit www.google.com/fonts and download and install the roboto family from there
2. Visit https://www.google.com/fonts/specimen/Roboto+Condensed and Roboto Condensed's Regular style is shown as Roboto's: 
3. Firefox does not show this. 

![attachment](https://cloud.githubusercontent.com/assets/261579/9476181/665e1682-4b39-11e5-8a3f-8c0a5bc48e41.png)

Also reported on https://twitter.com/kaibrach/status/726905298464600065

**Comment by snstar2006** [comment] 2016-01-22 19:59
The bug still exists. Google font doesn't work on Chrome??

**Comment by davelab6** [comment] 2016-01-22 23:21
@jamesgk do you have any insight into this?

**Comment by jamesgk** [comment] 2016-01-27 00:50
This is odd! There are no obvious problems with the name tables in either Roboto-Regular or RobotoCondensed-Regular. But clearly Chrome on Windows is getting them confused. However, this doesn't seem to be happening on Mac or Linux.

Since it seems to be Windows-specific, perhaps this is related to [this other bug](https://github.com/google/roboto/issues/37)? It's not clear to me how Windows is organizing these fonts once they're installed.

**Comment by jamesgk** [comment] 2016-01-27 00:56
Never mind, that other bug doesn't apply to the Roboto binaries here. So no leads, I guess.

**Comment by snstar2006** [comment] 2016-01-27 15:21
It seems like not just Roboto has this problem. I also notice this issue with PT Sans Narrow showing as PT Sans. 
![google-font-ptsans-scrnshot](https://cloud.githubusercontent.com/assets/2364410/12617913/47a1f05c-c4d7-11e5-89da-5cba8f37d678.jpg)

**Comment by davelab6** [comment] 2016-01-27 15:27
I'll try to reproduce this again

**Comment by davelab6** [comment] 2017-03-09 14:10
https://twitter.com/briandotjp/status/837159394362040320 reports this again

**Comment by davelab6** [comment] 2017-03-09 14:10
@m4rc1e please test the upcoming Roboto v2.x update against this :)

**Comment by m4rc1e** [comment] 2017-03-09 15:22
@davelab6 I can't replicate the issue after following your step by step.


![screen shot 2017-03-09 at 15 21 13](https://cloud.githubusercontent.com/assets/7525512/23756610/207cc34e-04dc-11e7-934b-4cc27d91ae39.png)


I'm using Win 7 Chrome v56

**Comment by laerm0** [comment] 2017-09-11 20:05
I cannot reproduce this issue either. Safe to close?

![screen region 2017-09-11 at 16 05 01](https://user-images.githubusercontent.com/10780161/30294424-06f4556a-970b-11e7-86db-e5b73fadd24c.png)

**Comment by davelab6** [comment] 2017-09-11 21:07
Sure, if we can't reproduce it then yes

**Comment by laerm0** [comment] 2017-09-12 14:57
Sounds good. Closing.

**Closed by laerm0** 2017-09-12 14:57 UTC
Labels: z_PT Sans, z_Roboto, z_Roboto Slab
