### ISSUE TITLE
Hindi Sentences should not end with full-stop.

### ISSUE THREAD

**Issue by vikaskyadav** [google/fonts#309] opened 2016-07-06 10:05 UTC
This is quite big blunder as hindi sentences end with pipe symbol "|"  instead of full-stop used everywhere.

**Comment by kalapi** [comment] 2016-07-06 13:59
With all due respect this statement is entirely incorrect. (Also, this is an open '[issue](https://github.com/google/fonts/issues/304)'.)

Firstly, the _purnavirama_ is encoded as a character in the [Devanagari Unicode block](http://www.unicode.org/charts/PDF/U0900.pdf) (0x0900–0x097F) as Devanagari Danda (0x0964) and can be easily accessible via various common input methods (i.e. Devanagari Qwerty keyboard on OSX, 'Hindi' keyboard on iOS, etc.). The 'pipe' symbol (or 0x007C Vertical Line) has an entirely different semantic meaning in text and is usually not designed to fit the weight and proportions of Devanagari letterforms.

Secondly, while I agree that the Devanagari typefaces might benefit by showcasing the _purnavirama_ in the sample phrases on fonts.google.com, it is by no means a mandatory convention. A lot of modern text contexts including newspapers, magazines, paperbacks, as well as online publications increasingly use Latin punctuation. And surely, this phenomenon can be attributed to the inability of proper input technologies in the earlier days of computing. However, it is important to acknowledge that written language also evolves along with, if not at the same pace as spoken language. Thus, it could be argued that its omission may not quite be as big a blunder as it is made to be

Thus, in my opinion the more important issues could be things like showcasing phrases in more languages that use the Devanagari script instead of only sticking to Hindi to showcase language support and localised forms.

**Comment by davelab6** [comment] 2016-07-27 20:45
Closing as a duplicate of #304

**Closed by davelab6** 2016-07-27 20:45 UTC
