### ISSUE TITLE
Issue with Inter font in Adobe Illustrator

### ISSUE THREAD

**Issue by piersonjon** [google/fonts#4143] opened 2021-12-02 21:51 UTC
Our graphic designer is reporting an issue using the Inter font within Adobe Illustrator.
When automatic hyphenation is on, the hyphen symbol becomes an A with diacritical breve. (Ă)

Technical info:
filename: Inter-regular.ttf
machine model: MacBookPro18,1
CPU: Apple M1 Pro
Adobe Illustrator 26.0.1
Creative Cloud 5.6.0.788

Please let us know if we can improve any diagnostics with additional information.
Thank you for investigating.
![image](https://user-images.githubusercontent.com/8460978/144508861-4f600e8b-d530-4e5a-b102-0eecd2ef2566.png)

**Comment by RosaWagner** [comment] 2021-12-10 13:12
Thanks for your issue report. I couldn't reproduce using Apple M1 / Illustrator 25.4.1. I installed version 26.0.1 and can't reproduce either. Did Adobe brought a fix in the past week and can I close this issue, or is still happening on your side?

**Closed** 2022-02-24 11:24 UTC
Labels: I Font Bug
