### ISSUE TITLE
Please Update This Repo with new fonts

### ISSUE THREAD

**Issue by justvcreative** [google/fonts#550] opened 2016-12-15 16:28 UTC
I cloned this repo and noticed that it doesn't have all the fonts on your website. I noticed a bunch of fonts were not here as I was searching for them. We use this repo at my job and it's important for us to have the most up to date google fonts. I also noticed that it's very difficult to keep up with new a font  because you all don't put the date you added the font on the website or in the repo. Which makes this even more difficult. So in the future, please add the release/publish date on the google font website whenever you release a font and please keep this repo up to date. 

Some fonts I noticed were missing was Space Mono, Trirong, Taviraj but there could be others. If you are going to have a repo at least keep it updated every time you release a font and please start putting the dates on the pages. These are just the ones I found, there could be more.

**Comment by davelab6** [comment] 2017-01-05 17:53
@justvcreative agree :)

**Comment by davelab6** [comment] 2017-05-16 16:49
I hope @m4rc1e can get this to 100% this week

**Comment by m4rc1e** [comment] 2017-05-18 15:43
Hey folks,

Here's a list of the families I'll be adding:
Amatica SC
Amiko
Aref Ruqaa
Arima Madurai
Assistant
Athiti
Atma
BioRhyme
BioRhyme Expanded
Biryani DemiBold
Biryani Heavy
Biryani UltraLight
Bungee
Bungee Hairline
Bungee Inline
Bungee Outline
Bungee Shade
Cairo
Chathura
Coiny
David Libre
El Messiri
Farsan
Frank Ruhl Libre
Galada
Harmattan
Heebo
Jomhuria
Katibeh
Kavivanar
Kumar One
Kumar One Outline
Lalezar
Lato Hairline
Lemonada
Libre Franklin
Mada
Maitree
Meera Inimai
Miriam Libre
Mirza
Mitr
Mogra
Pattaya
Pavanam
Pridi
Prompt
Proza Libre
Rakkas
Rasa
Reem Kufi
Scope One
Secular One
Shrikhand
Space Mono
Suez One
Taviraj
Trirong
Yatra One
Yrsa

This should bring fonts.google.com and this repo back into sync.

**Comment by davelab6** [comment] 2017-05-19 03:53
Thanks Marc, that sounds comprehensive :)

**Comment by davelab6** [comment] 2017-05-24 20:25
Closing as duplicate of https://github.com/google/fonts/issues/271

**Closed by davelab6** 2017-05-24 20:25 UTC
Labels: Priority 0 - Urgent and Important
