### ISSUE TITLE
Add Sixtyfour 

### ISSUE THREAD

**Issue by chrissimpkins** [google/fonts#5325] opened 2022-09-26 11:37 UTC
**Font Project Git Repo URL:**

https://github.com/jenskutilek/homecomputer-fonts by @jenskutilek

**Super short description of the Font Family:**

"Inspired by the article [Raster CRT Typography (According to DEC)](https://www.masswerk.at/nowgobang/2019/dec-crt-typography) by Norbert Landsteiner, I reworked some old pixel versions of the [Commodore 64](https://github.com/jenskutilek/homecomputer-fonts) and [Amiga Workbench fonts](https://github.com/jenskutilek/homecomputer-fonts-wb) I had done years ago to include variable font axes for the size of the horizontal scanlines and the amount of horizontal bleed of the pixels due to the phosphor latency found in CRT displays."

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [X] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [X] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to namecheck.fontdata.com (EU Trademark g:sixtyfour (2407542))
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

![64](https://user-images.githubusercontent.com/4249591/192266500-6f24385d-01db-49bb-8658-393a4a7a2de6.png)

**Comment by davelab6** [comment] 2022-09-26 12:33
Closing as duplicate of https://github.com/google/fonts/issues/3425

**Closed by davelab6** 2022-09-26 12:33 UTC
Labels: I New Font, II Submission
