### ISSUE TITLE
Please add a personal font library

### ISSUE THREAD

**Issue by a2ys** [google/fonts#6490] opened 2023-07-01 12:24 UTC
**Describe the issue**

The site seems to be complete, not in terms of the number of fonts but in terms of features, but there still is a quality of life feature that I can't seem to find. If a personal font library were to be present, it would have been a great utility!

By personal font library, I mean the user should be able to create their own library of favorite fonts, or fonts the user wants to use later, or check out later. There are more than a thousand different fonts out on the website, so it's not possible to browse the fonts and remember the fonts, which as I mentioned earlier, the user likes or wants to use later on.

You may incorporate any kind of authentication to allow this feature, or use the local browser cache to do this, that's up to the more skilled engineers, but this utility, if added, would be of great use!

**Comment by RosaWagner** [comment] 2023-07-04 08:26
Hi @a2ys thanks for you request. This is demanded often enough for GF engineers to know about it, wether it will be implemented or not is unknown. Therefore closing because this repo is mainly about managing the font collection, not the website's UI/UX.

(Duplicate of #6289)

**Closed by RosaWagner** 2023-07-04 08:26 UTC
Labels: I Tools / workflow / repo, I API / Website / Platform, I Request

**Comment by a2ys** [comment] 2023-07-04 08:44
Sure! Thanks for letting me know!
