### ISSUE TITLE
error in font comfortaa?

### ISSUE THREAD

**Issue by epson950** [google/fonts#229] opened 2016-03-19 22:53 UTC
I Online a few words in Russian is not displayed correctly when an external font comfortaa script: cyrillic
![image20160320014115](https://cloud.githubusercontent.com/assets/11770015/13901734/28a73d48-ee3e-11e5-8bb1-de77e68eb74f.jpg)
![image20160320013937](https://cloud.githubusercontent.com/assets/11770015/13901735/3723ca8a-ee3e-11e5-8ef7-663fc1a644b8.jpg)
[site](http://repetitordlyavas.ru/index.php/pushkin)

**Comment by ottomen** [comment] 2016-06-13 07:12
Yep. I have the same issue. What should we do with it?

**Comment by alexeiva** [comment] 2016-06-19 21:26
Thank you for submitting this. 
Issue confirmed. There is a problem in Comfortaa's Cyrillic kerning.

**Comment by alexeiva** [comment] 2016-06-20 20:43
Please download the latest version of the font from the authors page. It fixes the problem.
http://aajohan.deviantart.com/art/Comfortaa-font-105395949

If you need to use it for web use the webfont-genetor:
https://www.fontsquirrel.com/tools/webfont-generator

The update will appear on GWF after some technical checks.

**Comment by davelab6** [comment] 2016-07-02 18:34
https://twitter.com/bertydew/status/748525963688968192

**Comment by alexeiva** [comment] 2016-08-01 16:21
This will fixed in the next update

**Comment by MasterBopoH** [comment] 2016-08-17 09:43
so approximately when that would be? in this month?

**Comment by davelab6** [comment] 2016-08-18 16:47
We can't comment on specific release dates.

**Comment by igorleanch** [comment] 2016-12-26 17:01
Thank you very much, it helped me.

**Comment by alexeiva** [comment] 2017-01-09 23:15
I am closing this, because there is a duplicate of this issue #570. I suggest 570 to be used for further tracking

This issue has been fixed, but not yet updated on the servers. 

Feel free to download the update directly from the git repo:
https://github.com/alexeiva/comfortaa/releases/tag/v.3.000

**Comment by davelab6** [comment] 2017-01-09 23:15
Will be fixed in https://github.com/google/fonts/pull/535

**Closed by alexeiva** 2017-01-09 23:15 UTC
Labels: z_Comfortaa
