### ISSUE TITLE
Montserrat and -webkit-text-stroke overlapping

### ISSUE THREAD

**Issue by andersson09** [google/fonts#4212] opened 2022-01-12 13:13 UTC
You can see the issue by running https://www.html-code-generator.com/css/text-stroke-generator for Montserrat (a pretty popular font).

**Comment by BigPxl-Caleb** [comment] 2022-01-12 20:35
Yup. This was working just fine three days ago and now a site that we use the font on is all goofy

**Comment by vtucker** [comment] 2022-01-12 23:10
Same here on the main title: https://clearmortgage.com/meet-the-team

**Comment by amgdevelopers** [comment] 2022-01-12 23:11
Yes this just happened to a client's website. All primary headings were using -webkit-text-stroke and now they are rendering this weird bug.

**Comment by RosaWagner** [comment] 2022-01-13 10:35
Ah this is not a bug from the font, very much sorry.

We just onboarded an upgraded version of font that is now `variable` and it therefore keeps overlapping contours.
You can workaround this by downloading a static version of the font with merged contours and self host it: https://github.com/googlefonts/Montserrat/tree/master/fonts/ttf

You will find more answers in this issue: https://github.com/rsms/inter/issues/292

**Comment by thlinard** [comment] 2022-01-13 14:37
A substitution would be to use `text-shadow`, like this:
https://codepen.io/thlinard/pen/ZEXVQyM

**Comment by cannobbio** [comment] 2022-01-17 23:15
This worked for me:

Instead of loading it like this (the variable size way):
`https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,600;0,700;0,800;0,900;1,400;1,700&display=swap`

Load it like this (static sizes):
`https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;400i;600;700;700i;800;900&display=swap`

**Comment by enogael** [comment] 2022-01-18 17:19
> Load it like this (the static way): `https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;400i;600;700;700i;800;900&display=swap`

This is not working : "400: Invalid selector". You can't get the italics only with the weight axis range specified.

Even the old syntax https://fonts.googleapis.com/css?family=Montserrat:400;400i;700;700i;&display=swap is not working either, still getting overlapping strokes, so it means it also loads the variable font ?

So our only option here is to use a self-hosted static version ?

**Comment by diefl** [comment] 2022-01-20 16:09
The following setup is working for me now:
> using v15 of the font
> embed fonts locally

**Comment by TsiresyMDG** [comment] 2022-01-27 09:52
I have same problem to my website about the Montserrat stroke, how can I resolve it ?

**Comment by hogash** [comment] 2022-02-11 10:24
Issue still happening with v23 .

**Comment by m4rc1e** [comment] 2022-02-11 10:33
Alright, I've finally bothered to make a test case, https://jsbin.com/movowohesu/edit?html,output.

I'll open up an issue with webkit.

**Comment by m4rc1e** [comment] 2022-02-11 11:43
No problem!

I understand this stuff is incredibly frustrating.

**Comment by jimmytherrien** [comment] 2022-03-04 17:01
> The following setup is working for me now:
> 
> > using v15 of the font
> > embed fonts locally

How can I get the URLs for v15?

**Comment by 786ihtisham** [comment] 2022-03-19 20:16
I was using a URL that was overlapping the stroked text but thanks to @[RosaWagner](https://github.com/RosaWagner)  for sharing the solution :-). It worked for me.

**Comment by RosaWagner** [comment] 2022-07-01 09:47
Since this is not a GF issue, I close it. If anybody have updates form webkit, please feel free to feed this thread.

**Closed by RosaWagner** 2022-07-01 09:47 UTC

**Comment by lcnogueira** [comment] 2023-07-07 13:00
Just confirming here that using a self-hosted static version of the font and applying the stroke to it solved my problem with the `Mulish` font as well. Thank you, Rosa 👍

**Comment by bogdanblazhkevych** [comment] 2024-12-09 03:31
If you are like me and are still having this issue and the text shadow hack is not good enough, you can use 

```
paint-order: stroke fill;
```

this changes the behavior a slightly, but it will give you a text stroke without the overlap.
