### ISSUE TITLE
Kumar One not in repository

### ISSUE THREAD

**Issue by abumalick** [google/fonts#608] opened 2017-01-25 22:51 UTC
Where is [Kumar One](https://fonts.google.com/specimen/Kumar+One), I cannot find it in the repo ?
All fonts of the website should be here, shouldn't it ?

**Comment by davelab6** [comment] 2017-01-31 00:47
@abumalick thanks for reporting this! I'm closing as a duplicate of https://github.com/google/fonts/issues/271

**Closed** 2017-02-09 16:43 UTC
