### ISSUE TITLE
Merriweather cyrillic uppercase Ы letter

### ISSUE THREAD

**Issue by VladShcherbin** [google/fonts#588] opened 2017-01-22 08:14 UTC
Chrome
Mac os sierra 10.12.2

Google fonts website, lowecase letter `ы` is okay, uppercase `Ы` is not.

<img width="325" alt="screen shot 2017-01-22 at 11 11 51 am" src="https://cloud.githubusercontent.com/assets/6711845/22181039/ebc9f6f6-e093-11e6-9e97-baf577160dae.png">

**Comment by m4rc1e** [comment] 2017-01-23 10:35
@alexeiva Could you look into this?

This seems to be a recurring issue.

**Comment by m4rc1e** [comment] 2017-01-23 11:03
@VladShcherbin which browser?

**Comment by VladShcherbin** [comment] 2017-01-23 11:04
@m4rc1e google chrome 54.0.2840.98

**Comment by VladShcherbin** [comment] 2017-01-23 11:07
same with Safari - Version 10.0.2 (12602.3.12.0.1)

**Comment by m4rc1e** [comment] 2017-01-23 11:07
@VladShcherbin confirmed. 

I'll investigate this now.

![screen shot 2017-01-23 at 11 06 58](https://cloud.githubusercontent.com/assets/7525512/22201600/27505dfa-e15c-11e6-971c-b83085e99db5.png)

**Comment by m4rc1e** [comment] 2017-01-23 11:12
@VladShcherbin I can confirm we've fixed this in a pull request, [#37](https://github.com/EbenSorkin/Merriweather/pull/37) sent to the upstream [repo](https://github.com/EbenSorkin/Merriweather)

As soon as @EbenSorkin merges this, I will pr it here. 

![screen shot 2017-01-23 at 11 10 21](https://cloud.githubusercontent.com/assets/7525512/22201693/9c14fd62-e15c-11e6-9167-257fca2cf259.png)

Cheers,
Marc

**Comment by VladShcherbin** [comment] 2017-01-23 11:14
@m4rc1e great, thank you 👍

**Comment by m4rc1e** [comment] 2017-01-23 11:15
@alexeiva do we have any idea what caused this?

**Comment by alexeiva** [comment] 2017-01-24 18:21
This is an old bug. `Ы` was made from two components `Ь` + `I` and the they got reordered during export to UFO (from FontLab). Anyway I don't recommend using components for `Ы`, since the left `Ь`-part is generally compensated in width than proper `Ь`.

This is similar to how component-made fractions collaps when you open a UFO in Glyphs App.

**Comment by davelab6** [comment] 2017-01-31 00:52
@VladShcherbin confirmed fixed on fonts.google.com so closing:

<img width="642" alt="screen shot 2017-01-30 at 19 51 34" src="https://cloud.githubusercontent.com/assets/261579/22448189/866a6d0c-e725-11e6-8253-84c2ec7dc254.png">

@alexeiva thanks for explaining :)

**Comment by a-rusak** [comment] 2017-03-22 12:08
Any updates? The issue still exist:
![image](https://cloud.githubusercontent.com/assets/9419616/24197086/3ff684aa-0f11-11e7-8b78-d5f183ab59a1.png)

**Comment by VladShcherbin** [comment] 2017-03-22 12:11
Can confirm, issue is back:

<img width="302" alt="screen shot 2017-03-22 at 3 11 09 pm" src="https://cloud.githubusercontent.com/assets/6711845/24197226/dd7a5328-0f11-11e7-9369-bbd48882e01f.png">

**Comment by VladShcherbin** [comment] 2017-04-04 13:10
@davelab6 , @m4rc1e reopen this, the bug is not fixed for so long. Can't even imagine, how bad it
 looks on cyrillic sites, using this font 😱

**Comment by m4rc1e** [comment] 2017-04-04 13:29
@VladShcherbin we had to revert the fonts from v2.000 back to v1.584 due to regression issues, a few months back. 

@davelab6 Shall I hotfix this old version, while Eben continues to fix the regression issues in v2.000?

**Comment by VladShcherbin** [comment] 2017-04-04 14:33
@m4rc1e I appreciate your work, guys, but reverting the font and letting such a huge bug to exist for months, knowing about it and not fixing...

The users (me too), who are using Google Fonts, expect it to be tested and reliable as millions of sites are using Google Fonts every day. Such bugs in production... I really don't understand this, sorry.

**Comment by m4rc1e** [comment] 2017-04-04 14:44
@VladShcherbin the revert was necessary because of a far larger issue, https://github.com/EbenSorkin/Merriweather/issues/41. This was the lesser of two evils I'm afraid.

Our QA tools have been improving for the past few months. It's difficult to spot such errors because they do not violate any technical specifications. It has to be done visually. We now have regression tools which will show if glyphs have changed too drastically since the previous release. Again, I need to check this by eye. If you have some free time, feel free to write a ML based tool which can analyse the outlines of a glyph and work out what its meant to be :-)

**Comment by VladShcherbin** [comment] 2017-04-04 14:54
@m4rc1e I'm not an expert in fonts, just a regular developer.

You knew about this bug when reverted the font version and @a-rusak mentioned it again 2 weeks ago. As a website owner, I would be very upset if all by headings (and all uppercase words) would have a wrong letter. I'm just upset of seeing this happen in such a big trusted company.

Anyway, I really hope it will be fixed as soon as possible. Thanks.

**Comment by VladShcherbin** [comment] 2017-07-02 19:09
3 months later still not fixed, half year bug in all cyrillic websites. Definitely won't use google fonts again and won't recommend it to anyone.

Simply wow.

**Closed** 2017-08-07 18:22 UTC
Labels: Priority 0 - Urgent and Important, z_Merriweather

**Comment by VladShcherbin** [comment] 2017-08-09 13:09
Even though this issue is closed, the bug is still not fixed which is no surprise.

<img width="400" alt="screen shot 2017-08-09 at 4 07 17 pm" src="https://user-images.githubusercontent.com/6711845/29122993-e78a8b98-7d1c-11e7-9deb-da0f4c12f4be.png">

**Comment by EbenSorkin** [comment] 2017-08-09 13:17
I think Dave closed it because it is fixed in the files that will be made
live soon.
