### ISSUE TITLE
New Montserrat rendering issue when using -webkit-text-stroke

### ISSUE THREAD

**Issue by mikemccarron** [google/fonts#4249] opened 2022-01-27 15:54 UTC
A recent change to the file that is served up for Montserrat has created an issue when using `-webkit-text-stroke`. The shape crisscrosses in some places or is a separate shape in others. Below is an example:

https://share.getcloudapp.com/wbuYzJRN

The expected result is clean outlines for each character. (This had been the case up until recently)

**Comment by m4rc1e** [comment] 2022-01-27 15:58
Duplicate of #4212

**Closed by m4rc1e** 2022-01-27 15:58 UTC
