### ISSUE TITLE
Fix Concert One vertical metrics

### ISSUE THREAD

**Issue by mykthex** [google/fonts#362] opened 2016-08-26 13:08 UTC
The concert one font does not display correctly on Linux. It is rendered with the wrong top offset. It looks like there's a problem with the font descender in the font.  It happens on Firefox and on Chrome for Linux (tested with Ubuntu and others OS).

**Comment by m4rc1e** [comment] 2017-07-05 14:20
Made up a test case for this:

http://jsbin.com/zeyuvifobe/edit?html,output

I currently don't have access to my Ubuntu machine, will check this later. Can you confirm the issue is present still?

**Comment by fitojb** [comment] 2017-07-06 11:23
Looks like this to me:
![captura de pantalla de 2017-07-06 06-22-00](https://user-images.githubusercontent.com/554953/27908872-8ac20356-6213-11e7-98cd-560af82a89ec.png)

**Comment by m4rc1e** [comment] 2017-07-06 11:54
@fitojb thanks! 

hhea descender and os/2 typo descender are both positive integers, they should be negative.

**Comment by m4rc1e** [comment] 2017-07-06 12:16
I've rolled out another test using fonts which have their vert metrics fixed

http://jsbin.com/zigurinoza/1/edit?html,output

**Comment by laerm0** [comment] 2017-09-06 19:09
The fonts currently live work fine for me. Do you still have this issue, @mykthex?

**Comment by davelab6** [comment] 2017-12-06 03:59
> The fonts currently live work fine for me

What system did you test that on?

**Comment by laerm0** [comment] 2017-12-06 04:38
Ah, yes, there is an issue now. They looked fine before (Firefox 57.0 on Ubuntu 16.04.03). I'll add this to my list.

![screen region 2017-12-05 at 23 37 00](https://user-images.githubusercontent.com/10780161/33644833-5431e502-da15-11e7-8361-86c7bcebfb86.png)

**Comment by laerm0** [comment] 2017-12-06 04:38
(though, strangely, what I see and what @fitojb demonstrated are different 🤔 )

**Comment by laerm0** [comment] 2017-12-13 19:45
Okay, I have found some metrics that work for this one. How do we feel about this?

![screen region 2017-12-13 at 14 43 05](https://user-images.githubusercontent.com/10780161/33958966-09bb0314-e014-11e7-86a6-665d5c911740.png)

If this looks good, I'll PR it.

**Comment by davelab6** [comment] 2017-12-13 21:18
LGTM

**Comment by laerm0** [comment] 2018-02-26 18:48
The file in the repo is good so it looks like this just needs to be pushed (still flawed online).

**Comment by laerm0** [comment] 2020-02-26 19:06
ping for push to site @davelab6 @m4rc1e

**Comment by hyungtaecf** [comment] 2020-06-07 22:33
It appears with the same bug for me. I was trying to use it in a Flutter application. But it seems I need to choose another font.

**Comment by philjackson** [comment] 2021-01-13 11:23
@laerm0 Hey there. This is affecting our app at the moment, was wondering if the fixed version might make it up soon?

**Comment by different55** [comment] 2023-04-28 01:30
Hope it's alright to bump this to try to get it pushed to the site. It's been a few years and it'd be nice to get this issue fixed up once and for all.

**Comment by RosaWagner** [comment] 2023-06-01 13:58
The problem is that updating the vertical metrics for this font will break all website to which it is served. I am sure we can ever fix that issue, but we'll bring up to a meeting again.

**Comment by davelab6** [comment] 2023-07-17 16:09
The font is broken, let's proceed.

**Comment by eliheuer** [comment] 2023-12-19 03:22
This has no source files that I can find, the fonts were added to google/fonts in the [Initial commit](https://github.com/google/fonts/tree/main/ofl/concertone), so I will make a new source repo.

**Comment by davelab6** [comment] 2023-12-19 07:49
Sources are in https://github.com/googlefonts/googlefontsdirectory-old/tree/main/ofl/concertone/src

**Comment by chrissimpkins** [comment] 2024-05-03 18:37
Moved to Q2 and assigned to @emmamarichal

**Closed** 2024-05-29 23:27 UTC
Labels: -- Bad rendering, I Font Bug
