### ISSUE TITLE
[URGENT] Comfortaa BUG, one cyrillic letter overlaps in any browser or locally on ALL SITES!

### ISSUE THREAD

**Issue by UralZima** [google/fonts#570] opened 2017-01-09 15:21 UTC
Hello. This font is awesome, but it have a bug in one cyrillic letter, it overlaps on another letter (not all letters)
Example:
Вы - capital 'В' overlaps 'ы', this is for most next characters
Ва - this case all is fine. A few characters are ok.
Much people using this font on russian sites, and all of them have this bug. 

I tested it in Chrome, Firefox, installed locally in libreoffice, etc.

I tried to edit this font in fontforge, but width seems to be ok...

Please fix it asap or tell me how to fix it in fontforge and I can use it locally.

Thanks!

**Comment by m4rc1e** [comment] 2017-01-09 16:02
I'll take a loot at this very soon.

**Comment by alexeiva** [comment] 2017-01-09 23:12
This is a very old bug, it has been fixed, but not yet updated on the servers. Please wait for the update. Duplicate issue https://github.com/google/fonts/issues/229

<img width="470" alt="screen shot 2017-01-10 at 12 06 52 am" src="https://cloud.githubusercontent.com/assets/16634089/21787298/b854b1f0-d6c8-11e6-98d5-3890905b09a6.png">

If you want to use the new version right away, download it from the git repo. 
https://github.com/alexeiva/comfortaa

**Comment by davelab6** [comment] 2017-01-09 23:16
Closing as duplicate of https://github.com/google/fonts/issues/229

**Comment by m4rc1e** [comment] 2017-01-23 14:45
Ok, we have two bugs reporting the same issue on this font, #570, #229.

I can confirm that pr #535 fixes this overlap issue.
![screen shot 2017-01-23 at 14 43 14](https://cloud.githubusercontent.com/assets/7525512/22208299/531ea676-e17a-11e6-85a2-07587cdb1021.png)

If you're still experiencing this issue, make sure you have downloaded the newest version, [v3.000](https://fonts.google.com/specimen/Comfortaa) and cleared your font cache on your local system.

**Closed** 2017-01-23 14:55 UTC
