### ISSUE TITLE
Update Lato font to 2.015 version?

### ISSUE THREAD

**Issue by dasklney** [google/fonts#165] opened 2015-12-22 06:47 UTC
Hello,

I really love Lato web font and intend to use on all of my website, but the current version at Google Web Fonts doesn't support Vietnamese.

I can see that the new version from Latofonts.com does support Vietnamese, please update the font for us to have more scripts.

Resource: http://www.latofonts.com/

Many thanks,
Giang

**Comment by davelab6** [comment] 2015-12-22 14:49
I will do this early next year

**Comment by davelab6** [comment] 2016-03-31 22:39
Quick update on this, I have not yet processed this but I will do soon :)

**Comment by borissamardzija** [comment] 2016-08-03 12:42
Hi @davelab6, any chance Lato will be updated soon?

Current version is missing some diacritics, as you can see here
http://jsbin.com/momova/edit?html,css,output

**Comment by davelab6** [comment] 2016-08-08 15:30
Closing as duplicate of #6

**Closed by davelab6** 2016-08-08 15:30 UTC
Labels: z_Lato
