### ISSUE TITLE
Update Noto fonts (LGC) to version 2.0

### ISSUE THREAD

**Issue by cssobral2013** [google/fonts#1485] opened 2018-03-13 19:20 UTC
http://google.com/get/noto

**Comment by fitojb** [comment] 2018-03-13 21:02
No need to file duplicates :). Duplicate of #398

**Comment by cssobral2013** [comment] 2018-03-13 21:07
Sorry, I didn't see it. Feel free to close this, then.


Em 13 de mar de 2018 18:02, "Adolfo Jayme-Barrientos" <
notifications@github.com> escreveu:

No need to file duplicates :). Duplicate of #398
<https://github.com/google/fonts/issues/398>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/fonts/issues/1485#issuecomment-372817156>, or mute
the thread

**Closed** 2018-03-15 19:40 UTC
