### ISSUE TITLE
name table issues with eg Rubik and Figma/Word/Powerpoint

### ISSUE THREAD

**Issue by davelab6** [google/fonts#3214] opened 2021-03-18 14:28 UTC
A user wrote me,

> Hello, thank you for the beautiful font "Rubik", unfortunately, it has one error. This font does not work correctly, everything is fine on the Mac OS system, but in Windows some fonts are not always detected by various programs (Word, Figma, PowerPoint). For example, in the Figma program on Windows, there is no Rubik SemiBold font. What is the reason for this and how to solve this problem?

@m4rc1e I wonder if you can review this for your name table fontbakery checks refactoring

@RosaWagner as you are working on Rubik Generative fonts set and the upstream, please take a look and see if you can reproduce

**Comment by m4rc1e** [comment] 2021-03-18 15:02
Do we know if they're using the VF version of Rubik?

**Comment by Marianna-Ya** [comment] 2021-03-22 20:46
Hi! Yes, I use the VF version of Rubik. I downloaded it from Google Fonts. But I don't have SemiBold of Rubik at all. And I use Windows 10 if it matters. 
I downloaded the entire font family and then installed only the variable font. As a result, I have only a part of the family installed. Screenshots attached. 
Part 1: 
![image](https://user-images.githubusercontent.com/81188480/112055352-c8b30580-8b67-11eb-80eb-2b0203c8d066.png)
 Part 2: 
![image](https://user-images.githubusercontent.com/81188480/112055392-d6688b00-8b67-11eb-8ae2-827264a9bc29.png)

Yes, I can install additional fonts from the "static" folder. But they will only work in Adobe. They don't work in the Figma.

Part 3: 
![image](https://user-images.githubusercontent.com/81188480/112055741-47a83e00-8b68-11eb-93ef-8143c8e44b1e.png)
Part 4: 
![image](https://user-images.githubusercontent.com/81188480/112055869-6ad2ed80-8b68-11eb-8719-39dcad830992.png)
Part 5:
![image](https://user-images.githubusercontent.com/81188480/112056007-8e963380-8b68-11eb-8bf7-914cd5d1d1f4.png)

I would be grateful if you could help fix the problem.

**Comment by Marianna-Ya** [comment] 2021-03-25 13:18
I have some new information:
![image](https://user-images.githubusercontent.com/81188480/112479035-adbddc80-8d85-11eb-967b-7ac4981174ac.png)

**Comment by romzes2** [comment] 2021-03-25 14:23
Well Marianna-Ya asked me personally to take a closer look using TeamViewer to understand the issue.
Looks liks the Windows incorrectly recognizes SemiBold and ExtraBold fonts and creates additional font family to support them. It is a little bit hard to explain, but here is example: if you will setup Rubik-Regular.ttf and Rubik-SemiBold.ttf only, Win will recognize 3 fonts, (Regular, Regular & SemiBold). Another one, if you will setup all package (14 fonts with Italic), Windows will see 16.

Since windows incorrectly detects this two fonts, after installing it creates additional Regular package for SemiBold and ExtraBold. So instead 14 fonts you get 16.
Where 3 of them are Regular 
- Regular + 13 weights (Rubik)
- Regular + 1 weight (Rubik SemiBold)
- Regular + 1 weight (Rubik ExtraBold)
In most cases windows apps will correctly understand what they should use, but for some apps like Figma. They will detect only last installed font (like Regular + 1 weight (Rubik ExtraBold)) and ignore others (actually here is really random part), if you will uninstall Rubik ExtraBold, Figma will see (Regular + 13 weights (Rubik)) but without ExtraBold...etc.

The problem I found in this two fonts:
![image](https://user-images.githubusercontent.com/10059282/112486441-89adcb80-8d84-11eb-86bd-b5554385fedc.png)
I changed font weight from Demi to SemiBold, and recreated the font. Same I done for ExtraBold.

![image](https://user-images.githubusercontent.com/10059282/112486996-1193d580-8d85-11eb-8ce5-4b3727477fbc.png)
Next I removed all installed fonts from and setup new ones (14 fonts)

![image](https://user-images.githubusercontent.com/10059282/112487046-19ec1080-8d85-11eb-811b-18ab4398b558.png)
And works as expected.

This archive will be understand by windows correctly, by creating Regular + 15 weights only.
[Rubik-SemiBold-ExtraBold-Windows-Fix.zip](https://github.com/google/fonts/files/6205289/Rubik-SemiBold-ExtraBold-Windows-Fix.zip)

Just to reproduce issue, I will setup now one more Rubik-SemiBold from Google.
![image](https://user-images.githubusercontent.com/10059282/112487655-9252d180-8d85-11eb-8835-fc84eb82a844.png)

Just for test here is VF:
![image](https://user-images.githubusercontent.com/10059282/112488666-6edc5680-8d86-11eb-84e3-bbe13b863755.png)
Rubik-Italic-VariableFont_wght.ttf + Rubik-VariableFont_wght.ttf

So here is a bug :)

**Comment by rent-a-judith** [comment] 2021-03-29 08:51
Hi @romzes2 I'm experiencing the same issue with Manrope font. How can I change the font weight name like you did so that the font is recognized correctly by Windows?

**Comment by romzes2** [comment] 2021-03-29 08:59
> Hi @romzes2 I'm experiencing the same issue with Manrope font. How can I change the font weight name like you did so that the font is recognized correctly by Windows?

https://fontforge.org/en-US/
CTRL+SHIFT+F
- PS NAMES
- OS-2
- TTF Names
CTRL+SHIFT+G ignore validation.

Not sure, that your font has same issue.

**Comment by rent-a-judith** [comment] 2021-03-29 09:21
> > Hi @romzes2 I'm experiencing the same issue with Manrope font. How can I change the font weight name like you did so that the font is recognized correctly by Windows?
> 
> https://fontforge.org/en-US/
> CTRL+SHIFT+F
> 
> * PS NAMES
> * OS-2
> * TTF Names
> 
> CTRL+SHIFT+G ignore validation.
> 
> Not sure, that your font has same issue.

Thank you I will try Font Forge. When I install Manrope and Inter (both Google fonts) my Windows recognizes them as follows: 
![Screenshot 2021-03-29 111809](https://user-images.githubusercontent.com/30658374/112815588-c2012280-9080-11eb-9b27-bcdef6127a48.png)

It's so frustrating. Have contacted Windows support twice and they haven't been able to suggest a fix.

**Comment by m4rc1e** [comment] 2021-03-29 10:09
Use the fonts provided in the static directory. You're currently using the variable fonts which are not fully supported in DTP apps yet.

**Comment by rent-a-judith** [comment] 2021-03-29 10:20
> Use the fonts provided in the static directory. You're currently using the variable fonts which are not fully supported in DTP apps yet.

Have tried the static fonts, same problem still happens.

**Comment by romzes2** [comment] 2021-03-29 12:56
> > Use the fonts provided in the static directory. You're currently using the variable fonts which are not fully supported in DTP apps yet.
> 
> Have tried the static fonts, same problem still happens.

There are multiple problems with Manrope, since the thread is about the Rubik, I will not describe them.
[Manrope-fix.zip](https://github.com/google/fonts/files/6221805/Manrope-fix.zip)
@rent-a-judith I recommend to create another thread next time, this will help preform correct development.

**Comment by thlinard** [comment] 2021-03-29 13:06
1. Rubik: in the static files, there is a SemiBold weight and an ExtraBold weight (+ italics), while these weights aren't in the named instances of the VF. That the named instances of a VF don't match the static fonts must indeed be troubling to most people.
2. Manrope: duplicate of #3267.

**Comment by rent-a-judith** [comment] 2021-03-29 13:16
> > > Use the fonts provided in the static directory. You're currently using the variable fonts which are not fully supported in DTP apps yet.
> > 
> > 
> > Have tried the static fonts, same problem still happens.
> 
> There are multiple problems with Manrope, since the thread is about the Rubik, I will not describe them.
> [Manrope-fix.zip](https://github.com/google/fonts/files/6221805/Manrope-fix.zip)
> @rent-a-judith I recommend to create another thread next time, this will help preform correct development.

Will do, and many thanks for the help. Before seeing this reply I eventually downloaded the .otf Manrope files from here https://github.com/sharanda/manrope/tree/master/fonts/otf and they seemed to work okay

**Closed** 2021-04-27 15:37 UTC
Labels: - Needs confirmation, z_Rubik
