### ISSUE TITLE
Oswald - extra space after single quote

### ISSUE THREAD

**Issue by gemmadallman** [google/fonts#1026] opened 2017-06-01 11:52 UTC
We use Oswald on our website as our headline font: https://prostatecanceruk.org/

Whenever we use a single quote/apostrophe, extra padding/space is added after it:

eg https://prostatecanceruk.org/
![apostrophe space](https://cloud.githubusercontent.com/assets/29120616/26678197/4aec019e-46c7-11e7-9ad5-9feefe62a62c.PNG)

eg https://prostatecanceruk.org/about-us/news-and-views/2016/10/one-fans-record-breaking-return-journey-through-english-football-to-fight-prostate-cancer
![news headline](https://cloud.githubusercontent.com/assets/29120616/26678542/e45c4694-46c8-11e7-9b10-e35a5163e86e.PNG)

It seems to be a problem across the different weights:
![oswald examples](https://cloud.githubusercontent.com/assets/29120616/26678495/b1bab252-46c8-11e7-8f4f-5ef7f7de8667.PNG)

Any help would be very much appreciated!

**Comment by davelab6** [comment] 2017-06-02 04:47
@m4rc1e this seems to be a problem in the pending update too...

**Comment by davelab6** [comment] 2017-09-22 02:47
Reconfirmed

<img width="484" alt="screen shot 2017-09-21 at 22 47 24" src="https://user-images.githubusercontent.com/261579/30727376-da73cfe0-9f1e-11e7-8d11-422e17b241f8.png">

**Comment by kalapi** [comment] 2017-09-22 05:01
Was this down sampled from 2048 to 1000 rpm at some point? Kerning seems to have rounding errors. Fixing the source now and pushing it upstream. Will open pull request once i'm done.

**Comment by kalapi** [comment] 2017-09-22 06:52
@m4rc1e Pull request opened [here](https://github.com/googlefonts/OswaldFont/pull/5). I'm guessing @davelab6 will have to merge.

**Comment by m4rc1e** [comment] 2017-10-30 14:08
This will be fixed in #1289

![screen shot 2017-10-30 at 14 07 54](https://user-images.githubusercontent.com/7525512/32175098-be153020-bd7b-11e7-829d-5f29131b3d74.png)

**Comment by davelab6** [comment] 2017-10-30 16:21
Fixed in https://github.com/google/fonts/pull/1289

**Closed by davelab6** 2017-10-30 16:21 UTC
Labels: Priority 1 - Quick or Urgent but not Important, z_Oswald
