### ISSUE TITLE
Playfair Display upright has Ы components in wrong order

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1172] opened 2017-08-28 15:54 UTC
![screen region 2017-08-28 at 11 53 42](https://user-images.githubusercontent.com/10780161/29781554-918b65bc-8be7-11e7-8b31-52e48008e61f.png)

The upstream source files have this fixed. Looks like we can just pull it in.

**Comment by davelab6** [comment] 2017-08-28 18:14
Duplicate of https://github.com/google/fonts/issues/7

**Closed by davelab6** 2017-08-28 18:14 UTC
Labels: Priority 0 - Urgent and Important
