### ISSUE TITLE
Unpublished fonts 2

### ISSUE THREAD

**Issue by asantewa** [google/fonts#2231] opened 2019-10-31 21:34 UTC
Some more unpublished fonts for consideration:
Nikukyu, Mplus1p, Myanmar sans, Carrios Gothic, Carrios Gothic SC, Karla Tamil Incline, Karla Tamil Upright, Lao Muangdon, Lao Muangkhongnot, Paduak, Jeju Gothic, Jeju Hallasan, Jeju Myeongjo, Kokoro, Phetsarath, Souliyo, Thabit, Redacted, Strong, Bruno Ace, Abyssincasil, Varta, and Bhavuka.

**Comment by RosaWagner** [comment] 2021-03-16 14:07
Duplicate of #2187

**Closed by RosaWagner** 2021-03-16 14:07 UTC
