### ISSUE TITLE
Update Montserrat on Google Fonts website

### ISSUE THREAD

**Issue by runn1ng** [google/fonts#86] opened 2015-07-27 15:36 UTC
On Google Fonts website, there are only two weights of Montserrat font - Normal and Bold

https://www.google.com/fonts/specimen/Montserrat

I have written to the author and she wrote that a new version with more weights was already submitted to you. Citing her mail:

> The true is: I gave to Google fonts the Light and Hairline version (also the Black). But they didn't publish yet.
> What you see, and what you can get in some platforms is a font with mistakes. We were working a lot of time fixing things...
> I don't know why Google is so delayed with the publishing...

Also, on this very repository, you have more weights

https://github.com/google/fonts/tree/master/ofl/montserrat

Why are they not yet on Google Fonts website?

**Comment by davelab6** [comment] 2015-07-27 16:02
The reason for the delay is that updating high-profile fonts like this requires care not to include unwanted changes, and currently only I am responsible for making updates, and my core role is about bringing in new non-latin fonts this year, so updating this latin font is not high on my todo list and takes time.

**Comment by runn1ng** [comment] 2015-07-27 16:44
OK. I just wanted to let you know and didn't know if it was a mistake, etc.

**Comment by davelab6** [comment] 2015-07-27 17:13
The designer has continued working on the family, its at https://github.com/JulietaUla/Montserrat/ with 9 weights :)

**Comment by davelab6** [comment] 2015-07-27 17:13
Closing as duplicate of #2

**Closed by davelab6** 2015-07-27 17:13 UTC

**Comment by 4ants** [comment] 2016-09-13 17:20
+1

**Comment by nsoftproject** [comment] 2016-09-13 17:54
+1

**Comment by davidprati** [comment] 2016-09-23 15:05
+1

**Comment by nikkialgar** [comment] 2016-10-03 14:21
+1

**Comment by moahmo** [comment] 2016-10-03 14:43
+1

**Comment by Pandzinho** [comment] 2016-10-03 14:43
+1

**Comment by fitojb** [comment] 2016-10-04 21:15
Please everyone stop the ridiculous “+1” comment spam.

**Comment by galicante** [comment] 2016-10-05 11:17
+1

**Comment by kodujeme** [comment] 2016-10-10 22:35
+1

**Comment by somecallmejosh** [comment] 2016-10-12 21:07
👍

**Comment by anoosurf** [comment] 2016-10-26 14:34
+1
looking for light font

**Comment by fzzle** [comment] 2016-11-12 00:12
+1

**Comment by fgiust** [comment] 2016-11-14 18:38
+1

**Comment by cballou** [comment] 2016-11-18 14:33
+1

**Comment by coding-warehouse** [comment] 2016-11-28 02:04
+1

**Comment by m4rc1e** [comment] 2016-11-28 09:22
The [Montserrat](https://github.com/JulietaUla/Montserrat) sources are currently being [improved](https://groups.google.com/forum/#!topic/googlefonts-discuss/MIq0No6BXQI). We'll wait for the improvements to be completed first.

**Comment by mgan59** [comment] 2016-12-02 16:30
PLEASE FIX!!! 😄  Just spent an hour with our designer trying to figure out why the fonts weren't working on the marketing site only to track it down all the way to GoogleFont's missing the weights.

Thanks 👍

**Comment by podrivo** [comment] 2016-12-03 19:14
+1

**Comment by meneldil** [comment] 2016-12-05 16:38
+1

**Comment by Lionel-Daelemans** [comment] 2016-12-12 15:14
+1

**Comment by SpencerCDixon** [comment] 2016-12-12 17:17
+1 for light

**Comment by joepolask86** [comment] 2016-12-16 13:36
+1

**Comment by sebastiaanluca** [comment] 2016-12-16 13:38
Please just thumbs up the intro post. I'd like to get notified when the issue has been resolved, not get a "+1" mail in my inbox every other day :)

**Comment by ericsantos** [comment] 2016-12-22 17:07
+1

**Comment by robasaad** [comment] 2016-12-29 19:40
+1

**Comment by sr3d** [comment] 2017-01-03 23:56
+1 for this.  Currently even the "Regular" Montserrat is too bold for regular text.  For a project that has such high impact, Google Fonts team could really dedicate a little more resource to keep things going faster.

**Comment by leolll** [comment] 2017-01-25 02:50
+1

**Comment by giuvax** [comment] 2017-02-09 08:54
Is Google making updates right now, by chance?
This morning when I opened my website I found something weird. Montserrat seem streched. I noticed that the author uploaded some updated fonts just two days ago. Maybe Google is updating theirs?

**Comment by jcarnevale89** [comment] 2017-02-09 15:26
@giuvax I also experienced the same thing on all of my sites. A bunch of font weights were different

**Comment by samasq2** [comment] 2017-02-09 15:48
Same thing here, Montserrat has been fine on my website for over a year. Today it looks a lot lighter and more stretched, and on the official google font page many more weights are available than a few months ago.
I wish google would put a notification on the font page when they are updating it, been pulling my hair out trying to find out why my site has changed today!

**Comment by m4rc1e** [comment] 2017-02-09 15:59
@samasq2 @jcarnevale89 @giuvax We updated [Montserrat](https://github.com/JulietaUla/Montserrat) to the latest v.6001 version. Previously, Montserrat was not a Multiple Master based font and only came in Regular and Bold. The design has been updated so we could offer more styles. I'm assuming this is where the rounding/stretching is coming from.

It's very much a balancing act with these things. We have people who want the latest possible, #130 and those like yourselves who're suffering the consequences of an update.

**Comment by jcarnevale89** [comment] 2017-02-09 16:04
@m4rc1e No worries at all. I also noticed more font styles were added to the google fonts page. Thank you for the update and the quick response. Adding these new font weights to my sites isn't a big deal! Thank you!

**Comment by samasq2** [comment] 2017-02-09 16:12
@m4rc1e Thanks for the update, the new weights look good.

**Comment by m4rc1e** [comment] 2017-02-09 16:14
@samasq2 thank @JulietaUla @juandelperal @kalapi and many others who all contribute to the source [repo](https://github.com/JulietaUla/Montserrat)

I'm just a messenger.

**Comment by Andrew-Fam** [comment] 2017-02-10 04:20
Hi guys, as others have mentioned before, the regular weight (400) looks stretched vertically especially at smaller font-size, which in our case is 14 px. Can anyone verify whether this is a bug with the update, a flaw in the design that will be rectified in the future, or is it by design and will remain unchanged?

**Comment by ponny** [comment] 2017-02-10 04:47
Are we able to somehow get the old version of the font?  I don't seem to be able to adjust the weights to look they way they used to.

**Comment by giuvax** [comment] 2017-02-10 08:05
Thanks for info. As a matter of fact I've been able to reset everything as before, except the regular one. Like @Andrew-Fam I have some tables with very small regular font and now the effect is stretched. The regular / 400 is changed or maybe it's just rendering different but I hope it will get back as it was before because they just had to add some variants. The original one shouldn't be modified.

**Comment by Knittchen** [comment] 2017-02-10 08:36
@giuvax @ponny @Andrew-Fam @samasq2 @jcarnevale89 In case you want the old style:

- go to http://www.1001freefonts.com/montserrat.font 
- download
- unzip the file Montserrat-Regular.ttf to a src folder of your Website
- create a font-face in your css files

 ```
@font-face {
    font-family: 'Montserrat';
    src:  url('../font/Montserrat-Regular.ttf') format('opentype');
}
```

Hope that helps,
kind regards.

**Comment by giuvax** [comment] 2017-02-10 08:37
@Knittchen Thanks!! I'm going to try right now.

**Comment by giuvax** [comment] 2017-02-10 08:45
Well, it's quite different. Here attached you see the new and the old version. Note that in the table the third column is still with new version. It's really different.
![montserrat new version](https://cloud.githubusercontent.com/assets/25658673/22820118/af34a948-ef75-11e6-8937-c685b5315cce.jpg)
![montserrat old version](https://cloud.githubusercontent.com/assets/25658673/22820119/af363664-ef75-11e6-858b-fd8192207cc8.jpg)

**Comment by undfnd** [comment] 2017-09-18 11:03
Hello,

What happened with the Montserrat font since the update of styles? Now it looks very ugly, at least the old bold style is horrible now :(

![montserrat_font](https://user-images.githubusercontent.com/8759488/30539167-d9a2f020-9c79-11e7-9617-863c6614118f.png)

This font used to be my favorite one, now ..... bleah

**Comment by davelab6** [comment] 2017-09-20 22:11
> What happened with the Montserrat font since the update of styles? Now it looks very ugly, at least the old bold style is horrible now :(

This is likely because ttfautohint hinting (only seen on Windows) raises the x-height at small sizes by default, to improve legibility. 

In the next update, this can be correct to have the more square proportions of before. 

@m4rc1e we should be catching these changes...

**Comment by m4rc1e** [comment] 2017-09-21 09:16
@davelab6 I'm also certain ttfautohint also produces different results with each update.

**Comment by davelab6** [comment] 2017-11-14 18:42
@m4rc1e I would really like to get control over ttfautohint x height regressions :)
