### ISSUE TITLE
Oswald changed height and weight with recent update

### ISSUE THREAD

**Issue by martinml** [google/fonts#645] opened 2017-02-09 17:53 UTC
A picture is worth a thousand words (click for full size!):

![oswald](https://cloud.githubusercontent.com/assets/217925/22795750/15b1b220-eef8-11e6-87a1-1171a6d20f15.gif)

This is elotrolado.net. We're using weights 300 and 400. I'm used to see the old Oswald so I might be biased or even wrong, but I think it looked better before. I understand this is a subjective issue and there might not be any bugs, but just in case I'm reporting the difference.

**Comment by m4rc1e** [comment] 2017-02-09 18:12
Thanks for the before and after.

I'm guessing this may have been a design decision.

![screen shot 2017-02-09 at 18 02 42](https://cloud.githubusercontent.com/assets/7525512/22796416/1d778e04-eef2-11e6-84d8-2407037865f9.png)
**left: Oswald New | right: Oswald Old**

New Ascender: 810
Old Ascender 875

Oswald by design is a very tall font. Here's a comparison with Overpass.

![screen shot 2017-02-09 at 18 05 56](https://cloud.githubusercontent.com/assets/7525512/22796508/7b283b02-eef2-11e6-873f-626767a5fbc5.png)
**left: Overpass | center: Oswald New | right: Oswald Old**

Overpass Ascender:700
New Ascender: 810
Old Ascender 875

@kalapi was the design decisions influenced by this post? https://groups.google.com/d/msg/googlefonts-discuss/W4PHxnLk3JY/fx_LOIQqAwAJ

**Comment by davelab6** [comment] 2017-02-09 19:32
@martinml thanks for reporting this!

Last year @kalapi reworked the whole Oswald family to finalize the work in progress that was very sadly left unfinished by the original designer (www.sansoxygen.com has the full tragic story) and this work included adding support for many more weights and also languages, including Vietnamese, which required a slight reduction in the body of the type, while keeping the vertical metrics the same. 

When updating fonts we try to keep as much the same as possible while making it better.

**Comment by davelab6** [comment] 2017-02-09 19:33
I'm closing the issue but feel free to continue to discuss :)

**Closed by davelab6** 2017-02-09 19:33 UTC

**Comment by martinml** [comment] 2017-02-10 09:25
Thanks both of you for the fast reply. I was afraid it was something like that, just wanted to be sure. Such a sad story :(

Google Fonts doesn't have a way to serve a specific revision of a font, does it? If not, I guess I can rehost the old version myself: I've getting complaints from the users lately that the site "looks weird". I wasn't seeing it because I had the font installed locally (that's how I did the comparison), but there's definitely a difference that in our case somehow works for the worse: many of the sizes of the elements, especially heights, were designed with the original font size in mind (see the right sidebar titles for example).

**Comment by fitojb** [comment] 2017-02-11 00:44
I don’t think the new version looks “weird”; in fact, it’s now more readable IMHO… Why can’t you just adjust the font size with CSS?

**Comment by davelab6** [comment] 2017-02-11 18:44
Users often complain when fonts they habitually see are changed, no matter
what the change is. It's called "change aversion" by perceptual
psychologists.

Increase the CSS font-size value should mitigate this.

The old font has bugs, and if you want to live with them, you are free to
do so :)
