### ISSUE TITLE
Montserrat design structure flawed – not outlining correctly

### ISSUE THREAD

**Issue by AmberViking** [google/fonts#5370] opened 2022-10-05 10:27 UTC
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts in this repository: https://github.com/googlefonts/noto-fonts/issues.

**Describe the bug**
I am using Adobe Illustrator® and have found that the Montserrat font has an issue when outlining or adding a stroke to the font. It would appear that the construction of the vectors in the font has been poorly executed and doesn't utilize compound paths to build the characters. I have checked the font using FontLab v8 for Mac and all characters in the font set display the same attributes. I have attached screenshots to illustrate the issue.

**To Reproduce**
Type some text, then outline the font.

**Expected behavior**
Outlining a font should not produce these results

**Screenshots**
<img width="832" alt="Screenshot 2022-10-05 at 11 24 54" src="https://user-images.githubusercontent.com/115076688/194039175-8011d9fa-caee-47d7-b364-acc748d945ba.png">
<img width="647" alt="Screenshot 2022-10-05 at 11 21 02" src="https://user-images.githubusercontent.com/115076688/194039184-ed02a566-92ea-4785-b1ad-8c8f0e5f5c16.png">

**Additional context**
Adobe Illustrator® v26.5
MacOS 12.6
Montserrat Black v8.00

**Comment by RosaWagner** [comment] 2022-10-05 10:45
Hi, thanks for your report. This is not a bug, and these are not poorly executed outlines. This is necessary for the variable fonts to interpolate correctly. Although, Adobe could bring an option that allow this use of variable fonts in their software, on this I agree.

To resolve your issue I would recommend to download [the static version of the font in the upstream repository](https://github.com/googlefonts/Montserrat/tree/master/fonts/ttf). They do have merged outlines there.

Otherwise in Indesign, you can add a white background to the letters, it will make the inner outlines disappear if the added contour is "outside".

If you are interested in outline quality, GF Guide has an entire subject dedicated to the matter: 
https://googlefonts.github.io/gf-guide/outlines.html

Closing since this is not a GF issue.

**Closed** 2022-10-05 10:45 UTC
Labels: I Font Bug
