### ISSUE TITLE
Unbounded SVG Generation Bug

### ISSUE THREAD

**Issue by charlieforward9** [google/fonts#6146] opened 2023-03-31 08:52 UTC
**Describe the bug**
Generating a SVG trace with the Unbounded font results in overlapping geometries and color gaps.

See [source issue](https://github.com/danmarshall/google-font-to-svg-path/issues/40)

**To Reproduce**
Go to [the Gfont->SVG site](https://danmarshall.github.io/google-font-to-svg-path), switch the font to Unbounded, and take note of the rending errors.

**Expected behavior**
Solid fill on all characters for all default settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/62311337/229073592-4c695b6f-bb44-49f7-ba0a-e35ffccc006f.jpeg)

**Comment by anthrotype** [comment] 2023-03-31 09:27
here's the Regular with overlaps removed as explained above, then manually uploaded to the google-font-to-svg-path site:

![image](https://user-images.githubusercontent.com/6939968/229081836-7d060df6-8e32-4085-803c-659889ad8ab7.png)

**Comment by RosaWagner** [comment] 2023-03-31 13:36
Hi @charlieforward9, thanks for reporting, but indeed this is not a bug from the font. This platform should implement better support of Variable font following @anthrotype recommendations :)

In the meanwhile you can use the statuc fonts from the deigner's repository, in the directory `fonts/ttf`. In general those are having merged outlines: https://github.com/googlefonts/unbounded

**Closed by RosaWagner** 2023-03-31 13:36 UTC
Labels: I Font Bug

**Comment by charlieforward9** [comment] 2023-03-31 16:53
Thank you to both of you for the detailed explanation! I'll keep the conversation going in the linked issue.
