### ISSUE TITLE
Add Iosevka

### ISSUE THREAD

**Issue by be5invis** [google/fonts#559] opened 2016-12-29 22:47 UTC
https://github.com/be5invis/Iosevka

**Comment by davelab6** [comment] 2016-12-30 20:12
Thanks for filing this, I'll run this by the Google Design review board soon :)

**Comment by be5invis** [comment] 2016-12-31 23:59
@davelab6 Options:

- Build from source vs. grab the files in `releases`;
- If you decide to build from source, the styles being provided;
- Include Inziu Iosevka;

**Comment by be5invis** [comment] 2017-02-10 06:05
@davelab6 Any progress?

**Comment by davelab6** [comment] 2017-02-10 18:47
@be5invis I can't comment on the schedule, but it will be added soon! :)

**Comment by be5invis** [comment] 2017-04-04 10:36
@davelab6 ……Is it being rejected?

**Comment by kaushalmodi** [comment] 2017-08-03 18:32
Please add this font, looking forward to it.

**Comment by kaushalmodi** [comment] 2017-10-25 14:53
@davelab6 Any update on this please?

**Comment by davelab6** [comment] 2017-11-25 18:33
We should add this soon or we'll lose it

https://mobile.twitter.com/belleveinvis/status/934471141241921536

**Comment by vatula** [comment] 2018-01-07 01:18
This has being going for more than a year now and the only response within that whole year was "soon". Is there any actual ETA for this?

**Comment by be5invis** [comment] 2018-01-12 00:31
You have delayed it for about one YEAR.
**What happened?**

**Comment by vatula** [comment] 2018-01-12 00:38
@davelab6 please comment above when you have some time

**Comment by be5invis** [comment] 2018-01-12 10:47
@davelab6 
You know, Iosevka is a huge family with millions of possible variants...
It is preferred that, you publish these subfamilies only:

 - Iosevka
 - Iosevka Slab
 - Iosevka Term
 - Iosevka Slab Term

The "Type" and "CC" subfamily is made for special purposes (like "Type" is originally made for CoqIDE), for a general website providing webfonts, they are not needed to be provided.

**Comment by HoweChen** [comment] 2018-02-26 10:12
Looking forward to Iosevka on Google Font

**Comment by thepheer** [comment] 2018-08-24 05:57
👀

**Comment by JUSTIVE** [comment] 2018-09-03 01:46
👀

**Comment by rnetonet** [comment] 2018-11-15 01:14
:eyes:

**Comment by asm0dey** [comment] 2019-01-04 21:54
Iosevka can be built in lots of variations. And it can be easily built as woff2, which will be perfect for just uploading to Google Fonts Directory. For me it's crucial to have ability to use ligatures on slides…

Can't wait for it to be added.

**Comment by richardanaya** [comment] 2019-05-08 23:43
👀

**Comment by doersino** [comment] 2019-06-07 11:19
👀

**Comment by pvinis** [comment] 2019-08-27 20:00
*👀 intensifies*

**Comment by qwhex** [comment] 2019-09-26 17:16
👀👀

**Comment by pvinis** [comment] 2019-09-26 18:37
What is needed here?

**Comment by qwhex** [comment] 2019-09-29 14:23
@pvinis more eyes on this thread

**Comment by balzss** [comment] 2019-09-29 14:25
👀

**Comment by xbelanch** [comment] 2019-10-28 19:19
👀

**Comment by mosino** [comment] 2019-11-13 19:07
Almost two years and still nothing? How much work can it be...?

**Comment by pvinis** [comment] 2019-11-14 15:21
The problem is that we don't even know what's needed. Until then, I use this https://github.com/pvinis/iosevka-webfont like https://github.com/pvinis/pvinis-web/blob/727c9ba567c7bd23f8cf011f4674493d75abec41/packages/blog/src/components/seo.js#L41.

**Comment by qwhex** [comment] 2019-11-27 16:57
@pvinis 
Thanks for the tip!

**Comment by davelab6** [comment] 2019-11-30 17:35
The typeface designer asked us to hold off from publishing it.

**Comment by be5invis** [comment] 2019-11-30 19:46
I am working on 3.0 that is a _major_ change (i.e., make strokes straight by default).
I may publish that soon after holiday.

**Comment by pvinis** [comment] 2019-12-02 15:23
Good to know, thanks to both of you :)

**Comment by SteeleDynamics** [comment] 2020-01-16 13:58
Patiently waiting for this font.  Excited to see version 3.0!

**Comment by SteeleDynamics** [comment] 2020-01-16 13:58
Patiently waiting for this font. Excited to see version 3.0!

**Comment by vjeffz** [comment] 2020-05-19 08:27
https://github.com/be5invis/Iosevka/releases

**Comment by merrychap** [comment] 2021-03-18 17:59
Any progress guys?

**Comment by yohgen** [comment] 2021-05-25 15:21
👀 👀 👀

**Comment by pvinis** [comment] 2021-06-01 09:15
Yup.. I'm still using my own [thing](https://github.com/pvinis/iosevka-webfont). Some other people too.

**Comment by thiagowfx** [comment] 2021-09-20 16:10
What are the needed steps to perform this? I could try to help here.

**Comment by tiagorangel2011** [comment] 2021-12-28 17:16
Nothing, after almost 6 years!

**Comment by aarav2you** [comment] 2022-03-20 11:14
Still nothing!

**Comment by Diablo-D3** [comment] 2022-04-21 19:43
Is this coming at some point? Iosevka is a pretty popular font, shame it's missing.

**Comment by pinpox** [comment] 2022-05-27 14:40
Hello, does anyone even read these issues?

**Comment by pvinis** [comment] 2022-05-28 05:33
maybe we can use this template to make it a bit easier?

https://github.com/google/fonts/blob/0084da2c1f364d4f04b9ac1982d8f63025442f6b/.github/ISSUE_TEMPLATE/1_add-font.md

we can edit the top comment or make a new issue?

**Comment by pinpox** [comment] 2022-05-29 12:45
> maybe we can use this template to make it a bit easier?
> 
> https://github.com/google/fonts/blob/0084da2c1f364d4f04b9ac1982d8f63025442f6b/.github/ISSUE_TEMPLATE/1_add-font.md
> 
> we can edit the top comment or make a new issue?

I created a new issue according to the template: https://github.com/google/fonts/issues/4728 

But I'm not sure about some of the requirements listed there, maybe someone can look over it and tell me if I missed something.

**Comment by RosaWagner** [comment] 2022-09-29 14:28
Closing this issue since another one has been opened using the nice template. cf #4728

**Closed by RosaWagner** 2022-09-29 14:28 UTC
Labels: -- Needs manager's opinion, - Ready for Review, I New Font, II Submission
