### ISSUE TITLE
Lato missing glyphs

### ISSUE THREAD

**Issue by zodiac9797** [google/fonts#46] opened 2015-06-03 13:19 UTC
Lato is missing some latin-extended glyphs:
U+010C	Č
U+010D	č
U+0110	Đ
U+0111	đ

Any chance of fixing this issue?

![lato_font](https://cloud.githubusercontent.com/assets/12731488/7960849/ddb9b348-0a03-11e5-8034-737f4229bb62.jpg)

**Comment by tuankiet65** [comment] 2015-06-06 07:55
The issue is that Google Fonts is still using Lato 1.0. Lato 2.0 has those glyphs but it looks like Google won't update to v2 soon

There's an issue for that#6.

**Comment by rsheeter** [comment] 2015-06-11 20:01
Thank you for the report. I am closing this as #6 should suffice for tracking the issue.

**Closed by rsheeter** 2015-06-11 20:01 UTC

**Comment by kovinet** [comment] 2023-10-30 16:48
There is still no č whe using this font on Google Fonts. When will this be deployed?
