### ISSUE TITLE
Issue with italic characters of Roboto Mono

### ISSUE THREAD

**Issue by erusev** [google/fonts#160] opened 2015-12-08 13:08 UTC
The italic characters of Roboto Mono seem to be narrower than the regular and bold characters. Texts "shrink" when converted from regular to italic.

Here's a screenshot that should demonstrate the issue: 
![image](https://cloud.githubusercontent.com/assets/184170/11656350/33fc1fc8-9dbd-11e5-85ef-b63fac61d956.png)

**Comment by davelab6** [comment] 2015-12-08 20:10
This is a known issue. Thanks for reporting. I hope it will be addressed in a future update.

**Comment by erusev** [comment] 2015-12-08 20:24
Thanks, @davelab6, I look forward to it.

**Comment by davelab6** [comment] 2016-05-23 23:24
Closing as duplicate of https://github.com/google/fonts/issues/142

**Closed by davelab6** 2016-05-23 23:24 UTC
Labels: development request
