### ISSUE TITLE
Broken Arabic shaping in Vibes font

### ISSUE THREAD

**Issue by khaledhosny** [google/fonts#2612] opened 2020-08-10 00:43 UTC
The web font (as shown on the website) show Arabic letters disjoined (unusable), but the downloaded font is fine.

Web font:
![image](https://user-images.githubusercontent.com/93914/89745273-08365100-dab3-11ea-9245-83bc374dffb5.png)

Downloaded font:
![image](https://user-images.githubusercontent.com/93914/89745280-1be1b780-dab3-11ea-9ad4-6725ae131a72.png)

**Comment by khaledhosny** [comment] 2020-08-10 00:45
The same is happening with Aref Ruqaa, all other Arabic fonts seems fine.

**Comment by khaledhosny** [comment] 2020-08-10 00:51
And Jomhuria as well.

Seems to affect the website only, though. Test HTML pages loading the fonts from Google Fonts render fine.

**Comment by garretrieger** [comment] 2020-08-17 22:56
Thanks for the report. We're testing using harfbuzz subsetting for a small number of families and it was misconfigured and is currently dropping layout tables. This only effects dynamic subsetting (ie. /css?...&text=abc type requests). I'm working on a fix right now.

**Comment by khaledhosny** [comment] 2020-08-18 02:30
Thanks!

**Comment by garretrieger** [comment] 2020-08-20 23:09
This should be fixed now.

**Comment by garretrieger** [comment] 2020-08-24 20:18
Can you check https://codepen.io/garretrieger/pen/ExKNOQx again? I've rev'd the version of Vibes. That will ensure you're not getting a stale copy of the subset from a cache somewhere along the way.

**Comment by khaledhosny** [comment] 2020-08-24 23:57
This works, thanks. There seem to be a difference in spacing, though, the two lines are not the same length.

**Comment by khaledhosny** [comment] 2020-08-25 00:03
The spacing difference seems to be because space glyph is taken from a different font because of the ` unicode-range` in the FonTools `@font-face` rules (`unicode-range` Is Considered Harmful™, but that is a different issue).

**Comment by garretrieger** [comment] 2020-08-25 00:06
Great, I'll rev the version on the other affected families as well.

**Comment by khaledhosny** [comment] 2020-09-24 14:57
More fonts are broken now (e.g. Amiri), but different from how they were broken before. Basic shaping is happening, but other than that OpenType layout seems to be broken.

**Comment by garretrieger** [comment] 2020-09-24 17:25
Amiri was just switched over to harfbuzz for dynamic subsetting, so looking into what's changed in the subsetting result.

**Comment by garretrieger** [comment] 2020-09-24 18:45
Looks like some ChainContextPos lookups are getting dropped in the harfbuzz version. I'm looking into the cause.

**Comment by khaledhosny** [comment] 2020-09-24 18:53
I’m seeing also missing contextual substitution:
![image](https://user-images.githubusercontent.com/93914/94187039-b81b1e80-fea7-11ea-8390-26db022ca2e6.png)

It should be like this (which I got by changing `Amiri script=arabic rev=1` to `Amiri script=all rev=1`):
![image](https://user-images.githubusercontent.com/93914/94187141-d41ec000-fea7-11ea-8b9b-fbc4b1076c6b.png)

**Comment by garretrieger** [comment] 2020-09-24 19:04
In the meantime I'm reverting the switch to harfbuzz for any families with ChainContextPos/Sub rules.

**Comment by garretrieger** [comment] 2020-09-25 02:08
The revert is complete, that should fix things for now while I investigate the cause in harfbuzz.

**Closed by garretrieger** 2020-09-25 02:08 UTC

**Comment by khaledhosny** [comment] 2020-09-25 09:13
All seems fine now, thanks!
