### ISSUE TITLE
Google fonts

### ISSUE THREAD

**Issue by 21jhez2003** [google/fonts#7506] opened 2024-04-01 16:30 UTC
#This issue also works for requesting features. 

**Describe the issue**
The issue of Google fonts is i don't have "Select this style with + in the circle

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

**Screenshots**

**Comment by 21jhez2003** [comment] 2024-04-01 16:32
![Screenshot (20)](https://github.com/google/fonts/assets/116240466/a2cb7cba-865e-43c9-9f04-5a14425f9c3b)

**Comment by applecuckoo** [comment] 2024-04-01 21:35
Duplicate of issue #7166. You click the big blue 'get font' button, then the bag icon, then the 'Get embed code' button to select individual styles.

**Comment by davelab6** [comment] 2024-05-10 15:36
Thanks @applecuckoo

**Closed by davelab6** 2024-05-10 15:36 UTC
Labels: I Tools / workflow / repo, I API / Website / Platform, I Request
