### ISSUE TITLE
Fira Code does not download on Chrome 79.x on Windows only

### ISSUE THREAD

**Issue by hmemcpy** [google/fonts#2328] opened 2020-02-02 21:20 UTC
I noticed that my blog wasn't rendering the monospaced font correctly on Windows, and I noticed that I get a lot of warnings about it failing to download Fira Code:
![image](https://user-images.githubusercontent.com/601206/73615628-52291080-4612-11ea-8005-74e67586b4ec.png)

It works fine in Chrome/Brave on macOS, does not work on Windows. It does, however, work on Edge (Chromium 70) on both Windows and Mac.

I asked on twitter, and many folks confirm they get the same error in Chrome on Windows.
I'm using Brave version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit) if that helps

I managed to reproduce this on codepen: https://codepen.io/hmemcpy/pen/OJPKxLJ

macOS |  Windows
:--------------:|:---------------:
<img src=https://user-images.githubusercontent.com/601206/73615742-6f121380-4613-11ea-9b26-e09a695acf0d.png width=400 /> | <img src=https://user-images.githubusercontent.com/601206/73615754-881ac480-4613-11ea-83d7-cd9934ebfd10.png width=400 />

**Comment by rsheeter** [comment] 2020-02-03 19:44
Thank you for the report. I'm having trouble reproducing. Does this happen reliably for you?

**Comment by sladen** [comment] 2020-02-03 19:51
Hello @hmemcpy 

1. is there by any chance that there is a local copy of the font installed (somewhere) on this particular machine?
2. what does the Network debugging view show; is an HTTP GET occuring; and is the font being re-downloaded (might not be happening if already cached)?
3. What is the file-size + SHA or MD5sum checksum of any downloaded/cached copy?  (ie. is it bit-for-bit identical to a freshly-downloaded copy)

**Comment by hmemcpy** [comment] 2020-02-03 19:54
Hello @sladen, @rsheeter,

Let me get that info for you. But I just tried again in a clean Windows 10 VM with just Chrome (79.0.3945.130 (Official Build) (64-bit)) installed - same thing, I'm afraid :(
![image](https://user-images.githubusercontent.com/601206/73685902-a940eb00-46cf-11ea-8baf-6bb6ac756950.png)

**Comment by sladen** [comment] 2020-02-03 20:03
Re-typed URL from screenshots (ideally confirm copy-and-paste)

* https://fonts.gstatic.com/s/firacode/v7/uU9NCBsR6Z2vfE9ag3bh3dSD.woff2
* https://fonts.gstatic.com/s/firacode/v7/uU9NCBsR6Z2vfE9ag3bh3dSD.woff2
whereas:

* https://fonts.googleapis.com/css?family=Fira%20Code:300,400 returned CSS gives
* https://fonts.gstatic.com/s/firacode/v7/uU9eCBsR6Z2vfE9aq3bL0fxyUs4tcw4W_GNsJV37Nv7g.woff2

`…g3bh3dSD` vs. `q3bL0fxyUs4tcw4W_GNsJV37Nv7g`

**Comment by hmemcpy** [comment] 2020-02-03 20:07
What's interesting, if I request `family=Fira%20Code:300` or `family=Fira%20Code:400`, then I get the correct font rendered fine. When both are used I seem to have the problem. Still working on the hashes, one moment.

**Comment by sladen** [comment] 2020-02-03 20:08
```
ls -sh1 uU9*
20K uU9eCBsR6Z2vfE9aq3bL0fxyUs4tcw4W_GNsJV37Nv7g.woff2
44K uU9NCBsR6Z2vfE9aq3bh3dSD.woff2
```

**Comment by hmemcpy** [comment] 2020-02-03 20:26
Very odd, on my VM I get different sizes:
```
$ ls -sh1 uU*
36K uU9NCBsR6Z2vfE9aq3bh3dSD.woff2
32K uU9eCBsR6Z2vfE9aq3bL0fxyUs4tcw4W_GNsJVD7Ng.woff2
```

If it helps, I used this `curl` command which I copied from the Network tab, to download the font (I'm sure it doesn't really need all the headers, but just in case...):

```
curl -O 'https://fonts.gstatic.com/s/firacode/v7/uU9NCBsR6Z2vfE9aq3bh3dSD.woff2' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36' -H 'Referer: https://fonts.googleapis.com/css?family=Fira%20Code:300,400' -H 'Origin: https://cdpn.io' --compressed
```

Finally, the "broken" font (3dSD) doesn't also render properly in the Preview tab in network. It shows a generic serif font.

I'm sorry, not really a web dev, so not sure what else I can provide to be helpful...

**Comment by rsheeter** [comment] 2020-02-03 20:42
`300,400` is triggering delivery as a variable font whereas for just 300 or just 400 it's smaller as a static instance. I assume https://codepen.io/rs42/pen/QWweXyQ, which declares 300 and 400 to both come from the same src triggers the failure?

**Comment by hmemcpy** [comment] 2020-02-03 20:51
Yes, I get the same failure in your codepen as well in the VM. Interestingly, on my main Windows machine (which has Fira Code TTFs installed locally), it did show the failures, but it did render Fira Code. So I removed the local font, refreshed the page, and got the failed result as well:
<img src=https://user-images.githubusercontent.com/601206/73689784-ae099d00-46d7-11ea-953e-803cfa597188.png width=640/>

**Comment by rsheeter** [comment] 2020-02-03 21:11
https://chromium.googlesource.com/chromium/src/third_party/+/master/blink/renderer/platform/fonts/web_font_decoder.cc#184. Despite the message this may not be OTS.

**Comment by rsheeter** [comment] 2020-02-03 21:53
Appears to be due to a bug in our toolchain that Fira Code triggers, likely only causing an issue on Windows where Chrome tries to use DWrite for variable fonts.

**Comment by rsheeter** [comment] 2020-02-04 05:00
I pushed a fix; could I impose on you to retry? - make sure to flush cache or force refresh and look for a v8 in the Fira Code font path (`https://fonts.gstatic.com/s/firacode/v8/...blah...woff2`)

**Comment by hmemcpy** [comment] 2020-02-04 05:35
I am happy to report that whatever you did - worked! 🎉 I do indeed see v8 on the font path, and it seems to be working. Thank you so much!

**Comment by rsheeter** [comment] 2020-02-04 05:47
Thank you for the report and sorry for the inconvenience.

**Closed by rsheeter** 2020-02-04 05:47 UTC

**Comment by sladen** [comment] 2020-02-04 06:12
/me politely wonders what the root-cause + fix was…
