### ISSUE TITLE
Add Sixtyfour Convergence

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#6980] opened 2023-11-20 06:43 UTC
**Font Project Git Repo URL:** https://github.com/jenskutilek/homecomputer-fonts

**Super short description of the Font Family:** Sixtyfour Color is a colorised version of Home Computer Sixtyfour

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![](https://user-images.githubusercontent.com/106728/275872530-a5cf7c88-cf10-4f09-8a5a-282f0e779da6.gif)

**Comment by vv-monsalve** [comment] 2023-11-21 15:32
Additional steps/requirements for this project

- [ ] Registering the new custom Axis
- [ ] Changing the "Color" bit in the name

**Comment by simoncozens** [comment] 2023-11-21 15:58
I can change the name; I didn't realise "Color" was banned (maybe that should be in the gf-guide?). Can we go with "Retro"? :-)

I'll do an axisregistry issue for XELA.

**Comment by simoncozens** [comment] 2023-11-21 16:03
https://github.com/googlefonts/axisregistry/issues/157

**Comment by vv-monsalve** [comment] 2023-12-02 22:05
> I can change the name; I didn't realise "Color" was banned (maybe that should be in the gf-guide?). Can we go with "Retro"?

I didn't realise it was not included there yet. As a name, `Retro` would be ok, However, the entire concept for the Homecomputer fonts is retro :). Could it be something like "Glitch" or any other term referring to the overlapping/moving color channels happening?

**Comment by vv-monsalve** [comment] 2024-02-06 15:01
@jenskutilek do you have suggestions on the name to replace the `Color` bit? :)

**Comment by jenskutilek** [comment] 2024-03-15 13:09
Maybe "Sync" because it seems to desynchonize the RBG color components? But I think on an actual CRT, as far as I remember correctly, was called "Convergence", which is a bit long.

"Warp"?

I'm fine with "Glitch" too, it is a more general term, but matches the effect :)

**Comment by vv-monsalve** [comment] 2024-03-15 17:17
Due to the tech origin relation, I would love Convergence; however, I wonder how compelling it would be. 

Warp sounds good :) @simoncozens wdyt?

**Comment by simoncozens** [comment] 2024-03-18 13:02
I *love* Convergence.

**Comment by vv-monsalve** [comment] 2024-03-18 18:51
Okay! In that case, let's commit to tech consistency and go with _Convergence_

**Comment by vv-monsalve** [comment] 2024-06-06 18:57
The font is almost ready for the PR. However, the "Convergence" name is reporting a [name length issue](https://github.com/jenskutilek/homecomputer-fonts/issues/53).

Now would be the perfect time to reconsider it for a shorter one. @davelab6 could we continue with it for this particular case?

@jenskutilek, @simoncozens do you think there could be one conceptually as good as Convergence, but shorter?

**Comment by davelab6** [comment] 2024-06-06 19:01
I think just dropping it could work? :)

**Comment by vv-monsalve** [comment] 2024-06-06 19:15
Dropping it is not an option since there is already a "Sixtyfour" font in the catalog. This would be a "color" variant.

`Convergence` is the best conceptual option for the font + axes behavior related to the historical technology involved. It's just a bit long.

Considering this is not a font targeting MSW, I think we could proceed with it. But if a shorter name is definitely required, now is the time to decide on it.

**Comment by davelab6** [comment] 2024-06-06 19:58
Oh oh right. Yes, since MSW isn't really an issue, all good

**Comment by vv-monsalve** [comment] 2024-06-06 21:35
Excellent! Ty.

**Comment by jenskutilek** [comment] 2024-06-07 10:21
Thank you @davelab6 for waving this through :)

I think the name length checks are a bit underdefined, there is not much concrete information in the checks to reproduce actual failing behaviour.

My hunch is that in most cases, the length is not so much a problem as the uniqueness of names inside the first 27, 32, etc. characters.

**Comment by jenskutilek** [comment] 2024-06-07 11:38
https://github.com/fonttools/fontbakery/issues/4725
https://github.com/fonttools/fontbakery/issues/2179#issuecomment-2154656242

**Comment by vv-monsalve** [comment] 2024-06-07 14:50
We continue to show and verify the 32-character combination of the family name + instance name, which is crucial in standard cases. That is, the fonts that have MSW as a target environment.

**Comment by vv-monsalve** [comment] 2024-06-14 16:23
[XELA](https://github.com/googlefonts/axisregistry/pull/158) axis has been merged.

The last remaining steps would be:

- [ ] Color palettes revision
- [ ] Article with images
- [ ] Adding the categorization info

**Closed** 2024-07-10 16:05 UTC
Labels: I New Font, II Accepted, II Custom axes, P4
