### ISSUE TITLE
Manrope font weight issue | ExtraLight is showing for every weight.

### ISSUE THREAD

**Issue by saroj-mhrn** [google/fonts#6796] opened 2023-09-27 09:38 UTC
**Describe the bug**
Every font-weight for Manrope is showing ExtaLight.

**To Reproduce**
https://codepen.io/rozex/pen/QWzrQrr

**Expected behavior**
Font weight should be different for different weights.

**Screenshots**
https://d.pr/v/5LOxK2

**Comment by kenmcd** [comment] 2023-09-27 13:30
On your demo page I see six different weights in Vivaldi (chrome) on Android.

What browser and operating system are you using?

**Comment by saroj-mhrn** [comment] 2023-09-28 04:01
It's macOS Ventura [v 13.5.1].
Browser: Chrome [v 117.0.5938.92 (Official Build) (arm64)]

**Comment by RosaWagner** [comment] 2023-09-28 15:53
Hi @saroj-mhrn, thanks for your report. Do you have this issue if you use another variable font?

**Comment by RosaWagner** [comment] 2023-09-28 16:01
Ah. I think it is just that the full font name of the variable font that is displayed at that spot instead of the family name only. 

Since the default fallback of that font is ExtraLight, this is that style name that is showed, but it doesn't prevent a proper use of the font. Variable fonts contain all the instances in one file, so "officially" Manrope ExtraLight is the name of the entire file and so all the instances. So yes, in a way, this is "Manrope ExtraLight" the font rendered for each weight style.

**Comment by RosaWagner** [comment] 2023-09-28 16:06
So closing this issue cause it is actually not a font issue, the problem is from the App

**Closed by RosaWagner** 2023-09-28 16:06 UTC
Labels: I Font Bug, -- Needs Eng team opinion

**Comment by saroj-mhrn** [comment] 2023-09-29 04:41
> Hi @saroj-mhrn, thanks for your report. Do you have this issue if you use another variable font?

Other Fonts work well. :)
