### ISSUE TITLE
Roboto Mono and monodraw.helftone.com

### ISSUE THREAD

**Issue by samoconnor** [google/fonts#1408] opened 2018-01-04 05:58 UTC
Roboto Mono does not render the output of  http://monodraw.helftone.com nicely.
The arrowheads are too big.

Roboto:
<img width="587" alt="roboto" src="https://user-images.githubusercontent.com/8266283/34551683-440371b0-f170-11e7-9a19-f74f226cf454.png">

Menlo (with `line-height: 1.3em;`)

<img width="593" alt="menlo" src="https://user-images.githubusercontent.com/8266283/34551684-44402204-f170-11e7-97b7-bfe45a45a4ae.png">

GitHub Markdown:
```
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │                                             ┌───────────────┐              │ 
 │ HTTP.request(method, uri, headers, body) -> │ HTTP.Response ├──────────────┼┐
 │   │                                         └───────────────┘              ││
 │   │                                                                        ││
 │   │    ┌──────────────────────────────────────┐       ┌──────────────────┐ ││
 │   └───▶│ request(RedirectLayer, ...)          │       │ HTTP.StatusError │ ││
 │        └─┬────────────────────────────────────┴─┐     └─────────▲────────┘ ││
 │          │ request(BasicAuthLayer, ...)         │               │          ││
 │          └─┬────────────────────────────────────┴─┐             │          ││
 │            │ request(CookieLayer, ...)            │             │          ││
 │            └─┬────────────────────────────────────┴─┐           │          ││
 │              │ request(CanonicalizeLayer, ...)      │           │          ││
 │              └─┬────────────────────────────────────┴─┐         │          ││
 │                │ request(MessageLayer, ...)           ├─────────┼──────┐   ││
```

See https://github.com/JuliaDocs/Documenter.jl/issues/618

**Comment by fitojb** [comment] 2018-01-08 10:42
This is a duplicate of #142.

**Comment by davelab6** [comment] 2018-02-06 01:44
@samoconnor thanks for reporting this, I agree this is a bug

@fitojb im not sure it is a duplicate

**Comment by mailinglists35** [comment] 2018-09-25 11:59
if this is priority 1 since Feb 6 and now it's 25 sep, how long does it take google to fix it?

**Comment by mailinglists35** [comment] 2018-09-25 12:36
for me it's not just the vertical line, but it appears to insert space between lines (see issue i referenced above). to make it more prominent, use ascii extended characters that fill all vertical space:
note also that the lines are not the same length even if there is an identical number of characters!

![2018-09-25_15-28-40](https://user-images.githubusercontent.com/2054302/46014654-b233ac80-c0d8-11e8-9502-9c93b66b2994.png)

**Comment by mailinglists35** [comment] 2018-09-25 12:39
@sladen why google can't simply look at how other opensourced free monospaced fonts are made (dejavu sans mono, liberation mono, etc) and see what is different from roboto mono?

**Comment by mailinglists35** [comment] 2018-09-25 12:44
>problem is fully understand, and a solution has been debugged, confirmed and tested.

at what step is exactly google in the above process?

**Comment by sladen** [comment] 2018-09-25 12:56
@maillists35: regarding "what is different from roboto mono?" That is a really good question, it requires debugging!

**Comment by sladen** [comment] 2018-09-25 13:00
@mailinglist35: perhaps the first thing to check is whether the box-drawing characters are coming directly from Roboto Mono, or whether these characters are being substituted (using fallback character glyphs) from another font.

**Comment by thundernixon** [comment] 2019-01-29 22:10
Moving this to issue #1832 in order to group this fixing work with a couple of closely-related bugs and to make it a bit easier for a designer to start fixing in the future.

**Closed** 2019-01-29 22:10 UTC
Labels: Priority 1 - Quick or Urgent but not Important, z_Roboto_Mono
