### ISSUE TITLE
All subsets of font family loaded when making API request

### ISSUE THREAD

**Issue by eniallator** [google/fonts#1130] opened 2017-08-08 13:43 UTC
**Description:**
When making an API request to google fonts using `https://fonts.googleapis.com/css?family=FAMILY_NAME`, it will respond with all of the family's subsets instead of just Latin. When specifying a subset using `https://fonts.googleapis.com/css?family=FAMILY_NAME&amp;subset=SUBSET_NAME`, the response will also have all of the subsets as well.

**Expected Result:**
When you don't specify a subset, the response should be just the Latin subset. When you do specify a subset, the response should be Latin as well as whatever subset(s) you have specified.

**To Recreate:**
Without subset specified:
https://fonts.googleapis.com/css?family=Roboto

With subset specified:
https://fonts.googleapis.com/css?family=Roboto&amp;subset=cyrillic,cyrillic-ext

**Comment by davelab6** [comment] 2017-08-09 19:43
Duplicate of https://github.com/google/fonts/issues/384 :)

**Closed by davelab6** 2017-08-09 19:43 UTC
