### ISSUE TITLE
Add Doto

### ISSUE THREAD

**Issue by oliverlalan** [google/fonts#7164] opened 2024-01-15 17:35 UTC
**Font Project Git Repo URL:** https://github.com/oliverlalan/PixelPanel

**Super short description of the Font Family:**
A 6x10 bitmap-inspired font featuring two variable axes: One that controls the pixel size, and another one that controls the pixel roundness.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**
![Pixel Panel - VF demo - extraLow](https://github.com/google/fonts/assets/62823573/853d6cdf-cbfb-4118-9ae6-badb47a81e0d)
![sample2](https://github.com/google/fonts/assets/62823573/193113b2-4aef-48e5-8a6f-ea88391ea05b)

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by oliverlalan** [comment] 2024-01-19 19:14
- [Repository](https://github.com/oliverlalan/PixelPanel) made public
 - Fontbakery report [here](https://github.com/oliverlalan/PixelPanel/blob/main/documentation/reports/2024-01-13%20QA.md)

**Comment by oliverlalan** [comment] 2024-01-25 06:34
@emmamarichal I am not sure if you are the right person to contact, but I have seen that you are very active here lately, so... I hope you can answer a couple of quick questions I have: 
- How often are submissions reviewed / assigned?
- Is there any way of knowing if a proposal has already been discarded?

No pressure! I know your backlog is packed. I just want to know about the process ☺️

Thank you!

**Comment by oliverlalan** [comment] 2024-01-26 19:35
Thank you so much! After all the strange looks I've received for spending time on this, that "looks great" feels like a little victory😂 @emmamarichal

It is my first time working with fonts so, if there is anything else I can do to make the cut, just let me know. I'll be glad to work on your feedback.

**Comment by kenmcd** [comment] 2024-01-26 20:25
> After all the strange looks I've received for spending time on this, that "looks great" feels like a real victory😂

Do not be discouraged by "strange looks" from non-believers.
This is a very cool font.
Very retro, nice niche, and variable!
People are going to love and use this font.

**Comment by davelab6** [comment] 2024-04-16 15:53
@oliverlalan @sos0 I am happy to say this is accepted overall, and I'm so happy to see the axes already conform to the [Google Fonts Axis Registry](https://github.com/googlefonts/axisregistry) :) 

Since it is UFO based, I am assigning to @emmamarichal who is seeking an opportunity to learn how to onboard UFOs; the most common source is .glyphs but the new builder2 tool is expected to handle designSpace/UFO sources just as well, so this project may be a good opportunity for Emma to test builder2.

@oliverlalan To answer your questions directly, 

> How often are submissions reviewed / assigned?

This year we are doing more strict quarterly planning, so we are working to clear out the [|| Submissions](https://github.com/google/fonts/issues?q=is%3Aopen+label%3A%22II+Submission%22+sort%3Aupdated-desc) label at least every 3 months. 

> Is there any way of knowing if a proposal has already been discarded?

Yes, the issue's `|| Submission` label turns to `|| Accepted` or the issue is closed :)

**Comment by oliverlalan** [comment] 2024-04-17 11:12
@davelab6 Yeehaw! I am so happy with the news! Thank you for the answers :)

@emmamarichal I don't know what the next steps are. So, I hope you can guide me through the process. I am not a typographer, nor a full-time programmer, but I am quite good following instructions, so just tell me what you need me to do, and I'll do my best.

A couple of things before going further:
- I am considering renaming the font. While "Pixel Panel" is very descriptive, I feel it lacks personality. I have thought about "Doto", aligned with the nature of the font's nature, and much more friendly. I have already checked that [it is unique](https://namecheck.fontdata.com/?q=doto). Any problem with it?
- What are the steps from now onwards? I would like to create some promotional material before going live, and would be nice to know about the times.

Regards!

**Comment by emmamarichal** [comment] 2024-04-17 11:48
@oliverlalan "Doto" sounds nice to me, any objections @davelab6? :)

I'll let you know when I start to review it, and probably send you a list of what you need to do (I'll inspect if the font respect the specs of Google Fonts). But maybe that's good enough, and you'll hardly have to do anything :)

When the fonts will be exported and tested, these are the following steps:
- Add your designer profile to the catalog so it can appear on the specimen page
- Add category tags to the font
- Prepare promotion (images, description)

I'll send you a email later, about all of this.
But no rush, once the fonts are ready, it can several weeks before appearing on the API :)

I'll let you know, thanks again for this submission!

**Comment by davelab6** [comment] 2024-04-17 14:35
No, it sounds kind of like `Noto` but its fine to use :)

**Comment by emmamarichal** [comment] 2024-05-01 14:11
@oliverlalan, I opened an issue with the review in the repo: https://github.com/oliverlalan/PixelPanel/issues/2

Cheers :)

**Comment by oliverlalan** [comment] 2024-05-02 09:01
@emmamarichal 

Got it!

I'm having busy days, I'll try to work on the pending things this and next week.

Thank you for the feedback

**Comment by emmamarichal** [comment] 2024-06-25 10:05
Can be moved in Q3 @chrissimpkins

**Comment by oliverlalan** [comment] 2024-07-10 12:44
@emmamarichal I already merged your commits. Please, let me know if there is anything pending from my side.

**Comment by sos0** [comment] 2024-08-14 00:07
@emmamarichal Hi, is the upstream label still relevant?

**Comment by vv-monsalve** [comment] 2024-08-14 00:18
@sos0 Yes, it informs us that the process is still ongoing.

**Closed** 2024-10-15 14:04 UTC
Labels: I New Font, II Accepted, P4
