### ISSUE TITLE
Inter font is missing italics

### ISSUE THREAD

**Issue by alexleduc76** [google/fonts#3737] opened 2021-08-15 12:34 UTC
There are static and variable versions of inter and they all have italics, so it's surprising that Google Fonts only has the different font weights. Can you please add them?

You can find them in the author's repo
https://github.com/rsms/inter

**Comment by fanninpm** [comment] 2021-09-07 14:26
Duplicate of #2386

**Closed** 2021-09-28 00:04 UTC
