### ISSUE TITLE
Open Sans latin,latin-ext,greek,greek-ext files big

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [google/fonts#230] opened 2016-03-21 11:09 UTC
There's an issue with subsetting Open Sans. 

latin,latin-ext,greek,greek-ext woff files also have other characters making file sizes upto 90KB/font. 

This is because other subsets also appear in the font file. 

This can be checked by loading 

https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700,700italic&subset=latin,latin-ext,greek,greek-ext

in a browser which doesn't support woff2 such as Safari or Edge. 

Possible to have a lower file size?

**Comment by rsheeter** [comment] 2016-03-21 16:08
This is by design; in absence of unicode-range we may choose to deliver the entire font for some requests. That is what is happening here. 

Vote for unicode-range for Edge [here](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6510254-unicode-range) :)

**Comment by laerm0** [comment] 2017-09-19 17:28
Do you think we can close this, @rsheeter?

**Comment by davelab6** [comment] 2017-09-19 18:20
I do :)

**Closed by davelab6** 2017-09-19 18:20 UTC
Labels: z_Open_Sans
