### ISSUE TITLE
Droid Sans Fallback has some incorrect zero width glyphs

### ISSUE THREAD

**Issue by mikeday** [google/fonts#1352] opened 2017-11-23 02:51 UTC
I'm not sure if this is the right place to report this issue, but we've found a problem with Droid Sans Fallback, specifically version 1.00c, where the following Chinese glyphs have zero width when they should have a horizontal advance width of 256 like all the others:

affected glyph indices: 3971, 4042, 5033, 5455, 6407

**Comment by fitojb** [comment] 2017-11-23 13:39
I believe Droid Sans Fallback is deprecated at this point, having the Noto project being launched as its succesor and given that this font is no longer used in Android. You may want to simply switch to Noto, as I don't think this font will be further developed.

**Comment by davelab6** [comment] 2017-11-24 17:07
Thanks for reporting this. Would you like to start a new renamed upstream
for this project and fix it?

On Nov 23, 2017 6:39 AM, "Adolfo Jayme-Barrientos" <notifications@github.com>
wrote:

I believe Droid Sans Fallback is deprecated at this point, having the Noto
project being launched as its succesor and given that this font is no
longer used in Android. You may want to simply switch to Noto, as I don't
think this font will be further developed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/fonts/issues/1352#issuecomment-346620781>, or mute
the thread

**Comment by mikeday** [comment] 2017-11-24 23:20
Honestly I've never actually edited a font, what's the best tool for changing glyph metrics?

**Comment by jfkthame** [comment] 2017-12-04 12:57
Can someone point to a specific testcase where the issue shows up? (It'll be easier to look into it if we don't have to reverse-map those glyph IDs to characters, track down the exact font version, etc.)

**Comment by mikeday** [comment] 2017-12-05 02:17
Try this HTML:
```
<div style="font-family: Droid Sans Fallback">䆡䆡䆡䆡䆢</div>
```
The first repeated character has zero advance width, so all of the characters will be displayed on top of each other in Chrome and Safari. This is with Droid Sans Fallback v1.00c.

**Comment by jfkthame** [comment] 2017-12-05 09:50
I see the same thing in Firefox (Nightly), too. But with Droid Sans Fallback v2.53, which I also happen to have on hand, it looks fine. So this seems to be a problem in an outdated version of the font, and the "fix" is to use a newer one.

(Or switch to another font such as the Noto family, of course, but that's potentially a more disruptive change. But as far as Droid Sans Fallback is concerned, it looks like this was fixed long ago, and 1.00c is simply obsolete.)

**Comment by mikeday** [comment] 2017-12-05 09:54
Do you see the same problem in Firefox 57? Because I was surprised to find that it looked correct in that version of the browser.

What is the canonical source for the Droid Sans Fallback font?

**Comment by jfkthame** [comment] 2017-12-05 10:00
> Do you see the same problem in Firefox 57? Because I was surprised to find that it looked correct in that version of the browser.

Yes, just double-checked. (On macOS; which platform are you using? Can you check in the DevTools Inspector to confirm it really was using that font, not some other fallback?)

> What is the canonical source for the Droid Sans Fallback font?

I don't know; presumably somewhere at Google. I think the copies I have on hand were pulled for testing purposes from various old Android phones.

**Comment by mikeday** [comment] 2017-12-05 10:49
On Linux (Ubuntu 16.04, Firefox 57) the glyphs do _not_ overlap, even though on Chrome running on the same system they do. I checked with the Inspector and it is using the correct font file, specified using an @font-face rule.

**Comment by jfkthame** [comment] 2017-12-05 13:49
Yes, I see the same result.

On Linux, Firefox gets glyph widths via Freetype; it appears FT is in some way "fixing" the advance width of these unexpectedly-zero-width glyphs. If I patch Linux Firefox to get widths directly from the font tables (as it does on macOS), then I see the issue there as well.

So if you want to investigate this further, it appears it's a question for the Freetype project: why/how does it correct these glyphs, and is this intended behavior or a bug? But as far as Droid Sans Fallback is concerned, it's simply a bug in that old version, that has already been fixed in a more recent release.

**Comment by mikeday** [comment] 2017-12-05 21:32
Thanks, I will pursue it with the FreeType developers.

**Comment by laerm0** [comment] 2018-02-26 18:50
If @mikeday has taken this to FT for discussion, we can probably close it here...yes?

**Closed** 2021-12-01 16:28 UTC
Labels: II Font Bug
