### ISSUE TITLE
Shantell Sans Russian letter "ь" doesn't appear in the screen in Android Studio

### ISSUE THREAD

**Issue by rokapoz** [google/fonts#7508] opened 2024-04-01 22:22 UTC
Listnr feedback: Hello! Font "Shantell Sans" has a little problem. The letter in Russian language "ь" doesn't appear in the screen in Android Studio.

**Comment by chrissimpkins** [comment] 2024-05-03 18:58
@emmamarichal Mind having a look into this to see if there is a problem with this glyph in Shantell Sans? Ty!

**Comment by arrowtype** [comment] 2024-05-10 12:37
@rokapoz Would you potentially be able to share a screenshot of this, and describe what you expect, vs how exactly it’s not showing up? For example, is it just invisible in Cyrillic text, or is it replaced by a "notdef" block, or something else? Do any other Cyrillic characters have similar issues? I’m not familiar with Android Studio, so it’s hard for me to even guess at what you’re having trouble with. Did you download the font from [its Google Fonts page](https://fonts.google.com/specimen/Shantell+Sans), or from [its repo](https://github.com/arrowtype/shantell-sans/releases), or did you get it somewhere else?

@chrissimpkins The character shows up on Google Fonts and in Font Goggles when I copy & paste it in, so I don’t think it’s an issue in the source fonts. Maybe it’s something to do with subsetting, or maybe Android Studio has an issue?

<img width="988" alt="image" src="https://github.com/google/fonts/assets/45946693/49b03128-a923-4aa5-a458-df60ddc28677">

<img width="681" alt="image" src="https://github.com/google/fonts/assets/45946693/1ebbcb8a-646e-42c2-9065-ed4800a8e03b">

**Comment by emmamarichal** [comment] 2024-06-13 13:06
@rokapoz I close this issue for now, since we can't reproduce it. Please feel free to re-open it, if you still have the issue (with screenshots and more details if you have).
Thank you :)

**Closed by emmamarichal** 2024-06-13 13:06 UTC
Labels: I Font Bug
