### ISSUE TITLE
Open Sans 400 not rendering

### ISSUE THREAD

**Issue by eugeneross** [google/fonts#272] opened 2016-06-16 23:01 UTC
Since the Google Fonts site update, my project that uses Open Sans at a weight of 400 will not render at all within my project in any browser. I am able to render 600 weighted Open Sans and many other fonts at 400 without issue. I primarily use the `@import` method, but have tried different URL strings as well as different ways to include this exact font. My examples are below:

In my `style.sass` file
`@import url("https://fonts.googleapis.com/css?family=Open+Sans:400,600")`

Within the `head` of my `index.pug` file:
`link(rel='stylesheet', href='build/css/style.css')`

All examples compile fine to CSS with no browser errors.

**Comment by davelab6** [comment] 2016-07-17 23:53
@eugeneross please try uninstalling the fonts

**Comment by rscotton** [comment] 2017-02-21 15:20
+1 on this one - I have no fonts installed locally, but the problem remains. Here's a codepen demonstrating: http://codepen.io/rscotton/pen/egqMKP

Any progress on this one? Can anyone offer a solid work-around other than installing the fonts locally?

**Comment by eugeneross** [comment] 2017-02-24 17:29
I found my issue a while back. Be sure to check and see if you have the fonts that are giving you issues ON in Adobe TypeKit. Once I turned that OFF my issues was resolved.

**Comment by rscotton** [comment] 2017-02-25 01:16
@eugeneross thank you so much! I had search locally installed fonts through FontBook, but hadn't looked through my Creative Cloud TypeKit settings in forever - sure enough, this was the cause.

**Comment by allankikkas** [comment] 2017-05-31 18:29
Can confirm, this is creative cloud caused issue.

**Comment by davelab6** [comment] 2017-05-31 19:04
Thanks! I've contacted a friend at Adobe :)

**Comment by laerm0** [comment] 2017-09-08 14:37
As this appears to not be caused by Google Fonts, I am closing.

**Closed by laerm0** 2017-09-08 14:37 UTC
Labels: z_Open_Sans
